/// Filipino translations for `OnboardingCopy`.
///
/// Keys match member names (`member.case` for switch arms). Templated members
/// use `{0}`, `{1}` … placeholders; list members join items with `|`.
/// Missing keys fall back to English.
///
/// Authored without native-speaker review — proofread before release.
library;

const copyFil = <String, String>{
  'letsSetYouUpTitle': 'Ihanda natin ang iyong account',
  'letsSetYouUpSubtitle':
      'Magkuwento ka nang kaunti tungkol sa iyo para\nma-personalize ang iyong pag-aaral.',
  'fullNameLabel': 'Buong pangalan',
  'countryLabel': 'Bansa',
  'gradeLevelLabel': 'Antas ng baitang',
  'preferredLanguageLabel': 'Piniling wika',
  'continueLabel': 'Magpatuloy',
  'improveExperienceNote':
      'Patuloy naming pagbubutihin ang karanasang ito\npara sa iyo.',
  'chooseSubjectsTitle': 'Piliin ang iyong mga asignatura',
  'chooseSubjectsSubtitle':
      'Piliin ang mga asignaturang gusto mong pag-aralan.\nMaaari mo itong baguhin anumang oras.',
  'customizeLaterNote': 'Maaari ka pang mag-customize mamaya.',
  'preferencesTitle': 'Paano mo gustong matuto?',
  'preferencesSubtitle':
      'Piliin ang iyong mga kagustuhan. Mababago mo ito\nanumang oras.',
  'studyGoalLabel': 'Layunin sa pag-aaral',
  'dailyStudyTimeLabel': 'Araw-araw na oras ng pag-aaral',
  'adaptivePretestLabel': 'Magpatuloy sa adaptive na pretest',
  'personalizePathNote':
      'Nakakatulong ito para ma-personalize ang iyong landas sa pagkatuto.',
  'preferenceCallout':
      'Umaangkop ang WICARA sa iyo, sa bilis mo, sa istilo mo,\nat sa mga layunin mo.',
  'profileTitle': 'Profile',
  'profileSubtitle': 'Pamahalaan ang iyong mga kagustuhan sa pag-aaral at account.',
  'homeLabel': 'Home',
  'learnLabel': 'Mag-aral',
  'progressLabel': 'Progreso',
  'learningSetupTitle': 'Setup sa pagkatuto',
  'preferencesSectionTitle': 'Mga kagustuhan',
  'subjectsLabel': 'Mga asignatura',
  'logoutLabel': 'Mag-log out',
  'welcomeBack': 'Maligayang pagbabalik,\n',
  'homeSubtitle':
      'Handa ka na bang magpatuloy sa pag-aaral at gumawa ng kahanga-hanga ngayon?',
  'languageLabel': 'Wika',
  'getStartedLabel': 'Magsimula',
  'alreadyHaveAccountLabel': 'Mayroon na akong account',
  'signInTitle': 'Maligayang pagbabalik',
  'signInSubtitle': 'Mag-sign in para ipagpatuloy ang iyong pag-aaral',
  'registerTitle': 'Gumawa ng iyong account',
  'registerSubtitle':
      'Magparehistro nang isang beses, pagkatapos ay ipagpatuloy ang iyong landas sa pagkatuto',
  'emailOrPhoneLabel': 'Email o telepono',
  'emailOrPhoneHint': 'Ilagay ang iyong email o telepono',
  'emailLabel': 'Email',
  'emailHint': 'Ilagay ang iyong email',
  'passwordLabel': 'Password',
  'passwordHint': 'Ilagay ang iyong password',
  'fullNameHint': 'Ilagay ang iyong buong pangalan',
  'forgotPasswordLabel': 'Nakalimutan ang password?',
  'signInLabel': 'Mag-sign in',
  'registerLabel': 'Magparehistro',
  'logInLabel': 'Mag-log in',
  'orContinueWithLabel': 'o magpatuloy gamit ang',
  'securityNoteLabel': 'Pribado at ligtas ang iyong data.',
  'cancelLabel': 'Kanselahin',
  'applyLabel': 'Ilapat',
  'searchLabel': 'Maghanap',
  'recommendedLabel': 'Inirerekomenda',
  'tracksLabel': 'Mga track',
  'galleryLabel': 'Gallery',
  'viewAllLabel': 'Tingnan lahat',
  'nextUpLabel': 'Susunod',
  'exploreLabel': 'Tuklasin',
  'currentStreakLabel': 'Kasalukuyang streak',
  'backToHomeLabel': 'Bumalik sa Home',
  'continueLearningLabel': 'Magpatuloy sa Pag-aaral',
  'learningGoalTitle': 'Ano ang gusto mong pag-aralan?',
  'learningGoalSubtitle':
      'I-type muna ang iyong layunin. Hahanapin ng WICARA ang tumutugmang node ng materyal, pagkatapos ay magsisimula ang pretest kapag kinumpirma mo ito.',
  'learningTopicLabel': 'Paksa ng pag-aaral',
  'generatePretestLabel': 'Bumuo ng Pretest',
  'typeATopicHint': 'Mag-type ng paksa',
  'loadingPretestLabel': 'Nilo-load ang pretest',
  'pretestUnavailableLabel': 'Hindi available ang pretest',
  'tryAgainLabel': 'Subukan ulit',
  'preTestLabel': 'Pretest',
  'postTestLabel': 'Posttest',
  'refreshLabel': 'I-refresh',
  'retryLabel': 'Subukan ulit',
  'backLabel': 'Bumalik',
  'undoLabel': 'I-undo',
  'redoLabel': 'I-redo',
  'teacherReviewLabel': 'Pagsusuri ng guro',
  'insightsLabel': 'Mga insight',
  'knowledgeMapLabel': 'Mapa ng Kaalaman',
  'learningReportLabel': 'Ulat sa Pagkatuto',
  'reviewNowLabel': 'Repasuhin ngayon',
  'reviewDueLabel': 'Dapat repasuhin',
  'studyGoalOptionalLabel': 'Layunin sa pag-aaral (opsyonal)',
  'dailyStudyTimeOptionalLabel': 'Oras ng pag-aaral araw-araw (opsyonal)',
  'learnSubtitleRecommended': 'Mga mungkahing track para matulungan kang maabot ang iyong mga layunin.',
  'learnSubtitleTracks': 'Tuklasin ang iyong mga learning track o gumawa ng bago rito.',
  'learnSubtitleGallery': 'Balikan ang mga video at buod mula sa iyong learning journey.',
  'todaysLearningQueueLabel': 'Learning queue ngayong araw',
  'continueSessionLabel': 'Ipagpatuloy ang session',
  'wantToLearnSomethingNewLabel': 'Gusto mong matuto ng bago?',
  'exploreTracksDescription': 'Tuklasin ang mga track na ginawa mo o magsimula ng iba.',
  'streakDaysLabel': '{0} araw',
  'dailyEvaluationLabel': 'Pang-araw-araw na pagsusuri',
  'dailyEvaluationPrompt': '. Pumili ng confidence score kung gusto mo, tapos gawin ang daily check mo.',
  'takeDailyEvaluationLabel': 'Gawin ang Daily Evaluation',
  'dailyEvalsWordmark': 'Daily Evals',
  'dailyEvalsQuickCheckin': 'Mabilisang check-in para sa learning path mo ngayong araw.',
  'finishDailyEvalsLabel': 'Tapusin ang Daily Evals',
  'dailyQuestionProgressLabel': '{0} sa {1}',
  'reviewDueSummaryLabel': '{0} item ang handang balikan',
  'retentionForecastLabel': 'Ang forecast ng iyong retention',
  'retentionForecastBasisLabel': 'Batay sa MVP ng Ebbinghaus forgetting curve.',
  'retentionCoachingLabel': 'Magpatuloy sa pagbabalik-aral para umangat ang curve at gumanda ang long-term retention.',
  'evaluationCompleteLabel': 'Tapos na ang Pagsusuri 🎉',
  'evaluationCompleteSubtitle': 'Magaling! Nagtatayo ka ng pangmatagalang kaalaman.',
  'reviewedLabel': 'Nabalikan',
  'toReviewAgainLabel': 'Babalikan muli',
  'scoreLabel': 'Iskor',
  'reviewedConceptsLabel': 'Mga konseptong nabalikan',
  'noReviewedConceptsLabel': 'Wala pang konseptong nabalikan',
  'continueLearningReason': 'Pumunta sa iyong learning path.',
  'statusGoodLabel': 'Mabuti',
  'statusStrongLabel': 'Matatag',
  'statusReviewLabel': 'Balikan',
  'retentionLiftLabel': 'Retention Lift',
  'daysUntilNextReviewLabel': 'Araw Bago ang Susunod na Review',
  'learnSomethingNewLabel': 'Matuto ng bago',
  'newTrackDescription': 'Gumawa ng bagong track sa labas ng kasalukuyan mong listahan.',
  'newTrackLabel': 'Bagong track',
  'progressSubtitle': 'Magsimula sa iyong learning report, tapos tuklasin ang knowledge map.',
  'learningReportDescription': 'Lingguhang performance, naayos na gaps, nabuksang konsepto.',
  'fixedGapsLabel': 'Naayos na gaps',
  'remainingGapsLabel': 'Natitirang gaps',
  'thisWeekFixedDelta': '+4 ngayong linggo',
  'thisWeekRemainingDelta': '-2 ngayong linggo',
  'learningReportHint': 'I-hover o i-tap ang isang linggo para makita ang growth, naayos na gaps, at memory lift.',
  'retentionDeltaLabel': '+{0}% retention',
  'weekLabel': 'L{0}',
  'knowledgeMapDescription': 'Tuklasin ang mga subject domain at prerequisite path.',
  'fallbackGraphLabel': 'Static fallback graph',
  'liveCurriculumGraphLabel': 'Live knowledge graph',
  'nodeCountLabel': '{0} node',
  'masteryConfidenceLabel': 'Mastery confidence',
  'aboutThisConceptLabel': 'Tungkol sa konseptong ito',
  'relatedConceptsLabel': 'Mga kaugnay na konsepto',
  'noDirectRelatedConceptLabel': 'Walang direktang kaugnay na konsepto',
  'crossSubjectConnectionsLabel': 'Cross-subject na koneksyon',
  'graphOfGraphsHint': 'Nakikita ang mga Graph of Graphs link kapag available.',
  'conceptBridgeFallbackLabel': 'Concept bridge',
  'conceptFallbackDescription': 'Konsepto sa prerequisite graph.',
  'confidenceQuestionLabel': 'Gaano ka kakumpiyansa?',
  'yourKnowledgeStateLabel': 'Ang estado ng iyong kaalaman',
  'personalizedPathGeneratedLabel': 'Nabuo ang personalized path',
  'personalizedPathDescription': 'Magsimula sa prerequisites, tapos magsanay sa root-cause na tanong.',
  'continueToMyPathLabel': 'Ipagpatuloy sa aking path',
  'missingPrerequisiteGapsLabel': 'Kulang na prerequisite gaps',
  'learnerLabel': 'Mag-aaral',
  'statusLabel': 'Status',
  'couldNotLoadQueueLabel': 'Hindi ma-load ang queue',
  'nothingToReviewLabel': 'Walang babalikan',
  'reviewItemLabel': 'Review item',
  'flaggedForReviewLabel': 'Na-flag para sa review.',
  'learningGoalDiagnosisLabel': 'Diagnosis ng learning goal',
  'learnerAskedLabel': 'Tanong ng mag-aaral',
  'subjectSingularLabel': 'Asignatura',
  'suggestedConceptIdLabel': 'Iminungkahing concept id',
  'confidenceLabel': 'Kumpiyansa',
  'reasoningEvaluationLabel': 'Pagsusuri sa pangangatwiran',
  'learnerReasoningLabel': 'Pangangatwiran ng mag-aaral',
  'answerScoreLabel': 'Iskor ng sagot',
  'reasoningScoreLabel': 'Iskor ng pangangatwiran',
  'evidenceScoreLabel': 'Iskor ng ebidensya',
  'overrideConceptIdLabel': 'I-override ang na-diagnose na prerequisite concept id. Ang pagkumpirma ay nagtatakda ng diagnosis status sa "confirmed".',
  'correctedOfReviewedLabel': '{0} naitama sa {1} na sinuri',
  'noReviewedItemsLabel': 'Wala pang sinuring item.',
  'reviewedCountLabel': '{0} ang nasuri',
  'darkCorrectedLightReviewedLabel': 'Madilim = naitama · maliwanag = nasuri',
  'reviewArtifactLabel.question': 'Tanong',
  'reviewArtifactLabel.diagnosis': 'Diagnosis',
  'reviewArtifactLabel.evaluation': 'Pagsusuri',
  'reviewArtifactLabel.open': 'Bukas',
  'reviewArtifactLabel.approved': 'Naaprubahan',
  'reviewArtifactLabel.rejected': 'Tinanggihan',
  'reviewArtifactLabel.corrected': 'Naitama',
  'reviewArtifactLabel.all': 'Lahat',
  'reviewArtifactLabel.low_confidence': 'Mababang kumpiyansa',
  'reviewArtifactLabel.risk_signal': 'Senyales ng panganib',
  'reviewArtifactLabel.sampled': 'Nasample',
  'reviewArtifactLabel.learner_flag': 'Flag ng mag-aaral',
  'overallMasteryLabel': 'Kabuuang mastery',
  'streakSummaryLabel': '🔥 {0}-araw na streak · pinakamahaba {1} · {2} aktibong araw',
  'masteryBySubjectLabel': 'Mastery ayon sa asignatura',
  'noSubjectDataLabel': 'Wala pang datos ng asignatura.',
  'streakDaysShortLabel': '{0}a',
  'scoreTrendLabel': 'Trend ng iskor',
  'needsReviewLabel': 'Kailangang balikan ({0})',
  'edgeAiStatusReadFailedLabel': 'Nabigong basahin ang edge runtime status: {0}',
  'edgeAiStatusChecking': 'sinusuri',
  'edgeAiStatusUnknown': 'hindi alam',
  'edgeAiStatusReady': 'handa',
  'edgeAiStatusNeedsInit': 'kailangang-simulan',
  'edgeAiStatusNeedsInstall': 'kailangang-i-install',
  'todaysTopicLabel': 'Paksa ngayong araw: ',
  'notConfidentLabel': 'Hindi kumpiyansa',
  'veryConfidentLabel': 'Sobrang kumpiyansa',
  'nextQuestionLabel': 'Susunod na tanong',
  'highImpactLabel': 'Malaking epekto',
  'maintainedLabel': 'Napanatili',
  'correctLabel': 'Tama',
  'pendingLabel': 'Nakabinbin',
  'recommendedNextActionsLabel': 'Mga inirerekomendang susunod na hakbang',
  'spacedRepetitionImpactLabel': 'Epekto ng spaced repetition',
  'memoryStrengthenedLabel': 'Napatibay mo ang iyong memorya.',
  'contentGalleryLabel': 'Content Gallery',
  'contentGalleryDescription': 'Nandito lahat ng videong nagawa dati, handang panoorin ulit kasama ang mga notes na tinipon ng WICARA para sa iyo.',
  'notesLabel': 'Mga tala',
  'cheatsheetSummaryLabel': 'Buod ng cheatsheet',
  'recommendedForCurrentReadinessLabel': 'Inirerekomenda para sa Calculus I batay sa\nkasalukuyan mong gaps at readiness.',
  'fixedShortLabel': '+4 naayos',
  'overallLabel': 'Kabuuan',
  'applicationLabel': 'Aplikasyon',
  'analysisLabel': 'Pagsusuri',
  'completeLabel': 'Kumpleto',
  'skillGrowthLabel': 'Paglago ng kasanayan',
  'remainingCountLabel': '{0} ang natitira',
  'loadingCurriculumLabel': 'Nilo-load ang kurikulum mula sa backend...',
  'prerequisiteLayerLabel': 'Prerequisite layer',
  'combinedLayerLabel': '{0} + {1} pa',
  'prerequisitesLabel': 'Mga prerequisite',
  'noDirectPrerequisiteLabel': 'Walang direktang prerequisite',
  'relatedBadgeLabel': 'KAUGNAY',
  'bypassForWebDevLabel': 'Bypass para sa web dev',
  'passwordResetMockedMessage': 'Naka-mock pa ang password reset sa ngayon.',
  'emailRequiredMessage': 'Ilagay ang iyong email',
  'fullNameRequiredMessage': 'Ilagay ang iyong buong pangalan',
  'registrationEmailValidationMessage': 'Gumamit ng email address para sa pagpaparehistro',
  'passwordMinLengthMessage': 'Dapat hindi bababa sa 6 na karakter ang password',
  'adaptivePretestReadyNextLabel': 'Handa na ang adaptive pretest',
  'adaptivePretestReadyDescription': 'Ilang tanong ang magka-calibrate ng starting point mo.',
  'pretestGeneratedCompleteLabel': 'Kumpleto na ang pretest na nabuo!',
  'openingAdaptivePretestLabel': 'Binubuksan na ang iyong adaptive pretest.',
  'lowLabel': 'Mababa',
  'highLabel': 'Mataas',
  'basedOnYourResponsesLabel': 'Batay sa iyong mga sagot.',
  'whatsNextLabel': 'Ano ang susunod',
  'retakePretestAnytimeLabel': 'Puwede mong ulitin ang pretest anumang oras.',
  'currentTopicLabel': 'Kasalukuyang paksa',
  'askOrReflectHereHint': 'Magtanong o mag-reflect dito...',
  'speechReadAloud': 'Basahin nang malakas',
  'speechReadAloudHint': 'Basahin ang nilalamang ito gamit ang boses',
  'speechStop': 'Itigil ang pagsasalita',
  'speechStopHint': 'Itigil ang aktibong speech o voice input',
  'speechPause': 'I-pause',
  'speechResume': 'Ituloy',
  'speechSpeed': 'Bilis ng pagsasalita',
  'speechSpeedValue': '{0} beses',
  'speechVoiceInput': 'Voice input',
  'speechVoiceInputHint': 'Simulan o itigil ang voice recording',
  'speechListening': 'Nakikinig...',
  'speechProcessing': 'Pinoproseso...',
  'speechSpeaking': 'Nagsasalita',
  'speechPaused': 'Naka-pause ang speech',
  'speechError': 'Speech error',
  'speechMicPermissionDenied': 'Tinanggihan ang pahintulot sa mikropono',
  'speechMicPermissionInstructions': 'I-enable ang microphone permission sa device settings para magamit ang voice input.',
  'speechServiceUnavailable': 'Hindi available ang speech service',
  'correctionMetricsLabel': 'Correction metrics',
  'typeLabel': 'Uri',
  'triggerLabel': 'Trigger',
  'allFilterLabel': 'lahat',
  'noAiOutputsMatchFiltersLabel': 'Walang AI output na tumutugma sa mga filter na ito ngayon.',
  'noSummaryLabel': '(walang buod)',
  'itemNotFoundLabel': 'Hindi nahanap ang item.',
  'approveThisOutputLabel': 'Aprubahan ang output na ito',
  'rejectThisOutputLabel': 'Tanggihan ang output na ito',
  'optionalNoteHint': 'Opsyonal na tala',
  'whyIsItWrongHint': 'Bakit mali? (kailangan)',
  'approveLabel': 'Aprubahan',
  'rejectLabel': 'Tanggihan',
  'correctLabelAction': 'Itama',
  'approvedLabel': 'Naaprubahan',
  'rejectedLabel': 'Tinanggihan',
  'correctionSavedLabel': 'Na-save ang pagwawasto',
  'correctionFailedLabel': 'Nabigo ang pagwawasto',
  'resolveSuccessLabel': '{0} · hindi apektado ang mga mag-aaral sa real time',
  'resolveFailureLabel': 'Nabigo ang {0}',
  'flaggedBecauseLabel': 'Na-flag dahil sa: {0}',
  'artifactLabel': 'Artifact',
  'artifactUnavailableLabel': 'Hindi ma-load ang pinagbatayang artifact (baka natanggal na). Available pa rin ang review record.',
  'generatedQuestionLabel': 'Nabuong tanong',
  'promptLabel': 'Prompt',
  'helperLabel': 'Helper',
  'optionsLabel': 'Mga pagpipilian',
  'expectedReasoningLabel': 'Inaasahang pangangatwiran',
  'generationSourceLabel': 'Pinagmulan ng generation',
  'noneLabel': '(wala)',
  'alternativesLabel': 'Mga alternatibo',
  'candidateCountLabel': '{0} kandidato',
  'modelLabel': 'Modelo',
  'isCorrectLabel': 'Tama ba?',
  'yesLabel': 'Oo',
  'noLabel': 'Hindi',
  'diagnosticSignalLabel': 'Diagnostic signal',
  'historyLabel': 'Kasaysayan',
  'correctArtifactTitle': 'Itama ang {0}',
  'saveCorrectionLabel': 'I-save ang pagwawasto',
  'artifactNotCorrectableLabel': 'Hindi maitatama ang ganitong uri ng artifact.',
  'optionsTapCorrectLabel': 'Mga pagpipilian (i-tap ang bilog para markahan ang tama)',
  'optionNumberLabel': 'Pagpipilian {0}',
  'teacherFeedbackLabel': 'Feedback ng guro',
  'auditNoteLabel': 'Tala (audit log)',
  'humanCorrectionRateLabel': 'Rate ng pagwawasto ng tao',
  'backlogLabel': 'Backlog',
  'oldestBacklogLabel': 'pinakamatanda {0}a',
  'noneOpenLabel': 'walang bukas',
  'correctionRateByTypeLabel': 'Rate ng pagwawasto ayon sa uri',
  'triggerPrecisionLabel': 'Katumpakan ng trigger',
  'triggerPrecisionDescription': 'Sa mga item na na-flag ng trigger, ilan ang talagang kailangang ayusin (naitama o tinanggihan). Mas mataas = mas sulit sa oras ng guro ang trigger.',
  'noResolvedItemsLabel': 'Wala pang naresolbang item.',
  'lastFourteenDaysLabel': 'Huling 14 na araw',
  'noActivityFourteenDaysLabel': 'Walang aktibidad sa nakalipas na 14 na araw.',
  'noMetricsYetLabel': 'Wala pang metrics.',
  'flagForTeacherLabel': 'I-flag para sa guro',
  'flagForTeacherDescription': 'Sabihin sa amin kung ano ang mukhang mali. Rerepasuhin ito ng guro — tuloy pa rin ang pag-aaral mo.',
  'flagReasonHint': 'hal. mukhang mali ang minarkahang sagot',
  'sendLabel': 'Ipadala',
  'flagSentLabel': 'Naipadala sa guro para suriin. Salamat!',
  'flagFailedLabel': 'Hindi maipadala ang flag sa ngayon.',
  'flaggedLabel': 'Na-flag',
  'looksWrongLabel': 'Mukhang mali?',
  'insightsUnavailableLabel': 'Walang available na insights',
  'insightsSummaryLabel': '{0} asignatura · {1} konsepto · {2} pagsubok',
  'masteredCountLabel': '{0}/{1} na-master',
  'masteredLabel': 'Na-master',
  'attemptsPerDayLabel': 'Pagsubok/araw',
  'periodLabel': 'Panahon:',
  'trendPeriodLabel.month': 'buwan',
  'trendPeriodLabel.all': 'lahat',
  'notEnoughHistoryLabel': 'Kulang pa ang history.',
  'nothingAtRiskLabel': 'Walang nanganganib — magaling!',
  'atRiskDetailLabel': '{0} · mastery {1}{2}',
  'overdueSuffixLabel': ' · {0}a na overdue',
  'edgeAiSettingsTitle': 'Local AI settings',
  'edgeAiSettingsSubtitle': 'I-install, i-initialize, at i-test ang LiteRT-LM model sa isang lugar.',
  'edgeAiHideModelUrlLabel': 'Itago ang model URL',
  'edgeAiShowModelUrlLabel': 'Palitan ang model URL (advanced)',
  'edgeAiModelUrlLabel': 'Model URL (.litertlm)',
  'edgeAiInstallingLabel': 'Ini-install...',
  'edgeAiInstallModelLabel': 'I-install ang modelo',
  'edgeAiReinstallLabel': 'I-reinstall',
  'edgeAiInitializingLabel': 'Ini-initialize...',
  'edgeAiInitializeLabel': 'I-initialize',
  'edgeAiUnloadLabel': 'I-unload',
  'edgeAiRunningLabel': 'Tumatakbo...',
  'edgeAiRunTestPromptLabel': 'Patakbuhin ang test prompt',
  'edgeAiDownloadLabel': 'I-download ang modelo: {0}',
  'edgeAiDownloadedLabel': '{0} ang na-download',
  'edgeAiEnterModelUrlLabel': 'Ilagay muna ang model URL.',
  'edgeAiModelAlreadyPresentLabel': 'Nasa device na ang modelo ({0}).',
  'edgeAiModelReinstalledLabel': 'Na-reinstall ang modelo ({0} sa {1} ms).',
  'edgeAiModelInstalledLabel': 'Na-install ang modelo ({0} sa {1} ms).',
  'edgeAiInstallFailedLabel': 'Nabigo ang pag-install ng modelo: {0}',
  'edgeAiUnloadedLabel': 'Na-unload ang modelo mula sa runtime memory.',
  'edgeAiUnloadFailedLabel': 'Nabigo ang pag-unload ng modelo: {0}',
  'edgeAiInitializeCorruptLabel': 'Nabigo ang pag-initialize. Kadalasan sira ang model file o hindi tugma sa runtime ng device na ito. Subukang i-reinstall, tapos i-initialize ulit.',
  'edgeAiInitializeFailedLabel': 'Nabigo ang pag-initialize: {0}',
  'edgeAiGenerationFailedLabel': 'Nabigo ang local generation: {0}',
  'edgeAiStatusUnavailable': 'hindi available',
  'edgeAiModelNotReadyTitle': 'Hindi pa handa ang local model',
  'edgeAiModelNotReadyMessage': 'Hindi pa handa ang local AI model. I-install at i-initialize bago simulan ang pretest.',
  'edgeAiOpenSettingsLabel': 'Buksan ang local AI settings',
  'edgeAiCheckingReadinessLabel': 'Sinusuri ang readiness ng local AI model...',
  'edgeAiPickTargetNodeLabel': 'Pumili ng target node sa Learning Goal bago simulan ang pretest.',
  'edgeAiFinishInstallLabel': 'Hindi pa handa ang local model. Tapusin ang install/initialize, tapos simulan ulit ang pretest.',
  'edgeAiModelMissingTitle': 'Hindi naka-install ang local AI model',
  'edgeAiModelMissingMessage': 'Mas stable ang Wicara kapag na-download na ang LiteRT model. Buksan ang local AI settings ngayon?',
  'edgeAiDownloadModelLabel': 'I-download ang modelo',
  'edgeAiModelNotInitializedTitle': 'Hindi pa handa ang local AI model',
  'edgeAiModelNotInitializedMessage': 'Nasa device na ang modelo pero hindi pa na-initialize. I-initialize na ba?',
  'edgeAiOpenSettingsShortLabel': 'Buksan ang settings',
  'edgeAiInitializingModelLabel': 'Ini-initialize ang local model...',
  'edgeAiModelReadyLabel': 'Handa nang gamitin ang local model.',
  'edgeAiInitializedNotReadyLabel': 'Tapos na ang initialize pero hindi pa handa ang runtime. Subukang buksan ang local AI settings.',
  'edgeAiTestPrompt': 'Sumagot sa Filipino. Ipaliwanag ang derivative bilang rate of change sa 2 pangungusap, tapos magbigay ng 1 tanong para sa comprehension check.',
  'edgeAiInitializeModelFailedLabel': 'Nabigo ang pag-initialize ng modelo: {0}',
  'tapToOpenLabel': 'I-tap para buksan',
  'resetZoomLabel': 'I-reset ang zoom',
  'videoFailedToLoadLabel': 'Nabigong mag-load ang video. Subukan ulit.',
  'videoUrlMissingLabel': 'Walang video URL para sa artifact na ito.',
  'videoLoadFailedLabel': 'Nabigong i-load ang video na ito.',
  'openFullscreenLabel': 'Buksan nang fullscreen',
  'videoPreviewWebOnlyLabel': 'Available ang video preview sa web demo build.',
  'penSizeLabel': 'Laki ng pen {0}',
  'penColorLabel': 'Kulay ng pen',
  'saveWorkLabel': 'I-save ang gawa',
  'sendToChatLabel': 'Ipadala sa chat',
  'canvasStatusLabel.draftEmpty': 'Walang laman ang draft',
  'canvasStatusLabel.unsavedSketch': 'Hindi pa naka-save na sketch',
  'canvasStatusLabel.unsavedChanges': 'Hindi pa naka-save na pagbabago',
  'canvasStatusLabel.sentToChat': 'Naipadala sa chat',
  'canvasStatusLabel.default': 'Naka-save, handang ipadala',
  'canvasClearTitle': 'Linisin ang canvas?',
  'canvasClearMessage': 'Aalisin nito ang kasalukuyang sketch at ang nakalakip na paper note.',
  'canvasLabel': 'Canvas',
  'canvasWorkspaceLabel': 'Canvas workspace',
  'canvasLargeHint': 'Gamitin ang mas malaking workspace para sa mga diagram at tala.',
  'canvasSmallHint': 'Idaan sa pangangatwiran bago magsumite.',
  'canvasClosePanelLabel': 'Isara ang panel',
  'canvasLargerPanelLabel': 'Mas malaking panel',
  'canvasResetViewLabel': 'I-reset ang view',
  'canvasHideGridLabel': 'Itago ang grid',
  'canvasShowGridLabel': 'Ipakita ang grid',
  'canvasClearLabel': 'Linisin ang canvas',
  'canvasUploadImageLabel': 'Mag-upload ng larawan',
  'canvasKeepLabel': 'Panatilihin',
  'canvasClearShortLabel': 'Linisin',
  'canvasViewSectionLabel': 'View',
  'canvasEditSectionLabel': 'I-edit',
  'canvasZoomOutLabel': 'Mag-zoom out',
  'canvasZoomInLabel': 'Mag-zoom in',
  'canvasPenLabel': 'Pen',
  'canvasPenTooltip': 'Pen mode',
  'canvasHandLabel': 'Kamay',
  'canvasHandTooltip': 'Hand mode',
  'canvasEraseLabel': 'Burahin',
  'canvasEraseTooltip': 'Eraser mode',
  'canvasShapeLabel': 'Hugis',
  'canvasShapeTooltip': 'Shape helper',
  'canvasLineShapeLabel': 'Hugis na linya',
  'canvasArrowShapeLabel': 'Hugis na arrow',
  'canvasRectangleShapeLabel': 'Hugis na rektanggulo',
  'canvasPaperAttachedLabel': 'Nakalakip ang\ngawa sa papel',
  'canvasEmptyHintLabel': 'Mag-sketch ng mga formula, diagram, o hakbang dito.',
  'preparingAdaptiveQuestionsLabel': 'Naghahanda ng adaptive na tanong...',
  'noLocalQuestionLabel': 'Walang tanong na ibinalik ang local pretest generator.',
  'chooseAnswerBeforeReasoningLabel': 'Pumili ng sagot bago idagdag ang iyong solusyon.',
  'imageUnreadableLabel': 'Hindi mabasa ang image file.',
  'imageTooLargeLabel': 'Dapat 10 MB pababa ang larawan.',
  'adaptiveProbingLabel': 'Adaptive probing  •  Knowledge Space Theory',
  'missingPrerequisiteSkillLabel': 'Kulang na prerequisite: causal drivers',
  'missingPrerequisiteMessageLabel': 'Mukhang pumipili ng tool ang gap bago pangalanan ang defect driver, ebidensya, at malamang na chain ng sanhi.',
  'improvedLabel': 'Bumuti',
  'stagnantLabel': 'Hindi umuusad',
  'reviewDueConceptsLabel': 'Balikan ang mga due na konsepto',
  'dueThisWeekLabel': 'Due ngayong linggo',
  'preVsPostTestLabel': 'Pre-test vs Post-test',
  'weeklyNarrativeLabel': 'Lingguhang salaysay',
  'focusLabel': 'Pokus',
  'answerScoredByAiLabel': 'Ang sagot ay iniskor ng AI.',
  'scoringOffLabel': 'Mali ang scoring?',
  'laterLabel': 'Mamaya',
  'trackWithoutModuleLabel': 'Nagawa ang track, pero wala pang available na workspace module.',
  'workspaceAutoOpenFailedLabel': 'Hindi ma-auto-open ang workspace pagkatapos ng pretest.',
  'retentionLiftShortLabel': 'Retention Lift',
  'remainingLabel': 'Natitira',
  'weeklyReportLabel': 'Lingguhang Ulat',
  'retentionLabel': 'Retention',
  'posttestMasteryCheckLabel': 'Posttest Mastery Check',
  'noSubjectsSelectedLabel': 'Walang napiling asignatura',
  'thisWeekLabel': 'Ngayong linggo',
  'consistencyCompoundingLabel': 'Nagkukumpol ang iyong konsistensi.',
  'serverTimeoutLabel': 'Masyadong natagalan ang WICARA server. Pakisubukan ulit.',
  'uploadTimeoutLabel': 'Masyadong natagalan ang WICARA server sa pag-upload ng larawan. Pakisubukan ulit.',
  'serverUnreachableLabel': 'Hindi maabot ang WICARA server sa {0}. {1}',
  'loginBeforeDashboardLabel': 'Mag-log in muna bago buksan ang dashboard.',
  'loginBeforeOnboardingLabel': 'Mag-log in muna bago mag-onboarding.',
  'loginBeforeWorkspaceLabel': 'Mag-log in muna bago buksan ang workspace.',
  'loginBeforeTrackLabel': 'Mag-log in muna bago gumawa ng track.',
  'noMatchingGoalLabel': 'Walang nahanap na tugmang learning goal.',
  'noImageAssetIdLabel': 'Walang ibinalik na image asset id ang server.',
  'activeGoalConflictLabel': 'May aktibo ka nang layunin para sa "{0}". ',
  'signInFailedLabel': 'Nabigo ang pag-sign in: {0}',
  'registrationFailedLabel': 'Nabigo ang pagpaparehistro: {0}',
  'googleSignInFailedLabel': 'Nabigo ang Google sign-in: {0}',
  'googleSignInCancelledLabel': 'Kinansela ang Google sign-in.',
  'createGoalBeforePretestLabel': 'Gumawa ng learning goal bago buksan ang pretest.',
  'invalidPretestQuestionLabel': 'Nagbalik ang backend ng invalid na pretest question.',
  'chooseAnswerFirstLabel': 'Pumili ng sagot bago magpatuloy.',
  'noNextQuestionLabel': 'Walang ibinalik ang backend na susunod na tanong o diagnosis.',
  'invalidEvidenceImageLabel': 'Nagbalik ang backend ng invalid na evidence image.',
  'createGoalBeforePathLabel': 'Gumawa ng learning goal bago pumili ng path.',
  'loginBeforePretestLabel': 'Mag-log in muna bago kumuha ng pretest.',
  'openPretestBeforeSubmitLabel': 'Buksan ang nabuong pretest bago magsumite.',
  'pathSelectedLabel': 'Napiling path',
  'adaptivePathReadyLabel': 'Handa na ang iyong adaptive learning path.',
  'continueSelectedPathLabel': 'Ituloy ang napiling path.',
  'modulesCountLabel': '{0} module',
  'adaptiveDiagnosisLabel': 'Adaptive diagnosis',
  'adaptivePretestCompleteLabel': 'Tapos na ang adaptive pretest',
  'scoreMetaLabel': 'Iskor {0}%',
  'correctCountMetaLabel': '{0}/{1} tama',
  'pathDescriptionLabel.review_only': 'Magsimula sa maikling review at advanced na pagsasanay.',
  'pathDescriptionLabel.target_reinforcement': 'Magsanay sa target na konsepto sa medium at hard na antas.',
  'pathDescriptionLabel.target_intro': 'Magsimula sa introduksyon ng target na konsepto.',
  'pathDescriptionLabel.repair_prerequisites': 'Ayusin ang prerequisite gaps bago bumalik sa target.',
  'pathDescriptionLabel.full_foundation_path': 'Muling itayo muna ang mas malalim na pundasyon.',
  'pathDescriptionLabel.default': 'Aralin ang target na konsepto mula sa basics.',
  'questionProgressLabel': 'Tanong {0} sa {1}',
  'conceptNotFoundLabel': 'Hindi nahanap ang konsepto sa local curriculum.',
  'conceptCodeNotFoundLabel': 'Hindi nahanap ang konseptong "{0}" sa local curriculum.',
  'evidenceUploadNeedsBackendLabel': 'Kailangan ng backend pretest mode ang pag-upload ng image evidence.',
  'emptyPathOptionLabel': 'Hindi puwedeng blangko ang path option.',
  'localDiagnosisUnavailableLabel': 'Wala pang local diagnosis. Tapusin muna ang pretest.',
  'localPretestStateInvalidLabel': 'Hindi valid ang local pretest state.',
  'localPretestSessionInvalidLabel': 'Hindi valid ang local pretest session.',
  'questionMismatchLabel': 'Hindi tugma ang tanong. I-reload ang pretest at subukan ulit.',
  'optionNotFoundLabel': 'Hindi nahanap ang napiling opsyon para sa tanong na ito.',
  'offlineCurriculumMissingLabel': 'Walang offline curriculum sa device na ito.',
  'targetConceptNotChosenLabel': 'Walang napiling target na konsepto. Buksan ang Learning Goal at pumili muna ng target node.',
  'targetConceptNotFoundLabel': 'Hindi nahanap ang target na konseptong "{0}" sa local curriculum.',
  'backendPretestNotConfiguredLabel': 'Hindi naka-configure ang backend pretest repository.',
  'chooseBestAnswerLabel': 'Piliin ang pinakamahusay na sagot para sa {0}.',
  'reviewWorkingStepsLabel': 'Balikan ang iyong mga hakbang para kumpirmahin ang piniling sagot.',
  'emptyTopicLabel': 'Hindi puwedeng blangko ang learning topic.',
  'noMatchingConceptLabel': 'Wala pang tugmang konsepto. Subukang magdagdag ng mas tiyak na keyword.',
  'searchAllSubjectsLabel': 'Hinanap sa lahat ng local na asignatura.',
  'searchLimitedSubjectLabel': 'Limitado ang paghahanap sa napiling asignatura.',
  'resolutionNotFoundLabel': 'Hindi nahanap ang resolution. Maghanap ulit ng goal node.',
  'resolutionMissingLabel': 'Hindi nahanap ang resolution.',
  'noTargetNodeLabel': 'Walang napiling target node para sa pretest.',
  'noMatchingConceptRetryLabel': 'Walang nahanap na tugmang konsepto. Subukan ang ibang query.',
  'localCurriculumMissingLabel': 'Wala pang local curriculum. I-sync muna ang kurikulum.',
  'localNodeNotFoundLabel': 'Hindi nahanap ang node na "{0}" sa local curriculum.',
  'targetConceptFallbackTitle': 'Target na konsepto',
  'tutorHintDerivativeLabel': 'Pahiwatig: tingnan kung paano nagbabago ang value ng function kapag bahagyang gumalaw ang x, tapos ikumpara ang dalawang napakalapit na punto.',
  'tutorHintGenericLabel': 'Pahiwatig: hatiin ang problema sa tatlong maliliit na hakbang, suriin ang assumption sa bawat hakbang, tapos gawin isa-isa.',
  'tutorEvaluateCloseLabel': 'Malapit na ang mga hakbang mo. Ngayon ipaliwanag kung bakit angkop ang rule na iyon sa anyo ng problemang ito.',
  'tutorEvaluateInconsistentLabel': 'Hindi pa consistent ang sagot mo. Suriin ulit ang unang hakbang, tapos isulat muli ang dahilan sa bawat transformation.',
  'reasoningTooShortLabel': 'Masyado pang maikli ang pangangatwiran mo; idagdag kung bakit mo pinili ang operasyong iyon.',
  'reasoningClearLabel': 'Malinaw ang istruktura ng pangangatwiran mo; suportahan mo ngayon ng isang maikling numeric na halimbawa.',
  'quizPromptLabel': "Subukan ito: kung f(x)=x^2, ano ang derivative na f'(x), at bakit?",
  'summaryFallbackLabel': 'Sa madaling salita: pokus sa pangunahing konsepto, isang pangunahing rule, at isang karaniwang pagkakamaling dapat iwasan.',
  'explainDerivativeLabel': 'Inilalarawan ng derivative kung gaano kabilis nagbabago ang value ng function kaugnay ng x. Isipin mo itong slope ng tangent line sa isang punto ng curve.',
  'explainGenericLabel': 'Magsisimula tayo sa pangunahing depinisyon, saka isang maikling halimbawa, tapos babalikan natin sa pamamagitan ng verification question.',
  'heuristicReasoningFeedback': 'Iniskor ang pangangatwiran gamit ang local heuristic dahil hindi available ang LiteRT evaluation.',
  'carelessMistakeFeedback': 'Mali ang multiple choice, pero may medyo malakas na senyales ng bahagyang pangangatwiran.',
  'partialReasoningFeedback': 'Bahagyang pangangatwiran, pero hindi pa sapat para suportahan ang sagot.',
  'unrelatedReasoningFeedback': 'Hindi pa direktang kaugnay ng pangunahing konsepto ang pangangatwiran.',
  'diagnosisSummaryLabel.review_only': 'Handa ka na sa {0}; sapat na ang maikling review.',
  'diagnosisSummaryLabel.target_reinforcement': 'Naiintindihan mo ang basics ng {0}, pero kailangan mo ng mas mahirap na pagsasanay.',
  'diagnosisSummaryLabel.target_from_basics': 'Nabubuo na ang {0}, pero hindi pa matatag sa medium na antas.',
  'diagnosisSummaryLabel.target_intro': 'Ang {0} pa rin ang pangunahing gap; magsimula sa introduksyon ng konsepto.',
  'diagnosisSummaryLabel.repair_prerequisites': 'May ilang prerequisite para sa {0} na kailangan munang patatagin.',
  'diagnosisSummaryLabel.full_foundation_path': 'Kailangang muling itayo ang pundasyon bago ang {0}, simula sa pinakamalalim na prerequisite.',
  'diagnosisSummaryLabel.default': 'Kumpleto na ang diagnosis para sa {0}.',
  'diagnosisFocusLabels.review_only.0': 'Ibuod muli ang target na konsepto',
  'diagnosisFocusLabels.review_only.1': 'Gumawa ng 1-2 magaan na reinforcement na tanong',
  'diagnosisFocusLabels.target_reinforcement.0': 'Magsanay ng medium hanggang hard sa target',
  'diagnosisFocusLabels.target_reinforcement.1': 'Pagbutihin ang kalidad ng nakasulat na pangangatwiran',
  'diagnosisFocusLabels.target_from_basics.0': 'Ulitin ang pundasyon bago mismo ang target',
  'diagnosisFocusLabels.target_from_basics.1': 'Magsanay nang paunti-unti mula madali hanggang medium',
  'diagnosisFocusLabels.target_intro.0': 'Magsimula sa introduksyon ng target na konsepto',
  'diagnosisFocusLabels.target_intro.1': 'Gumamit ng konkretong halimbawa bago ang simboliko',
  'diagnosisFocusLabels.repair_prerequisites.0': 'Patatagin ang marupok o kulang na prerequisite node',
  'diagnosisFocusLabels.repair_prerequisites.1': 'Bumalik sa target kapag matatag na ang prerequisites',
  'diagnosisFocusLabels.full_foundation_path.0': 'Muling itayo mula sa pinakamalalim na prerequisite',
  'diagnosisFocusLabels.full_foundation_path.1': 'Umakyat nang paunti-unti ayon sa lalim ng graph',
  'offlineWritingNotesLabel': 'Sinusulat ng AI ang iyong personal na notes...',
  'offlineSessionNotFoundLabel': 'Hindi nahanap ang pretest session.',
  'offlineInvalidStateLabel': 'Hindi valid ang pretest state.',
  'offlineNotesReadyLabel': 'Handa na ang personal mong AI notes.',
  'offlineNotesFailedLabel': 'Hindi nakapagsulat ang AI ng personal na notes para sa session na ito.',
  'offlineRuntimeNotReadyLabel': 'Hindi pa handa o hindi naka-install ang LiteRT model. Ginagamit ang local fallback.',
  'offlineGeneratingAttemptLabel': 'Bumubuo ng local na tanong (subok {0}/{1}, timeout {2}s)...',
  'offlineOutputInvalidLabel': 'Hindi pa valid ang output ng modelo, sinusubukan ulit ({0}/{1}).',
  'offlineValidLevelsLabel': 'Nakabuo ang modelo ng {0} valid na antas ({1}).',
  'offlineAttemptTimeoutLabel': 'Nag-timeout ang subok {0} ({1}s). Sinusubukan ulit...',
  'offlineAttemptFailedLabel': 'Nabigo ang subok {0}: {1}. Magpapatuloy sa susunod na retry.',
  'offlineGenerationDoneLabel': 'Tapos na ang pagbuo ng tanong.',
  'offlineGenerationPartialLabel': 'May ilang valid na tanong. Nilaktawan: {0}.',
  'offlineGenerationFailedLabel': 'Nabigo ang pagbuo ng tanong. Ginagamit ang fallback template.',
  'offlineGenerationFallbackLabel': 'Nabigo ang local na pagbuo ng tanong. Ginagamit ang fallback template.',
  'offlinePreparingModelLabel': 'Inihahanda ang local model...',
  'devModeLabel': 'Dev Mode',
  'devBypassTitle': 'Developer Bypass',
  'devBypassSubtitle': 'Laktawan ang totoong authentication sa debug builds.',
  'devOnboardingIncompleteLabel': 'Naka-sign in na, pero hindi pa tapos ang onboarding.',
  'startAtOnboardingLabel': 'Magsimula sa onboarding',
  'jumpToHomeLabel': 'Dumiretso sa home',
  'devSignedInLabel': 'Naka-sign in at namarkahang tapos na ang onboarding.',
  'demoLimitsFromGraphsTitle': 'Limits mula sa graph',
  'demoLimitsFromGraphsReason': 'Bakit ngayon? Bubuksan nito ang continuity at\nintuwisyon sa first derivative.',
  'demoDerivativeRulesTitle': 'Mga rule ng derivative',
  'demoFunctionCompositionTitle': 'Review sa function composition',
  'demoContinueCalculusTitle': 'Ipagpatuloy ang Calculus I',
  'demoContinueCalculusSubtitle': 'Limits, derivatives, aplikasyon',
  'demoLinearAlgebraTitle': 'Linear Algebra',
  'demoLinearAlgebraSubtitle': 'Vectors, matrices, transformations',
  'demoDiscreteMathTitle': 'Discrete Math',
  'demoDiscreteMathSubtitle': 'Logic, sets, graphs, counting',
  'demoDerivativesIntuitionTitle': 'Intuwisyon sa derivatives',
  'demoDerivativesIntuitionSubtitle': 'Ano ang sinasabi sa atin ng derivative?',
  'demoLimitsFromGraphsSubtitle': 'Papalapit sa isang value nang hindi ito nadadampian',
  'demoCalculusOneLabel': 'Calculus I',
  'demoCalculusLabel': 'Calculus',
  'demoDerivativeRulesReason': 'Bakit ngayon? Handa ka na pagkatapos ng limits at\npag-unawa sa slope.',
  'demoFunctionCompositionReason': 'Bakit ngayon? Kailangan bago ang chain rule at\nimplicit differentiation.',
  'demoLessonMetaLabel': '{0} min   •   {1}',
  'reviewNowShortLabel': 'Balikan',
  'demoCurrentTrackMeta': 'Kasalukuyang track   •   {0}% tapos',
  'demoCreatedTrackMeta': 'Nagawang track   •   {0}% tapos',
  'demoCreatedTrackReadyMeta': 'Nagawang track   •   handang ipagpatuloy',
  'gradeValue': 'Baitang {0}',
  'subjectLabel.Math': 'Matematika',
  'subjectLabel.Matematika': 'Matematika',
  'subjectLabel.Physics': 'Pisika',
  'subjectLabel.Fisika': 'Pisika',
  'subjectLabel.Chemistry': 'Kimika',
  'subjectLabel.Kimia': 'Kimika',
  'subjectLabel.Biology': 'Biyolohiya',
  'subjectLabel.Biologi': 'Biyolohiya',
  'subjectLabel.Science': 'Agham',
  'subjectLabel.IPA': 'Agham',
  'subjectLabel.IPAS': 'Agham',
  'subjectDescription.Math': 'Algebra, Geometry, Calculus',
  'subjectDescription.Physics': 'Mekaniks, Alon, Thermo',
  'subjectDescription.Chemistry': 'Stoichiometry, Mga reaksyon',
  'subjectDescription.Biology': 'Selula, Genetics, Ekolohiya',
  'difficultyLabel.easy': 'Madali',
  'difficultyLabel.medium': 'Katamtaman',
  'difficultyLabel.hard': 'Mahirap',
  'estimatedDurationLabel': 'Tinatayang {0}   •   {1}',
  'layerLabel': 'Layer {0}',
  'nodeStatusLabel.MASTERED': 'NA-MASTER',
  'nodeStatusLabel.REVIEW': 'BALIKAN',
  'nodeStatusLabel.READY': 'HANDA',
  'nodeStatusLabel.GAP': 'GAP',
  'nodeStatusLabel.LOCKED': 'NAKA-LOCK',
  'weekShortLabels': 'L|L|M|M|H|B|S',
  'diagnosisPromptInstructions': '\nWrite a diagnosis of the learner\'s pretest in Filipino. Not a summary, not encouragement - a DIAGNOSIS.\nEvery field of the JSON output must be written in Filipino.\nUse ONLY the data in "nodes" below.\nTone: casual, addressed directly to the learner ("You ..."), no jargon.\nIf siswa_pakai_canvas=true, mention that the learner wrote or sketched while working (an effort signal).\n\nRules for each field:\n- "summary" (2-3 sentences, roughly 80-120 words):\n  name the specific target concept + 1 thing already understood (cite a correct question) + 1 thing still missing (cite a wrong question).\n  Avoid motivational lines.\n- "strengths" (1-3 points, each 1-2 full sentences):\n  format: "On the question about [core of the question], you [correct step]."\n  Cite reasoning_siswa whenever it is available.\n- "gaps" (1-3 points, each 2-3 full sentences):\n  format: "On the question about [core of the question], you chose [siswa_pilih] when the answer was [jawaban_benar]. [Contrast reasoning_siswa with expected_reasoning or explain the error]."\n- "evidence_notes" (0-2 points):\n  describe concrete cross-question patterns (e.g. empty reasoning on hard questions, canvas effort appearing, etc).\n- "recommended_focus" (1-3 points):\n  concrete practice that directly fixes the gap (name the sub-topic, not "practice more").\n\nFORBIDDEN: generic lines ("needs more practice", "the concept is weak").\nAlways reference the actual question content from the data.',
  'offlineQuestionPromptInstructions': '\nWrite short adaptive pretest questions in Filipino.\nEvery question, option, and explanation must be written in Filipino.\nOnly output these difficulty keys: {0}.\nEvery question must have 4 unique options and exactly 1 correct answer.\nAvoid long explanations. Keep it concise.\nThe "explanation" field MUST be concrete numbered steps (e.g. "1) ... 2) ... 3) ..."),\nnot a general definition of the concept.',
  'diagnosisSystemPrompt': "You are WICARA's on-device pretest diagnostic writer. Write a specific narrative in Filipino, grounded in the given questions and the learner's answers, not generalities. Output valid JSON only.",
  'knowledgeGraph.Mathematics Prerequisite Map': 'Mapa ng Prerequisite sa Matematika',
  'knowledgeGraph.Knowledge Map': 'Mapa ng Kaalaman',
  'knowledgeGraph.Primary Math': 'Matematika sa Elementarya',
  'knowledgeGraph.Lower Secondary': 'Junior High School',
  'knowledgeGraph.Algebra and Functions': 'Algebra at Mga Function',
  'knowledgeGraph.Precalculus': 'Precalculus',
  'knowledgeGraph.Limits and Continuity': 'Limits at Continuity',
  'knowledgeGraph.Calculus 1': 'Calculus 1',
  'knowledgeGraph.Calculus 2': 'Calculus 2',
  'knowledgeGraph.Calculus 3': 'Calculus 3',
  'knowledgeGraph.Counting': 'Pagbilang',
  'knowledgeGraph.Place Value': 'Place Value',
  'knowledgeGraph.Arithmetic Operations': 'Mga Operasyong Aritmetiko',
  'knowledgeGraph.Fractions and Decimals': 'Mga Praksyon at Desimal',
  'knowledgeGraph.Basic Shapes and Measurement': 'Batayang Hugis at Pagsukat',
  'knowledgeGraph.Tables, Charts, and Mean': 'Talahanayan, Tsart, at Mean',
  'knowledgeGraph.Integers and Rational Numbers': 'Integers at Rational Numbers',
  'knowledgeGraph.Exponents and Roots Basics': 'Batayan ng Exponents at Roots',
  'knowledgeGraph.Linear Equations': 'Linear na Ekwasyon',
  'knowledgeGraph.Coordinate Graphing': 'Pag-graph sa Coordinate',
  'knowledgeGraph.Slope and Intercepts': 'Slope at Intercepts',
  'knowledgeGraph.Pythagorean Theorem': 'Teorama ng Pythagoras',
  'knowledgeGraph.Functions, Domain, and Range': 'Function, Domain, at Range',
  'knowledgeGraph.Function Composition and Inverses': 'Function Composition at Inverses',
  'knowledgeGraph.Exponential and Logarithmic Functions': 'Exponential at Logarithmic na Function',
  'knowledgeGraph.Quadratic and Polynomial Functions': 'Quadratic at Polynomial na Function',
  'knowledgeGraph.Rational Functions': 'Rational na Function',
  'knowledgeGraph.Sequences, Series, Sigma Notation': 'Sequences, Series, Sigma Notation',
  'knowledgeGraph.Analytic Geometry and Conics': 'Analytic Geometry at Conics',
  'knowledgeGraph.Trigonometric Functions and Graphs': 'Trigonometric na Function at Graph',
  'knowledgeGraph.Trigonometric Identities and Equations': 'Trigonometric Identities at Equations',
  'knowledgeGraph.Vectors, Parametric, and Polar Basics': 'Batayan ng Vectors, Parametric, at Polar',
  'knowledgeGraph.Precalculus Fluency': 'Kahusayan sa Precalculus',
  'knowledgeGraph.Intuitive Limits': 'Intuwitibong Limits',
  'knowledgeGraph.Limit Laws and Algebraic Techniques': 'Limit Laws at Algebraic na Teknik',
  'knowledgeGraph.Trigonometric Limits and Squeeze Theorem': 'Trigonometric Limits at Squeeze Theorem',
  'knowledgeGraph.Continuity and Intermediate Value Theorem': 'Continuity at Intermediate Value Theorem',
  'knowledgeGraph.Derivative Definition': 'Depinisyon ng Derivative',
  'knowledgeGraph.Derivative Rules': 'Mga Rule ng Derivative',
  'knowledgeGraph.Chain Rule and Implicit Differentiation': 'Chain Rule at Implicit Differentiation',
  'knowledgeGraph.Related Rates, Optimization, Curve Sketching': 'Related Rates, Optimization, Curve Sketching',
  'knowledgeGraph.Antiderivatives, Riemann Sums, Definite Integrals': 'Antiderivatives, Riemann Sums, Definite Integrals',
  'knowledgeGraph.Fundamental Theorem of Calculus': 'Pundamental na Teorama ng Calculus',
  'knowledgeGraph.Integration Techniques': 'Mga Teknik sa Integration',
  'knowledgeGraph.Area, Volume, Work, Fluid Force': 'Area, Volume, Work, Fluid Force',
  'knowledgeGraph.Convergence Tests and Power Series': 'Convergence Tests at Power Series',
  'knowledgeGraph.Parametric and Polar Calculus': 'Parametric at Polar na Calculus',
  'knowledgeGraph.3D Coordinates and Vector Operations': '3D Coordinates at Vector Operations',
  'knowledgeGraph.Partial Derivatives and Gradients': 'Partial Derivatives at Gradients',
  'knowledgeGraph.Double and Triple Integrals': 'Double at Triple Integrals',
  'knowledgeGraph.Vector Fields, Line Integrals, Green, Stokes, Divergence': 'Vector Fields, Line Integrals, Green, Stokes, Divergence',
  'workspace.topicTitle': 'Paksa sa pag-aaral',
  'workspace.startChatTitle': 'Simulan ang pag-aaral',
  'workspace.startChatBody': 'Gagabayan ka ng tutor mula sa diagnosis at learning phase na nakatago sa backend.',
  'workspace.startChatButtonLabel': 'Simulan ang learning chat',
  'workspace.loadingDescription': 'Ikinokonekta ang module na ito sa backend learning context.',
  'workspace.syncedDescription': 'Naka-sync sa backend ang usapan, canvas, media, at phase state.',
  'workspace.workspaceTitleLabel': 'Workspace',
  'workspace.newChatLabel': 'Bagong chat',
  'workspace.chatHistoryTitle': 'Kasaysayan ng chat',
  'workspace.advancePhaseLabel': 'Susunod na phase',
  'workspace.advancingPhaseLabel': 'Nagpapatuloy sa susunod na phase...',
  'workspace.phaseTransitionHint': 'Tapos na ang phase na ito. Manatili rito hanggang handa ka na.',
  'workspace.phaseCheckpointPrompt': 'Batay sa sagot mong “{0}” tungkol sa {1}, tugma ba ito sa pagkaunawa mo ngayon?',
  'workspace.confirmPhaseLabel': 'Oo, magpatuloy',
  'workspace.stayInPhaseLabel': 'Hindi pa',
  'workspace.stayInPhaseMessage': 'Hindi pa, kailangan ko pa ng tulong sa bahaging ito.',
  'workspace.startPosttestButtonLabel': 'Simulan ang Posttest',
  'workspace.posttestReadyBody': 'Simulan ang posttest ngayon? Kukumpletuhin nito ang workspace module at ihahanda ang posttest session.',
  'workspace.cancelLabel': 'Kanselahin',
  'workspace.startPosttestDialogLabel': 'Simulan ang posttest',
  'workspace.posttestUnavailableMessage': 'Hindi pa handa ang posttest. Magpatuloy ayon sa gabay ng tutor.',
  'workspace.posttestGeneratingButtonLabel': 'Inihahanda ang posttest...',
  'workspace.posttestGenerationDelayedMessage': 'Ginagawa pa ang posttest. Maaari kang umalis at ipagpatuloy ang workspace na ito mamaya.',
  'workspace.workspaceNotReadyMessage': 'Hindi pa handa ang workspace.',
  'workspace.openTrackModuleMessage': 'Buksan ang track module mula sa Home o Queue bago gamitin ang workspace.',
  'workspace.chatLoadingMessage': 'Naglo-load pa ang chat session.',
  'workspace.connectingWorkspaceMessage': 'Kumokonekta sa backend workspace...',
  'workspace.savingEvidenceMessage': 'Sine-save ang workspace evidence...',
  'workspace.queueingVideoMessage': 'Ipinipila ang video generation...',
  'workspace.videoQueuedMessage': 'Nasa queue na ang video. Hinihintay ang worker...',
  'workspace.videoTimedOutMessage': 'Nag-timeout ang video generation matapos ang {0} minuto.',
  'workspace.generationTimeoutMessage': 'Nag-timeout ang generation.',
  'workspace.buildingScenesMessage': 'Binubuo ang mga eksena, narration, at rendering...',
  'workspace.generatingVideoTitle': 'Bumubuo ng video',
  'workspace.generatedVideoFallbackTitle': 'Nabuong video',
  'workspace.savedGeneratedVideoTitle': 'Naka-save na video',
  'workspace.generatedVideoSubtitle': 'Tapos na ang video rendering at nasa workspace mo na.',
  'workspace.aiVideoChip': 'AI video',
  'workspace.readyUrlChip': 'Handa ang URL',
  'workspace.playGeneratedVideoLabel': 'I-play ang video',
  'workspace.videoUrlUnavailableLabel': 'Hindi available ang video URL',
  'workspace.videoGenerationFailedTitle': 'Nabigo ang video generation',
  'workspace.videoGenerationFailedMessage': 'Nabigo ang video generation.',
  'workspace.visualOnlyExploreMessage': 'Sa Explore lamang maaaring gumawa ng visualization.',
  'workspace.visualSuggestionLabel': 'Biswal na suporta',
  'workspace.acceptVisualSuggestionLabel': 'Gumawa ng visualization',
  'workspace.retryGenerateVideoLabel': 'Subukang bumuo ulit ng video',
  'workspace.generatingVideoButtonLabel': 'Bumubuo ng video...',
  'workspace.generateVideoFromChatLabel': 'Bumuo ng video mula sa chat na ito',
  'workspace.generatingVideoContextMessage': 'Bumubuo ng video mula sa pinakabagong konteksto ng usapan mo...',
  'workspace.videoReadyMessage': 'Handa na ang video. Puwede mo itong i-play mula sa pinakabagong chat card.',
  'workspace.failedToLoadVideoMessage': 'Nabigong i-load ang video mula sa backend URL.',
  'workspace.openFullscreenTooltip': 'Buksan nang fullscreen',
  'workspace.durationChipLabel': 'Tagal {0}',
  'workspace.canvasAttachedPrompt': 'Nakalakip na ang canvas work. Magdagdag ng ibang sketch kung kailangan.',
  'workspace.canvasPrompt': 'Kailangan ng whiteboard? Buksan ang canvas at ipadala ang sketch mo rito.',
  'workspace.openCanvasLabel': 'Buksan ang canvas',
  'workspace.useCanvasLabel': 'Gamitin ang canvas',
  'workspace.canvasSentLabel': 'Naipadala ang canvas',
  'workspace.explanationCardLabel': 'Explanation card',
  'workspace.evidenceRequestLabel': 'Hinihinging ebidensya',
  'workspace.nextActionsLabel': 'Susunod na hakbang',
  'workspace.canvasSnapshotSentLabel': 'Naipadala ang canvas snapshot',
  'workspace.canvasSnapshotSentCountLabel': 'Naipadala ang canvas snapshot ({0} marka)',
  'workspace.canvasMarksLabel': '{0} marka',
  'workspace.canvasMarksAttachedLabel': '{0} marka - may nakalakip na papel',
  'workspace.historyButtonLabel': 'Kasaysayan ({0})',
  'workspace.historyMessageCountLabel': '{0} mensahe',
  'workspace.workspaceSyncFailedMessage': 'Nabigo ang workspace sync: {0}',
  'workspace.imageSentLabel': 'Naipadala ang larawan',
  'workspace.videoRequestedNote': 'May hiniling na video dito.',
  'workspace.canvasUploadFailedMessage': 'Nabigo ang pag-upload ng canvas image, teksto lang ang natanggap ng tutor: {0}',
  'workspace.resumingVideoMessage': 'Muling kumakabit sa kasalukuyang render...',
  'workspace.resumeVideoLabel': 'Ikabit muli',
  'workspace.tutorOfflineTitle': 'Hindi available ang AI tutor',
  'workspace.tutorOfflineBody': 'Fallback text ang ginagamit ng mga sagot sa ibaba, kaya hindi uusad ang phase mo hanggang bumalik ang tutor. Subukan ulit mamaya.',
  'workspace.feedbackCorrectLabel': 'Tama',
  'workspace.feedbackPartialLabel': 'Malapit na',
  'workspace.feedbackIncorrectLabel': 'Hindi pa tama',
  'workspace.misconceptionLabel': 'May natukoy na misconception',
  'workspace.masteryDeltaUpLabel': 'Mastery +{0}%',
  'workspace.masteryDeltaDownLabel': 'Mastery -{0}%',
  'workspace.masteryDeltaFlatLabel': 'Walang pagbabago ang mastery',
  'workspace.hintLevelLabel': 'Antas ng hint {0}',
  'workspace.whyThisModuleLabel': 'Bakit ang module na ito?',
  'workspace.deleteSessionLabel': 'Burahin ang session',
  'workspace.deleteSessionConfirmBody': 'Permanenteng buburahin ang chat session na ito. Magpatuloy?',
  'loadingPosttestLabel': 'Nilo-load ang Posttest',
  'preparingAdaptivePosttestFromBackendLabel': 'Inihahanda ang adaptive posttest mula sa backend.',
  'posttestUnavailableLabel': 'Hindi available ang posttest',
  'backendReturnedNoPosttestQuestionsLabel': 'Walang ibinalik na posttest question ang backend.',
  'tryAgainLabel2': 'Subukan ulit',
  'questionsMediumHardBasedWhatLabel': '10 tanong: 3 medium at 7 hard batay sa natutuhan mo.',
  'continueLabel2': 'Magpatuloy',
  'finishPosttestLabel': 'Tapusin ang posttest',
  'loadingDailyEvalsLabel': 'Nilo-load ang Daily Evals',
  'fetchingSpacedReviewQuestionsFromLabel': 'Kinukuha ang spaced-review questions mula sa backend.',
  'dailyEvalsUnavailableLabel': 'Hindi available ang Daily Evals',
  'backendReturnedNoReviewQuestionsLabel': 'Walang ibinalik na review question ang backend.',
  'dashboardUnavailableLabel': 'Hindi available ang dashboard',
  'retryLabel2': 'Ulitin',
  'loadingDashboardLabel': 'Nilo-load ang dashboard',
  'fetchingProfileFromBackendLabel': 'Kinukuha ang profile mo mula sa backend.',
  'elementarySchoolLabel': 'Elementarya',
  'juniorHighSchoolLabel': 'Junior high school',
  'seniorHighSchoolLabel': 'Senior high school',
  'universityLabel': 'Unibersidad',
  'pretestProgressLabel': 'Nasa proseso ang pretest',
  'submittedAnswersSavedContinueFromLabel': 'Naka-save ang mga isinumite mong sagot. Magpatuloy mula sa pinakabago mong tanong.',
  'continuePretestLabel': 'Ipagpatuloy ang pretest',
  'createLearningGoalLabel': 'Gumawa ng learning goal',
  'createLearningGoalSoWicaraLabel': 'Gumawa ng learning goal para makapaghanda ang WICARA ng track at workspace.',
  'pickGoalSubjectBeforeOpeningLabel': 'Pumili ng layunin sa asignaturang ito bago buksan ang workspace.',
  'nextModuleLabel': 'Susunod na module',
  'progressLabel2': 'Nasa proseso',
  'readyLabel': 'Handa',
  'completedLabel': 'Nakumpleto',
  'pausedLabel': 'Naka-pause',
  'needsReviewLabel2': 'Kailangang balikan',
  'activeLabel': 'Aktibo',
  'noModuleReadyYetLabel': 'Wala pang handang module',
  'goalDoesNotHaveActiveLabel': 'Wala pang aktibong module ang layuning ito.',
  'createChooseAnotherGoalStartLabel': 'Gumawa o pumili ng ibang layunin para magsimulang matuto.',
  'noGeneratedVideosReadyYetLabel': 'Wala pang handang nabuong video.',
  'videosFromBackendJobsSavedLabel': 'Dito nase-save ang mga video mula sa backend jobs.',
  'bundledTemplatePackLabel': 'Template pack · nakalagay na sa app',
  'noDailyEvaluationAssignedYetLabel': 'Wala pang naka-assign na daily evaluation.',
  'noEvaluationLabel': 'Walang pagsusuri',
  'answerConfidenceLevelLabel': 'Antas ng kumpiyansa sa sagot',
  'howConfidentAnswerLabel': 'Gaano ka kakumpiyansa sa sagot mo?',
  'chooseNotConfidentVeryConfidentLabel': 'Pumili ng 0 (hindi kumpiyansa) hanggang 10 (sobrang kumpiyansa).',
  'masteryConfirmedLabel': 'Nakumpirma ang mastery',
  'reviewNeededFromPosttestResultsLabel': 'Kailangan ng review batay sa resulta ng posttest',
  'posttestResultsLabel': 'Resulta ng Posttest',
  'scoreSummaryLearningProgressionDecisionLabel': 'Galing sa backend ang buod ng iskor at desisyon sa learning progression.',
  'correctnessLabel': 'Katumpakan',
  'correctLabel2': 'Tama',
  'decisionLabel': 'Desisyon',
  'trackProgressLabel': 'Progreso ng track',
  'continueLearningLabel2': 'Magpatuloy sa pag-aaral',
  'reviewWeakAreasLabel': 'Balikan ang mahihinang bahagi',
  'moduleCompleteNextModuleNowLabel': 'Kumpleto na ang module na ito at available na ang susunod.',
  'learningGoalCompleteLabel': 'Kumpleto na ang learning goal na ito.',
  'backendConfirmedModuleAsPassedLabel': 'Kinumpirma ng backend na pasado ang module na ito. I-refresh ang Home para makita ang susunod na track step.',
  'backendRequiresReviewRemainingWeakLabel': 'Hinihingi ng backend na balikan ang natitirang mahihinang bahagi bago muling subukan.',
  'conceptResultsLabel': 'Resulta bawat konsepto',
  'noPosttestNodesHaveBeenLabel': 'Wala pang nasusuring posttest node.',
  'scoreLabel2': 'Iskor',
  'profileUpdatedLabel': 'Na-update ang profile.',
  'localAiLitertLmLabel': 'Local AI (LiteRT-LM)',
  'installInitializeModelLabel': 'I-install at i-initialize ang modelo',
  'reportUnavailableLabel': 'Hindi available ang ulat',
  'openDetailsLabel': 'Buksan ang detalye',
  'loadingWeekLabel': 'Nilo-load ang linggong ito',
  'syncingLabel': 'Nagsi-sync',
  'fetchingReportDataFromBackendLabel': 'Kinukuha ang report data mula sa backend.',
  'noDataYetLabel': 'Wala pang datos',
  'startLabel': 'Simulan',
  'takeDailyEvaluationsFirstPopulateLabel': 'Gawin muna ang daily evaluations para mapunan ang chart na ito.',
  'weekTrendLabel': 'Trend sa 4 na linggo',
  'ptsLabel': 'pts',
  'averageAccuracyLabel': 'Karaniwang katumpakan',
  'scoresLabel': 'Mga iskor',
  'preTestPostTestChangeLabel': 'Ang Pre-test, Post-test, at Pagbabago ay kumakatawan sa galaw ng average score.',
  'preTestLabel2': 'Pre-test',
  'postTestLabel2': 'Post-test',
  'changeLabel': 'Pagbabago',
  'learningReportUnavailableLabel': 'Hindi available ang learning report',
  'loadingLearningReportLabel': 'Nilo-load ang Learning Report',
  'fetchingWeeklyProgressSummaryLabel': 'Kinukuha ang lingguhang buod ng progreso.',
  'weekSummaryLabel': 'Buod ng Linggong Ito',
  'answerAccuracyLabel': 'Katumpakan ng Sagot',
  'fixedGapsLabel2': 'Naayos na Gaps',
  'remainingGapsLabel2': 'Natitirang Gaps',
  'answerAccuracyPercentageCorrectAnswersLabel': 'Katumpakan ng sagot = porsyento ng tamang sagot sa napiling saklaw ng petsa.',
  'weekProgressLabel': 'Progreso sa 4 na Linggo',
  'trackAccuracyAttemptVolumeGapLabel': 'Subaybayan ang katumpakan, dami ng pagsubok, at galaw ng gaps kada linggo.',
  'effortVsImpactLabel': 'Effort kumpara sa impact',
  'attemptsLabel': 'Mga pagsubok',
  'activeDaysLabel': 'Aktibong araw',
  'impactLabel': 'Impact',
  'strongConceptsVsNeedsImprovementLabel': 'Malalakas na Konsepto kumpara sa Kailangang Pagbutihin',
  'focusConceptsBiggestLiftOnesLabel': 'Pokus sa mga konseptong may pinakamalaking lift at sa mga nanganganib pa rin.',
  'numberRightShowsConceptMasteryLabel': 'Ang numero sa kanan ay nagpapakita ng pagbabago sa concept mastery (%) sa saklaw na ito.',
  'nowStrongLabel': 'Malakas Na',
  'noConceptsShowedSignificantImprovementLabel': 'Walang konseptong nagpakita ng malaking pag-unlad ngayong linggo.',
  'needsImprovementLabel': 'Kailangang Pagbutihin',
  'noRiskConceptsRangeLabel': 'Walang nanganganib na konsepto sa saklaw na ito.',
  'weekLabel2': 'Ngayong linggo',
  'lastWeekLabel': 'Nakaraang linggo',
  'lastWeeksLabel': 'Huling 4 na linggo',
  'averageScoreLabel': 'Karaniwang Iskor',
  'notEnoughMatchedPreTestLabel': 'Kulang pa ang magkatugmang pre-test at post-test na datos.',
  'reportRequestTimedOutPleaseLabel': 'Nag-timeout ang report request. Pakisubukan ulit.',
  'reportCouldNotLoadedPleaseLabel': 'Hindi ma-load ang ulat. Pakisubukan ulit.',
  'completeDataLabel': 'Kumpletong Datos',
  'partialDataLabel': 'Bahagyang Datos',
  'earlyDataLabel': 'Maagang Datos',
  'highLeverageLabel': 'Malaking leverage',
  'steadyLabel': 'Matatag',
  'needsFocusLabel': 'Kailangan ng pokus',
  'noSignalLabel': 'Walang senyales',
  'reportBuiltFromSufficientlyCompleteLabel': 'Nabuo ang ulat na ito mula sa sapat na kumpletong kasaysayan.',
  'dataExistsButComparisonHistoryLabel': 'May datos, pero hindi pa kumpleto ang kasaysayan para sa paghahambing.',
  'dataStillThinSoSomeLabel': 'Manipis pa ang datos, kaya maagang tantiya pa ang ilang insight.',
  'dataQualityStatusNotDefinedLabel': 'Hindi pa natutukoy ang data quality status.',
  'overallLabel2': 'Kabuuan',
  'applicationLabel2': 'Aplikasyon',
  'analysisLabel2': 'Pagsusuri',
  'weekLabel3': '0 ngayong linggo',
  'learningPerformanceLabel': 'Learning performance',
  'noAssessmentAttemptsRangeYetLabel': 'Wala pang assessment attempt sa saklaw na ito. Gumawa ng daily evaluation para mabuo ang graph.',
  'useAsLearningGoalLabel': 'Gamitin ito bilang learning goal mo?',
  'chooseAnotherNodeLabel': 'Pumili ng ibang node',
  'startPretestLabel': 'Simulan ang pretest',
  'activeGoalFoundLabel': 'May nahanap na aktibong layunin',
  'backLabel2': 'Bumalik',
  'continueExistingGoalLabel': 'Ipagpatuloy ang umiiral na layunin',
  'useAsNewGoalLabel': 'Gamitin bilang bagong layunin',
  'visualizePrerequisitesGapsNextConceptsLabel': 'Ilarawan ang prerequisites, gaps, at susunod na konsepto.',
  'alreadyHaveActiveGoalNodeLabel': 'May aktibo ka nang layunin para sa node na ito:',
  'canContinueGoalGoBackLabel': 'Puwede mong ituloy ang layuning ito, o bumalik para pumili ng node.',
  'findLearningGoalNodeLabel': 'Hanapin ang learning goal node',
  'searchAgainLabel': 'Maghanap ulit',
  'searchAgainNewQueryLabel': 'Maghanap ulit gamit ang bagong query',
  'sureWantTakeLabel': 'Sigurado ka bang ito ang kukunin mo?',
  'nodeDetailLabel': 'Detalye ng node',
  'descriptionLabel': 'Paglalarawan',
  'subjectLabel2': 'Asignatura',
  'matchLabel': 'Tugma',
  'seeGraphLabel': 'Tingnan ang graph',
  'lockLabel': 'I-lock',
  'findLearningGoalFirstLabel': 'Hanapin muna ang learning goal',
  'typeGoalThenWicaraWillLabel': 'I-type ang layunin mo, tapos itutugma ito ng WICARA sa isang material node. Magsisimula lang ang pretest kapag kinumpirma mo ang node.',
  'nodeNotCertainLabel': 'Hindi pa tiyak ang node',
  'tryAddingGradeSubjectMoreLabel': 'Subukang magdagdag ng baitang, asignatura, o mas tiyak na paksa.',
  'pickClosestCandidateLabel': 'Piliin ang pinakamalapit na kandidato',
  'recommendedNodeLabel': 'Inirerekomendang node',
  'otherPossibleNodesLabel': 'Iba pang posibleng node',
  'editPromptLabel': 'I-edit ang prompt',
  'viewDetailLabel': 'Tingnan ang detalye',
  'descriptionNotFoundLabel': 'Hindi nahanap ang paglalarawan.',
  'nodeBelowGradeLevelCanLabel': 'Mas mababa ang node na ito sa baitang mo; makapagpapatibay ito ng pundasyon.',
  'nodeAboveGradeLevelMayLabel': 'Mas mataas ang node na ito sa baitang mo; maaaring mas mahirap.',
  'nodeFitsGradeLevelLabel': 'Bagay ang node na ito sa baitang mo.',
  'mathLabel': 'Matematika',
  'physicsLabel': 'Pisika',
  'chemistryLabel': 'Kimika',
  'biologyLabel': 'Biyolohiya',
  'uploadingWorkImageLabel': 'Ina-upload ang larawan ng gawa mo...',
  'answerSentEvaluatingWorkPreparingLabel': 'Naipadala ang sagot. Sinusuri ang gawa mo at inihahanda ang susunod na tanong...',
  'submitAnswerLabel': 'Isumite ang sagot',
  'addReasoningSketchLabel': 'Magdagdag ng pangangatwiran / sketch',
  'hideWorkEvidenceLabel': 'Itago ang work evidence',
  'workEvidenceLabel': 'Work evidence',
  'typeStepsUploadPhotoWorkLabel': 'I-type ang mga hakbang mo, mag-upload ng larawan ng gawa mo, o pareho. Babasahin ng AI ang larawan bilang mga hakbang ng solusyon.',
  'writeSolutionStepsLabel': 'Isulat ang mga hakbang ng solusyon mo...',
  'uploadWorkImageLabel': 'Mag-upload ng larawan ng gawa',
  'removeImageLabel': 'Alisin ang larawan',
  'submitAnswerEvidenceLabel': 'Isumite ang sagot na may ebidensya',
  'correctLabel3': 'tama',
  'noAnswersLabel': 'Walang sagot',
  'officialMcqScoreLabel': 'Opisyal na MCQ score',
  'reportLabel': 'Ulat',
  'whatLooksStrongLabel': 'Ano ang mukhang malakas',
  'whatNeedsWorkLabel': 'Ano ang kailangang ayusin',
  'evidenceNotesLabel': 'Mga tala ng ebidensya',
  'checkedNodesLabel': 'Mga nasuring node',
  'levelLabel': 'Antas',
  'nextPathFocusLabel': 'Pokus ng susunod na path',
  'reasoningSuggestsMisconceptionNodeLabel': 'Nagpapahiwatig ang pangangatwiran ng misconception sa node na ito.',
  'therePossibleCarelessChoiceDespiteLabel': 'May posibleng pagkakamali sa pagpili kahit makatwiran ang pangangatwiran.',
  'evidenceWasStoredButNoLabel': 'Naitago ang ebidensya, pero walang nakasulat na hakbang na masusuri.',
  'noSubjectGoalsYetLabel': 'Wala pang layunin sa {0}',
  'subjectGoalsLabel': 'Mga layunin sa {0}',
  'percentCompleteLabel': '{0}% tapos',
  'moduleStatusLabel': 'Status ng module: {0}',
  'moduleStatusWithMinutesLabel': '{0} min - status ng module: {1}',
  'sessionReturnsToPhaseLabel': 'Bumabalik ang session sa {0} para sa remediation.{1}',
  'targetPassedLabel': '{0}/{1} tama. Pasado ang target na ito.',
  'conceptMarkedForReviewLabel': '{0}/{1} tama. Minarkahan ng backend ang konseptong ito para sa review.',
  'accuracyPercentLabel': 'Katumpakan {0}%',
  'fixedGapsDeltaLabel': '+{0} ngayong linggo',
  'remainingGapsDeltaLabel': '{0} ngayong linggo',
  'weeklyPointSummaryLabel': '{0} pagsubok • {1} naayos na gaps • {2} natitirang gaps',
  'positiveDeltaThisWeekLabel': '+{0} ngayong linggo',
  'deltaThisWeekLabel': '{0} ngayong linggo',
  'activeGoalConflictBodyLabel': 'May aktibo ka nang layunin para sa "{0}". Puwede mong ituloy iyon o bumalik para pumili ng node.',
  'reasoningQualityLabel': 'Kalidad ng pangangatwiran: {0}{1}.',
  'learnConceptInGraphLabel': 'Aralin ang {0} sa prerequisite graph.',
  'outputValidJsonOnlyLabel': 'Mag-output lang ng valid na JSON:',
  'workspace.collapseLabel': 'Tiklupin',
  'workspace.detailsLabel': 'Detalye',
  'workspace.finalTargetLabel': 'Pinal na target: {0}',
  'workspace.phaseTransitionReadyLabel': 'Handa nang lumipat ng phase',
  'workspace.continueThisPhaseLabel': 'Ipagpatuloy ang phase na ito',
  'goalResolvingTitle': 'Hinahanap ang tamang konsepto',
  'goalResolvingSubtitle': 'Itinutugma namin ang iyong isinulat sa\nmapa ng kurikulum.',
  'goalResolvingStageRead': 'Binabasa ang gusto mong matutunan',
  'goalResolvingStageSearch': 'Hinahanap sa mapa ng kurikulum',
  'goalResolvingStageMatch': 'Pinipili ang pinakamalapit na konsepto',
  'answerCheckingTitle': 'Sinusuri ang iyong sagot',
  'answerCheckingSubtitle': 'Binabasa ng tutor ang iyong pangangatwiran, hindi lang\nang pinili mong opsyon.',
  'answerCheckingStageRead': 'Binabasa ang iyong pangangatwiran',
  'answerCheckingStageReason': 'Tinitimbang ang naiintindihan mo na',
  'answerCheckingStageNext': 'Pinipili ang susunod na itatanong',
  'pretestBuildingTitle': 'Binubuo ang iyong pretest',
  'pretestBuildingSubtitle': 'Sumusulat kami ng mga tanong na tugma sa iyong layunin.\nKaraniwang tumatagal ito nang mga dalawang minuto.',
  'pretestBuildingStageGoal': 'Binabasa ang iyong layunin sa pag-aaral',
  'pretestBuildingStageMap': 'Minamapa ang mga kailangang konsepto muna',
  'pretestBuildingStageWrite': 'Sumusulat ng tanong sa bawat antas ng hirap',
  'pretestBuildingStageCheck': 'Sinusuri ang bawat sagot at paliwanag',
  'pretestBuildingStageFinish': 'Pinagsasama-sama ang iyong pretest',
  'pretestBuildingFootnote': 'Panatilihing bukas ang screen na ito. Isinusulat ang mga tanong mo para sa iyo.',
  'workspace.imageUnreadableMessage': 'Hindi mabasa ang image file.',
  'workspace.imageTooLargeMessage': 'Ang larawan ay dapat 10 MB o mas maliit.',
};
