/// ภาษาไทย translations for `OnboardingCopy`.
///
/// Keys match member names (`member.case` for switch arms). Templated members
/// use `{0}`, `{1}` … placeholders; list members join items with `|`.
/// Missing keys fall back to English.
///
/// Authored without native-speaker review — proofread before release.
library;

const copyTh = <String, String>{
  'letsSetYouUpTitle': 'มาตั้งค่าบัญชีของคุณกันเถอะ',
  'letsSetYouUpSubtitle':
      'บอกเราสักเล็กน้อยเกี่ยวกับตัวคุณ\nเพื่อปรับการเรียนรู้ให้เหมาะกับคุณ',
  'fullNameLabel': 'ชื่อ-นามสกุล',
  'countryLabel': 'ประเทศ',
  'gradeLevelLabel': 'ระดับชั้น',
  'preferredLanguageLabel': 'ภาษาที่ต้องการ',
  'continueLabel': 'ต่อไป',
  'improveExperienceNote': 'เราจะพัฒนาประสบการณ์นี้ต่อไป\nเพื่อคุณโดยเฉพาะ',
  'chooseSubjectsTitle': 'เลือกวิชาของคุณ',
  'chooseSubjectsSubtitle':
      'เลือกวิชาที่คุณต้องการเรียน\nคุณเปลี่ยนได้ทุกเมื่อ',
  'customizeLaterNote': 'คุณปรับแต่งเพิ่มเติมได้ภายหลัง',
  'preferencesTitle': 'คุณอยากเรียนแบบไหน?',
  'preferencesSubtitle': 'เลือกสิ่งที่คุณชอบ คุณเปลี่ยนได้\nทุกเมื่อ',
  'studyGoalLabel': 'เป้าหมายการเรียน',
  'dailyStudyTimeLabel': 'เวลาเรียนต่อวัน',
  'adaptivePretestLabel': 'ไปยังแบบทดสอบก่อนเรียนแบบปรับตัว',
  'personalizePathNote': 'สิ่งนี้ช่วยให้เราปรับเส้นทางการเรียนให้เหมาะกับคุณ',
  'preferenceCallout':
      'WICARA ปรับตามคุณ จังหวะของคุณ สไตล์ของคุณ\nและเป้าหมายของคุณ',
  'profileTitle': 'โปรไฟล์',
  'profileSubtitle': 'จัดการการตั้งค่าการเรียนและบัญชีของคุณ',
  'homeLabel': 'หน้าแรก',
  'learnLabel': 'เรียน',
  'progressLabel': 'ความคืบหน้า',
  'learningSetupTitle': 'การตั้งค่าการเรียน',
  'preferencesSectionTitle': 'การตั้งค่า',
  'subjectsLabel': 'วิชา',
  'logoutLabel': 'ออกจากระบบ',
  'welcomeBack': 'ยินดีต้อนรับกลับมา,\n',
  'homeSubtitle': 'พร้อมเรียนต่อและสร้างสิ่งดี ๆ ในวันนี้หรือยัง?',
  'languageLabel': 'ภาษา',
  'getStartedLabel': 'เริ่มต้น',
  'alreadyHaveAccountLabel': 'ฉันมีบัญชีอยู่แล้ว',
  'signInTitle': 'ยินดีต้อนรับกลับมา',
  'signInSubtitle': 'เข้าสู่ระบบเพื่อเรียนต่อ',
  'registerTitle': 'สร้างบัญชีของคุณ',
  'registerSubtitle': 'สมัครครั้งเดียว แล้วไปต่อกับเส้นทางการเรียนของคุณ',
  'emailOrPhoneLabel': 'อีเมลหรือเบอร์โทร',
  'emailOrPhoneHint': 'กรอกอีเมลหรือเบอร์โทรของคุณ',
  'emailLabel': 'อีเมล',
  'emailHint': 'กรอกอีเมลของคุณ',
  'passwordLabel': 'รหัสผ่าน',
  'passwordHint': 'กรอกรหัสผ่านของคุณ',
  'fullNameHint': 'กรอกชื่อ-นามสกุลของคุณ',
  'forgotPasswordLabel': 'ลืมรหัสผ่าน?',
  'signInLabel': 'เข้าสู่ระบบ',
  'registerLabel': 'สมัคร',
  'logInLabel': 'เข้าสู่ระบบ',
  'orContinueWithLabel': 'หรือดำเนินการต่อด้วย',
  'securityNoteLabel': 'ข้อมูลของคุณเป็นส่วนตัวและปลอดภัย',
  'cancelLabel': 'ยกเลิก',
  'applyLabel': 'ใช้',
  'searchLabel': 'ค้นหา',
  'recommendedLabel': 'แนะนำ',
  'tracksLabel': 'เส้นทาง',
  'galleryLabel': 'แกลเลอรี',
  'viewAllLabel': 'ดูทั้งหมด',
  'nextUpLabel': 'ถัดไป',
  'exploreLabel': 'สำรวจ',
  'currentStreakLabel': 'สถิติต่อเนื่องปัจจุบัน',
  'backToHomeLabel': 'กลับสู่หน้าแรก',
  'continueLearningLabel': 'เรียนต่อ',
  'learningGoalTitle': 'คุณอยากเรียนอะไร?',
  'learningGoalSubtitle':
      'พิมพ์เป้าหมายของคุณก่อน WICARA จะค้นหาโหนดเนื้อหาที่ตรงกัน จากนั้นแบบทดสอบก่อนเรียนจะเริ่มเมื่อคุณยืนยัน',
  'learningTopicLabel': 'หัวข้อการเรียน',
  'generatePretestLabel': 'สร้างแบบทดสอบก่อนเรียน',
  'typeATopicHint': 'พิมพ์หัวข้อ',
  'loadingPretestLabel': 'กำลังโหลดแบบทดสอบก่อนเรียน',
  'pretestUnavailableLabel': 'ไม่มีแบบทดสอบก่อนเรียน',
  'tryAgainLabel': 'ลองอีกครั้ง',
  'preTestLabel': 'ก่อนเรียน',
  'postTestLabel': 'หลังเรียน',
  'refreshLabel': 'รีเฟรช',
  'retryLabel': 'ลองใหม่',
  'backLabel': 'ย้อนกลับ',
  'undoLabel': 'เลิกทำ',
  'redoLabel': 'ทำซ้ำ',
  'teacherReviewLabel': 'ครูตรวจทาน',
  'insightsLabel': 'ข้อมูลเชิงลึก',
  'knowledgeMapLabel': 'แผนที่ความรู้',
  'learningReportLabel': 'รายงานการเรียน',
  'reviewNowLabel': 'ทบทวนตอนนี้',
  'reviewDueLabel': 'ถึงกำหนดทบทวน',
  'studyGoalOptionalLabel': 'เป้าหมายการเรียน (ไม่บังคับ)',
  'dailyStudyTimeOptionalLabel': 'เวลาเรียนต่อวัน (ไม่บังคับ)',
  'learnSubtitleRecommended': 'เส้นทางที่แนะนำเพื่อช่วยให้คุณบรรลุเป้าหมาย',
  'learnSubtitleTracks': 'สำรวจเส้นทางการเรียนของคุณ หรือสร้างเส้นทางใหม่ที่นี่',
  'learnSubtitleGallery': 'ทบทวนวิดีโอและบทสรุปจากเส้นทางการเรียนรู้ของคุณ',
  'todaysLearningQueueLabel': 'คิวการเรียนวันนี้',
  'continueSessionLabel': 'เรียนต่อ',
  'wantToLearnSomethingNewLabel': 'อยากเรียนรู้สิ่งใหม่ไหม?',
  'exploreTracksDescription': 'สำรวจเส้นทางที่คุณสร้างไว้ หรือเริ่มเส้นทางใหม่',
  'streakDaysLabel': '{0} วัน',
  'dailyEvaluationLabel': 'การประเมินประจำวัน',
  'dailyEvaluationPrompt': '. เลือกคะแนนความมั่นใจหากต้องการ แล้วทำแบบทดสอบประจำวัน',
  'takeDailyEvaluationLabel': 'ทำการประเมินประจำวัน',
  'dailyEvalsWordmark': 'ประเมินประจำวัน',
  'dailyEvalsQuickCheckin': 'เช็กอินสั้น ๆ สำหรับเส้นทางการเรียนวันนี้',
  'finishDailyEvalsLabel': 'ทำการประเมินประจำวันให้เสร็จ',
  'dailyQuestionProgressLabel': '{0} จาก {1}',
  'reviewDueSummaryLabel': '{0} รายการพร้อมทบทวน',
  'retentionForecastLabel': 'การคาดการณ์การจดจำของคุณ',
  'retentionForecastBasisLabel': 'อ้างอิงจาก MVP ของเส้นโค้งการลืมของ Ebbinghaus',
  'retentionCoachingLabel': 'ทบทวนต่อไปเพื่อยกเส้นโค้งให้สูงขึ้นและเพิ่มการจดจำระยะยาว',
  'evaluationCompleteLabel': 'ประเมินเสร็จแล้ว 🎉',
  'evaluationCompleteSubtitle': 'เยี่ยมมาก! คุณกำลังสร้างความรู้ที่คงทน',
  'reviewedLabel': 'ทบทวนแล้ว',
  'toReviewAgainLabel': 'ต้องทบทวนอีกครั้ง',
  'scoreLabel': 'คะแนน',
  'reviewedConceptsLabel': 'แนวคิดที่ทบทวนแล้ว',
  'noReviewedConceptsLabel': 'ยังไม่มีแนวคิดที่ทบทวน',
  'continueLearningReason': 'ไปยังเส้นทางการเรียนของคุณ',
  'statusGoodLabel': 'ดี',
  'statusStrongLabel': 'แข็งแรง',
  'statusReviewLabel': 'ทบทวน',
  'retentionLiftLabel': 'การเพิ่มการจดจำ',
  'daysUntilNextReviewLabel': 'จำนวนวันจนถึงการทบทวนครั้งถัดไป',
  'learnSomethingNewLabel': 'เรียนรู้สิ่งใหม่',
  'newTrackDescription': 'สร้างเส้นทางใหม่นอกรายการปัจจุบันของคุณ',
  'newTrackLabel': 'เส้นทางใหม่',
  'progressSubtitle': 'เริ่มจากรายงานการเรียนของคุณ แล้วสำรวจแผนที่ความรู้',
  'learningReportDescription': 'ผลการเรียนรายสัปดาห์ ช่องว่างที่แก้ไขแล้ว แนวคิดที่ปลดล็อก',
  'fixedGapsLabel': 'ช่องว่างที่แก้ไขแล้ว',
  'remainingGapsLabel': 'ช่องว่างที่เหลือ',
  'thisWeekFixedDelta': '+4 สัปดาห์นี้',
  'thisWeekRemainingDelta': '-2 สัปดาห์นี้',
  'learningReportHint': 'วางเมาส์หรือแตะที่สัปดาห์เพื่อดูการเติบโต ช่องว่างที่แก้ไขแล้ว และการจดจำที่เพิ่มขึ้น',
  'retentionDeltaLabel': '+{0}% การจดจำ',
  'weekLabel': 'สัปดาห์ {0}',
  'knowledgeMapDescription': 'สำรวจขอบเขตวิชาและเส้นทางความรู้พื้นฐาน',
  'fallbackGraphLabel': 'กราฟสำรองแบบคงที่',
  'liveCurriculumGraphLabel': 'กราฟความรู้แบบสด',
  'nodeCountLabel': '{0} โหนด',
  'masteryConfidenceLabel': 'ความมั่นใจในความเชี่ยวชาญ',
  'aboutThisConceptLabel': 'เกี่ยวกับแนวคิดนี้',
  'relatedConceptsLabel': 'แนวคิดที่เกี่ยวข้อง',
  'noDirectRelatedConceptLabel': 'ไม่มีแนวคิดที่เกี่ยวข้องโดยตรง',
  'crossSubjectConnectionsLabel': 'การเชื่อมโยงข้ามวิชา',
  'graphOfGraphsHint': 'ลิงก์ Graph of Graphs จะแสดงเมื่อมีข้อมูล',
  'conceptBridgeFallbackLabel': 'สะพานเชื่อมแนวคิด',
  'conceptFallbackDescription': 'แนวคิดในกราฟความรู้พื้นฐาน',
  'confidenceQuestionLabel': 'คุณมั่นใจแค่ไหน?',
  'yourKnowledgeStateLabel': 'สถานะความรู้ของคุณ',
  'personalizedPathGeneratedLabel': 'สร้างเส้นทางเฉพาะบุคคลแล้ว',
  'personalizedPathDescription': 'เริ่มจากความรู้พื้นฐาน แล้วฝึกคำถามหาสาเหตุราก',
  'continueToMyPathLabel': 'ไปยังเส้นทางของฉัน',
  'missingPrerequisiteGapsLabel': 'ช่องว่างความรู้พื้นฐานที่ขาดหาย',
  'learnerLabel': 'ผู้เรียน',
  'statusLabel': 'สถานะ',
  'couldNotLoadQueueLabel': 'โหลดคิวไม่สำเร็จ',
  'nothingToReviewLabel': 'ไม่มีอะไรให้ทบทวน',
  'reviewItemLabel': 'รายการทบทวน',
  'flaggedForReviewLabel': 'ทำเครื่องหมายเพื่อตรวจทาน',
  'learningGoalDiagnosisLabel': 'การวินิจฉัยเป้าหมายการเรียนรู้',
  'learnerAskedLabel': 'ผู้เรียนถามว่า',
  'subjectSingularLabel': 'วิชา',
  'suggestedConceptIdLabel': 'รหัสแนวคิดที่แนะนำ',
  'confidenceLabel': 'ความมั่นใจ',
  'reasoningEvaluationLabel': 'การประเมินการให้เหตุผล',
  'learnerReasoningLabel': 'การให้เหตุผลของผู้เรียน',
  'answerScoreLabel': 'คะแนนคำตอบ',
  'reasoningScoreLabel': 'คะแนนการให้เหตุผล',
  'evidenceScoreLabel': 'คะแนนหลักฐาน',
  'overrideConceptIdLabel': 'แทนที่รหัสแนวคิดพื้นฐานที่วินิจฉัยไว้ การยืนยันจะตั้งสถานะการวินิจฉัยเป็น "ยืนยันแล้ว"',
  'correctedOfReviewedLabel': 'แก้ไขแล้ว {0} จากที่ตรวจ {1}',
  'noReviewedItemsLabel': 'ยังไม่มีรายการที่ตรวจแล้ว',
  'reviewedCountLabel': 'ตรวจแล้ว {0}',
  'darkCorrectedLightReviewedLabel': 'เข้ม = แก้ไขแล้ว · อ่อน = ตรวจแล้ว',
  'reviewArtifactLabel.question': 'คำถาม',
  'reviewArtifactLabel.diagnosis': 'การวินิจฉัย',
  'reviewArtifactLabel.evaluation': 'การประเมิน',
  'reviewArtifactLabel.open': 'เปิดอยู่',
  'reviewArtifactLabel.approved': 'อนุมัติแล้ว',
  'reviewArtifactLabel.rejected': 'ถูกปฏิเสธ',
  'reviewArtifactLabel.corrected': 'แก้ไขแล้ว',
  'reviewArtifactLabel.all': 'ทั้งหมด',
  'reviewArtifactLabel.low_confidence': 'ความมั่นใจต่ำ',
  'reviewArtifactLabel.risk_signal': 'สัญญาณความเสี่ยง',
  'reviewArtifactLabel.sampled': 'สุ่มตัวอย่าง',
  'reviewArtifactLabel.learner_flag': 'ผู้เรียนแจ้ง',
  'overallMasteryLabel': 'ความเชี่ยวชาญโดยรวม',
  'streakSummaryLabel': '🔥 ต่อเนื่อง {0} วัน · ดีที่สุด {1} · ใช้งาน {2} วัน',
  'masteryBySubjectLabel': 'ความเชี่ยวชาญแยกตามวิชา',
  'noSubjectDataLabel': 'ยังไม่มีข้อมูลรายวิชา',
  'streakDaysShortLabel': '{0}ว',
  'scoreTrendLabel': 'แนวโน้มคะแนน',
  'needsReviewLabel': 'ต้องทบทวน ({0})',
  'edgeAiStatusReadFailedLabel': 'อ่านสถานะ edge runtime ไม่สำเร็จ: {0}',
  'edgeAiStatusChecking': 'กำลังตรวจสอบ',
  'edgeAiStatusUnknown': 'ไม่ทราบ',
  'edgeAiStatusReady': 'พร้อม',
  'edgeAiStatusNeedsInit': 'ต้องเริ่มต้นระบบ',
  'edgeAiStatusNeedsInstall': 'ต้องติดตั้ง',
  'todaysTopicLabel': 'หัวข้อวันนี้: ',
  'notConfidentLabel': 'ไม่มั่นใจ',
  'veryConfidentLabel': 'มั่นใจมาก',
  'nextQuestionLabel': 'คำถามถัดไป',
  'highImpactLabel': 'ผลกระทบสูง',
  'maintainedLabel': 'คงไว้',
  'correctLabel': 'ถูกต้อง',
  'pendingLabel': 'รอดำเนินการ',
  'recommendedNextActionsLabel': 'การดำเนินการถัดไปที่แนะนำ',
  'spacedRepetitionImpactLabel': 'ผลของการทบทวนแบบเว้นระยะ',
  'memoryStrengthenedLabel': 'คุณได้เสริมความจำของคุณแล้ว',
  'contentGalleryLabel': 'คลังเนื้อหา',
  'contentGalleryDescription': 'วิดีโอทั้งหมดที่สร้างไว้ก่อนหน้านี้อยู่ที่นี่ พร้อมเล่นซ้ำพร้อมโน้ตที่ WICARA รวบรวมให้คุณ',
  'notesLabel': 'โน้ต',
  'cheatsheetSummaryLabel': 'สรุปชีตสูตร',
  'recommendedForCurrentReadinessLabel': 'แนะนำสำหรับแคลคูลัส I โดยอิงจาก\nช่องว่างและความพร้อมปัจจุบันของคุณ',
  'fixedShortLabel': '+4 แก้ไขแล้ว',
  'overallLabel': 'โดยรวม',
  'applicationLabel': 'การประยุกต์ใช้',
  'analysisLabel': 'การวิเคราะห์',
  'completeLabel': 'เสร็จสิ้น',
  'skillGrowthLabel': 'การเติบโตของทักษะ',
  'remainingCountLabel': 'เหลือ {0}',
  'loadingCurriculumLabel': 'กำลังโหลดหลักสูตรจากแบ็กเอนด์...',
  'prerequisiteLayerLabel': 'ชั้นความรู้พื้นฐาน',
  'combinedLayerLabel': '{0} + อีก {1}',
  'prerequisitesLabel': 'ความรู้พื้นฐาน',
  'noDirectPrerequisiteLabel': 'ไม่มีความรู้พื้นฐานโดยตรง',
  'relatedBadgeLabel': 'เกี่ยวข้อง',
  'bypassForWebDevLabel': 'ข้ามสำหรับการพัฒนาเว็บ',
  'passwordResetMockedMessage': 'การรีเซ็ตรหัสผ่านยังเป็นแบบจำลองอยู่',
  'emailRequiredMessage': 'กรอกอีเมลของคุณ',
  'fullNameRequiredMessage': 'กรอกชื่อ-นามสกุลของคุณ',
  'registrationEmailValidationMessage': 'ใช้ที่อยู่อีเมลในการลงทะเบียน',
  'passwordMinLengthMessage': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
  'adaptivePretestReadyNextLabel': 'แบบทดสอบก่อนเรียนแบบปรับตัวพร้อมแล้ว',
  'adaptivePretestReadyDescription': 'คำถามไม่กี่ข้อจะช่วยปรับจุดเริ่มต้นของคุณ',
  'pretestGeneratedCompleteLabel': 'สร้างแบบทดสอบก่อนเรียนเสร็จแล้ว!',
  'openingAdaptivePretestLabel': 'กำลังเปิดแบบทดสอบก่อนเรียนแบบปรับตัวของคุณ',
  'lowLabel': 'ต่ำ',
  'highLabel': 'สูง',
  'basedOnYourResponsesLabel': 'อ้างอิงจากคำตอบของคุณ',
  'whatsNextLabel': 'ขั้นต่อไป',
  'retakePretestAnytimeLabel': 'คุณสามารถทำแบบทดสอบก่อนเรียนใหม่ได้ทุกเมื่อ',
  'currentTopicLabel': 'หัวข้อปัจจุบัน',
  'askOrReflectHereHint': 'ถามหรือสะท้อนความคิดที่นี่...',
  'speechReadAloud': 'อ่านออกเสียง',
  'speechReadAloudHint': 'อ่านเนื้อหานี้ด้วยเสียง',
  'speechStop': 'หยุดพูด',
  'speechStopHint': 'หยุดเสียงพูดหรือการป้อนด้วยเสียงที่กำลังทำงาน',
  'speechPause': 'หยุดชั่วคราว',
  'speechResume': 'เล่นต่อ',
  'speechSpeed': 'ความเร็วเสียงพูด',
  'speechSpeedValue': '{0} เท่า',
  'speechVoiceInput': 'การป้อนด้วยเสียง',
  'speechVoiceInputHint': 'เริ่มหรือหยุดการบันทึกเสียง',
  'speechListening': 'กำลังฟัง...',
  'speechProcessing': 'กำลังประมวลผล...',
  'speechSpeaking': 'กำลังพูด',
  'speechPaused': 'หยุดเสียงพูดชั่วคราว',
  'speechError': 'เกิดข้อผิดพลาดด้านเสียง',
  'speechMicPermissionDenied': 'ไม่ได้รับอนุญาตให้ใช้ไมโครโฟน',
  'speechMicPermissionInstructions': 'เปิดสิทธิ์ไมโครโฟนในการตั้งค่าอุปกรณ์เพื่อใช้การป้อนด้วยเสียง',
  'speechServiceUnavailable': 'บริการเสียงพูดไม่พร้อมใช้งาน',
  'correctionMetricsLabel': 'ตัวชี้วัดการแก้ไข',
  'typeLabel': 'ประเภท',
  'triggerLabel': 'ตัวกระตุ้น',
  'allFilterLabel': 'ทั้งหมด',
  'noAiOutputsMatchFiltersLabel': 'ตอนนี้ไม่มีผลลัพธ์ AI ที่ตรงกับตัวกรองเหล่านี้',
  'noSummaryLabel': '(ไม่มีบทสรุป)',
  'itemNotFoundLabel': 'ไม่พบรายการ',
  'approveThisOutputLabel': 'อนุมัติผลลัพธ์นี้',
  'rejectThisOutputLabel': 'ปฏิเสธผลลัพธ์นี้',
  'optionalNoteHint': 'โน้ตเพิ่มเติม (ไม่บังคับ)',
  'whyIsItWrongHint': 'ทำไมถึงผิด? (จำเป็น)',
  'approveLabel': 'อนุมัติ',
  'rejectLabel': 'ปฏิเสธ',
  'correctLabelAction': 'แก้ไข',
  'approvedLabel': 'อนุมัติแล้ว',
  'rejectedLabel': 'ถูกปฏิเสธ',
  'correctionSavedLabel': 'บันทึกการแก้ไขแล้ว',
  'correctionFailedLabel': 'การแก้ไขล้มเหลว',
  'resolveSuccessLabel': '{0} · ผู้เรียนไม่ได้รับผลกระทบแบบเรียลไทม์',
  'resolveFailureLabel': '{0} ล้มเหลว',
  'flaggedBecauseLabel': 'ถูกทำเครื่องหมายเพราะ: {0}',
  'artifactLabel': 'อาร์ทิแฟกต์',
  'artifactUnavailableLabel': 'ไม่สามารถโหลดอาร์ทิแฟกต์ต้นทางได้ (อาจถูกลบไปแล้ว) แต่บันทึกการตรวจทานยังอยู่',
  'generatedQuestionLabel': 'คำถามที่สร้างขึ้น',
  'promptLabel': 'พรอมต์',
  'helperLabel': 'ตัวช่วย',
  'optionsLabel': 'ตัวเลือก',
  'expectedReasoningLabel': 'การให้เหตุผลที่คาดหวัง',
  'generationSourceLabel': 'แหล่งที่มาของการสร้าง',
  'noneLabel': '(ไม่มี)',
  'alternativesLabel': 'ทางเลือกอื่น',
  'candidateCountLabel': '{0} ตัวเลือก',
  'modelLabel': 'โมเดล',
  'isCorrectLabel': 'ถูกต้องไหม?',
  'yesLabel': 'ใช่',
  'noLabel': 'ไม่',
  'diagnosticSignalLabel': 'สัญญาณเชิงวินิจฉัย',
  'historyLabel': 'ประวัติ',
  'correctArtifactTitle': 'แก้ไข {0}',
  'saveCorrectionLabel': 'บันทึกการแก้ไข',
  'artifactNotCorrectableLabel': 'อาร์ทิแฟกต์ประเภทนี้แก้ไขไม่ได้',
  'optionsTapCorrectLabel': 'ตัวเลือก (แตะวงกลมเพื่อทำเครื่องหมายข้อที่ถูก)',
  'optionNumberLabel': 'ตัวเลือก {0}',
  'teacherFeedbackLabel': 'ความคิดเห็นของครู',
  'auditNoteLabel': 'โน้ต (บันทึกการตรวจสอบ)',
  'humanCorrectionRateLabel': 'อัตราการแก้ไขโดยมนุษย์',
  'backlogLabel': 'งานค้าง',
  'oldestBacklogLabel': 'เก่าสุด {0}ว',
  'noneOpenLabel': 'ไม่มีรายการที่เปิดอยู่',
  'correctionRateByTypeLabel': 'อัตราการแก้ไขแยกตามประเภท',
  'triggerPrecisionLabel': 'ความแม่นยำของตัวกระตุ้น',
  'triggerPrecisionDescription': 'จากรายการที่ตัวกระตุ้นทำเครื่องหมายไว้ มีกี่รายการที่ต้องแก้จริง (แก้ไขหรือปฏิเสธ) ยิ่งสูงยิ่งคุ้มกับเวลาของครู',
  'noResolvedItemsLabel': 'ยังไม่มีรายการที่แก้ไขเสร็จ',
  'lastFourteenDaysLabel': '14 วันที่ผ่านมา',
  'noActivityFourteenDaysLabel': 'ไม่มีกิจกรรมใน 14 วันที่ผ่านมา',
  'noMetricsYetLabel': 'ยังไม่มีตัวชี้วัด',
  'flagForTeacherLabel': 'แจ้งให้ครูตรวจสอบ',
  'flagForTeacherDescription': 'บอกเราว่าอะไรดูไม่ถูกต้อง ครูจะตรวจสอบให้ — การเรียนของคุณดำเนินต่อได้ตามปกติ',
  'flagReasonHint': 'เช่น คำตอบที่ทำเครื่องหมายไว้ดูผิด',
  'sendLabel': 'ส่ง',
  'flagSentLabel': 'ส่งให้ครูตรวจสอบแล้ว ขอบคุณ!',
  'flagFailedLabel': 'ส่งการแจ้งไม่สำเร็จในขณะนี้',
  'flaggedLabel': 'ทำเครื่องหมายแล้ว',
  'looksWrongLabel': 'ดูผิดใช่ไหม?',
  'insightsUnavailableLabel': 'ไม่มีข้อมูลเชิงลึก',
  'insightsSummaryLabel': '{0} วิชา · {1} แนวคิด · {2} ครั้ง',
  'masteredCountLabel': 'เชี่ยวชาญ {0}/{1}',
  'masteredLabel': 'เชี่ยวชาญแล้ว',
  'attemptsPerDayLabel': 'ครั้งต่อวัน',
  'periodLabel': 'ช่วงเวลา:',
  'trendPeriodLabel.month': 'เดือน',
  'trendPeriodLabel.all': 'ทั้งหมด',
  'notEnoughHistoryLabel': 'ประวัติยังไม่เพียงพอ',
  'nothingAtRiskLabel': 'ไม่มีอะไรเสี่ยง — เยี่ยมมาก!',
  'atRiskDetailLabel': '{0} · ความเชี่ยวชาญ {1}{2}',
  'overdueSuffixLabel': ' · เกินกำหนด {0} วัน',
  'edgeAiSettingsTitle': 'การตั้งค่า AI ในเครื่อง',
  'edgeAiSettingsSubtitle': 'ติดตั้ง เริ่มต้น และทดสอบโมเดล LiteRT-LM ได้ในที่เดียว',
  'edgeAiHideModelUrlLabel': 'ซ่อน URL ของโมเดล',
  'edgeAiShowModelUrlLabel': 'เปลี่ยน URL ของโมเดล (ขั้นสูง)',
  'edgeAiModelUrlLabel': 'URL ของโมเดล (.litertlm)',
  'edgeAiInstallingLabel': 'กำลังติดตั้ง...',
  'edgeAiInstallModelLabel': 'ติดตั้งโมเดล',
  'edgeAiReinstallLabel': 'ติดตั้งใหม่',
  'edgeAiInitializingLabel': 'กำลังเริ่มต้น...',
  'edgeAiInitializeLabel': 'เริ่มต้น',
  'edgeAiUnloadLabel': 'ยกเลิกการโหลด',
  'edgeAiRunningLabel': 'กำลังทำงาน...',
  'edgeAiRunTestPromptLabel': 'รันพรอมต์ทดสอบ',
  'edgeAiDownloadLabel': 'ดาวน์โหลดโมเดล: {0}',
  'edgeAiDownloadedLabel': 'ดาวน์โหลดแล้ว {0}',
  'edgeAiEnterModelUrlLabel': 'กรุณากรอก URL ของโมเดลก่อน',
  'edgeAiModelAlreadyPresentLabel': 'มีโมเดลอยู่บนอุปกรณ์นี้แล้ว ({0})',
  'edgeAiModelReinstalledLabel': 'ติดตั้งโมเดลใหม่แล้ว ({0} ใน {1} มิลลิวินาที)',
  'edgeAiModelInstalledLabel': 'ติดตั้งโมเดลแล้ว ({0} ใน {1} มิลลิวินาที)',
  'edgeAiInstallFailedLabel': 'ติดตั้งโมเดลไม่สำเร็จ: {0}',
  'edgeAiUnloadedLabel': 'ยกเลิกการโหลดโมเดลออกจากหน่วยความจำรันไทม์แล้ว',
  'edgeAiUnloadFailedLabel': 'ยกเลิกการโหลดโมเดลไม่สำเร็จ: {0}',
  'edgeAiInitializeCorruptLabel': 'เริ่มต้นไม่สำเร็จ โดยทั่วไปไฟล์โมเดลเสียหายหรือไม่ตรงกับรันไทม์ของอุปกรณ์นี้ ลองติดตั้งใหม่แล้วเริ่มต้นอีกครั้ง',
  'edgeAiInitializeFailedLabel': 'เริ่มต้นไม่สำเร็จ: {0}',
  'edgeAiGenerationFailedLabel': 'การสร้างในเครื่องล้มเหลว: {0}',
  'edgeAiStatusUnavailable': 'ไม่พร้อมใช้งาน',
  'edgeAiModelNotReadyTitle': 'โมเดลในเครื่องยังไม่พร้อม',
  'edgeAiModelNotReadyMessage': 'โมเดล AI ในเครื่องยังไม่พร้อม กรุณาติดตั้งและเริ่มต้นก่อนทำแบบทดสอบก่อนเรียน',
  'edgeAiOpenSettingsLabel': 'เปิดการตั้งค่า AI ในเครื่อง',
  'edgeAiCheckingReadinessLabel': 'กำลังตรวจสอบความพร้อมของโมเดล AI ในเครื่อง...',
  'edgeAiPickTargetNodeLabel': 'เลือกโหนดเป้าหมายในเป้าหมายการเรียนรู้ก่อนเริ่มแบบทดสอบก่อนเรียน',
  'edgeAiFinishInstallLabel': 'โมเดลในเครื่องยังไม่พร้อม ทำการติดตั้ง/เริ่มต้นให้เสร็จ แล้วเริ่มแบบทดสอบก่อนเรียนอีกครั้ง',
  'edgeAiModelMissingTitle': 'ยังไม่ได้ติดตั้งโมเดล AI ในเครื่อง',
  'edgeAiModelMissingMessage': 'Wicara จะเสถียรขึ้นเมื่อดาวน์โหลดโมเดล LiteRT แล้ว เปิดการตั้งค่า AI ในเครื่องเลยไหม?',
  'edgeAiDownloadModelLabel': 'ดาวน์โหลดโมเดล',
  'edgeAiModelNotInitializedTitle': 'โมเดล AI ในเครื่องยังไม่พร้อม',
  'edgeAiModelNotInitializedMessage': 'มีโมเดลบนอุปกรณ์นี้แล้วแต่ยังไม่ได้เริ่มต้น เริ่มต้นเลยไหม?',
  'edgeAiOpenSettingsShortLabel': 'เปิดการตั้งค่า',
  'edgeAiInitializingModelLabel': 'กำลังเริ่มต้นโมเดลในเครื่อง...',
  'edgeAiModelReadyLabel': 'โมเดลในเครื่องพร้อมใช้งานแล้ว',
  'edgeAiInitializedNotReadyLabel': 'เริ่มต้นเสร็จแล้วแต่รันไทม์ยังไม่พร้อม ลองเปิดการตั้งค่า AI ในเครื่อง',
  'edgeAiTestPrompt': 'ตอบเป็นภาษาไทย อธิบายอนุพันธ์ในฐานะอัตราการเปลี่ยนแปลงใน 2 ประโยค แล้วให้คำถามตรวจสอบความเข้าใจ 1 ข้อ',
  'edgeAiInitializeModelFailedLabel': 'เริ่มต้นโมเดลไม่สำเร็จ: {0}',
  'tapToOpenLabel': 'แตะเพื่อเปิด',
  'resetZoomLabel': 'รีเซ็ตการซูม',
  'videoFailedToLoadLabel': 'โหลดวิดีโอไม่สำเร็จ ลองอีกครั้ง',
  'videoUrlMissingLabel': 'ไม่มี URL วิดีโอสำหรับอาร์ทิแฟกต์นี้',
  'videoLoadFailedLabel': 'โหลดวิดีโอนี้ไม่สำเร็จ',
  'openFullscreenLabel': 'เปิดเต็มหน้าจอ',
  'videoPreviewWebOnlyLabel': 'ดูตัวอย่างวิดีโอได้ในเวอร์ชันเดโมบนเว็บ',
  'penSizeLabel': 'ขนาดปากกา {0}',
  'penColorLabel': 'สีปากกา',
  'saveWorkLabel': 'บันทึกงาน',
  'sendToChatLabel': 'ส่งไปที่แชท',
  'canvasStatusLabel.draftEmpty': 'ฉบับร่างว่างเปล่า',
  'canvasStatusLabel.unsavedSketch': 'ภาพร่างที่ยังไม่บันทึก',
  'canvasStatusLabel.unsavedChanges': 'การเปลี่ยนแปลงที่ยังไม่บันทึก',
  'canvasStatusLabel.sentToChat': 'ส่งไปที่แชทแล้ว',
  'canvasStatusLabel.default': 'บันทึกแล้ว พร้อมส่ง',
  'canvasClearTitle': 'ล้างแคนวาสไหม?',
  'canvasClearMessage': 'การทำเช่นนี้จะลบภาพร่างปัจจุบันและโน้ตกระดาษที่แนบไว้',
  'canvasLabel': 'แคนวาส',
  'canvasWorkspaceLabel': 'พื้นที่ทำงานแคนวาส',
  'canvasLargeHint': 'ใช้พื้นที่ทำงานที่ใหญ่ขึ้นสำหรับแผนภาพและโน้ต',
  'canvasSmallHint': 'คิดหาเหตุผลให้เสร็จก่อนส่ง',
  'canvasClosePanelLabel': 'ปิดแผง',
  'canvasLargerPanelLabel': 'แผงที่ใหญ่ขึ้น',
  'canvasResetViewLabel': 'รีเซ็ตมุมมอง',
  'canvasHideGridLabel': 'ซ่อนเส้นตาราง',
  'canvasShowGridLabel': 'แสดงเส้นตาราง',
  'canvasClearLabel': 'ล้างแคนวาส',
  'canvasUploadImageLabel': 'อัปโหลดรูปภาพ',
  'canvasKeepLabel': 'เก็บไว้',
  'canvasClearShortLabel': 'ล้าง',
  'canvasViewSectionLabel': 'มุมมอง',
  'canvasEditSectionLabel': 'แก้ไข',
  'canvasZoomOutLabel': 'ซูมออก',
  'canvasZoomInLabel': 'ซูมเข้า',
  'canvasPenLabel': 'ปากกา',
  'canvasPenTooltip': 'โหมดปากกา',
  'canvasHandLabel': 'มือ',
  'canvasHandTooltip': 'โหมดมือ',
  'canvasEraseLabel': 'ลบ',
  'canvasEraseTooltip': 'โหมดยางลบ',
  'canvasShapeLabel': 'รูปทรง',
  'canvasShapeTooltip': 'ตัวช่วยวาดรูปทรง',
  'canvasLineShapeLabel': 'รูปทรงเส้นตรง',
  'canvasArrowShapeLabel': 'รูปทรงลูกศร',
  'canvasRectangleShapeLabel': 'รูปทรงสี่เหลี่ยมผืนผ้า',
  'canvasPaperAttachedLabel': 'แนบงานบนกระดาษ\nแล้ว',
  'canvasEmptyHintLabel': 'ร่างสูตร แผนภาพ หรือขั้นตอนการทำที่นี่',
  'preparingAdaptiveQuestionsLabel': 'กำลังเตรียมคำถามแบบปรับตัว...',
  'noLocalQuestionLabel': 'ตัวสร้างแบบทดสอบก่อนเรียนในเครื่องไม่ได้ส่งคำถามกลับมา',
  'chooseAnswerBeforeReasoningLabel': 'เลือกคำตอบก่อนเพิ่มวิธีทำของคุณ',
  'imageUnreadableLabel': 'อ่านไฟล์รูปภาพไม่ได้',
  'imageTooLargeLabel': 'รูปภาพต้องมีขนาดไม่เกิน 10 MB',
  'adaptiveProbingLabel': 'การตรวจสอบแบบปรับตัว  •  ทฤษฎีปริภูมิความรู้',
  'missingPrerequisiteSkillLabel': 'ขาดความรู้พื้นฐาน: ปัจจัยเชิงสาเหตุ',
  'missingPrerequisiteMessageLabel': 'ช่องว่างดูเหมือนการเลือกเครื่องมือก่อนที่จะระบุปัจจัยของข้อบกพร่อง หลักฐาน และห่วงโซ่สาเหตุที่เป็นไปได้',
  'improvedLabel': 'ดีขึ้น',
  'stagnantLabel': 'คงที่',
  'reviewDueConceptsLabel': 'ทบทวนแนวคิดที่ถึงกำหนด',
  'dueThisWeekLabel': 'ถึงกำหนดสัปดาห์นี้',
  'preVsPostTestLabel': 'ทดสอบก่อนเรียน vs หลังเรียน',
  'weeklyNarrativeLabel': 'เรื่องเล่ารายสัปดาห์',
  'focusLabel': 'โฟกัส',
  'answerScoredByAiLabel': 'คำตอบถูกให้คะแนนโดย AI',
  'scoringOffLabel': 'คะแนนไม่ตรงไหม?',
  'laterLabel': 'ภายหลัง',
  'trackWithoutModuleLabel': 'สร้างเส้นทางแล้ว แต่ยังไม่มีโมดูลพื้นที่ทำงาน',
  'workspaceAutoOpenFailedLabel': 'เปิดพื้นที่ทำงานอัตโนมัติหลังแบบทดสอบก่อนเรียนไม่สำเร็จ',
  'retentionLiftShortLabel': 'การเพิ่มการจดจำ',
  'remainingLabel': 'คงเหลือ',
  'weeklyReportLabel': 'รายงานประจำสัปดาห์',
  'retentionLabel': 'การจดจำ',
  'posttestMasteryCheckLabel': 'การตรวจสอบความเชี่ยวชาญหลังเรียน',
  'noSubjectsSelectedLabel': 'ยังไม่ได้เลือกวิชา',
  'thisWeekLabel': 'สัปดาห์นี้',
  'consistencyCompoundingLabel': 'ความสม่ำเสมอกำลังทบต้น',
  'serverTimeoutLabel': 'เซิร์ฟเวอร์ WICARA ตอบสนองช้าเกินไป กรุณาลองอีกครั้ง',
  'uploadTimeoutLabel': 'เซิร์ฟเวอร์ WICARA อัปโหลดรูปภาพช้าเกินไป กรุณาลองอีกครั้ง',
  'serverUnreachableLabel': 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ WICARA ที่ {0} ได้ {1}',
  'loginBeforeDashboardLabel': 'กรุณาเข้าสู่ระบบก่อนเปิดแดชบอร์ด',
  'loginBeforeOnboardingLabel': 'กรุณาเข้าสู่ระบบก่อนเริ่มการตั้งค่าเริ่มต้น',
  'loginBeforeWorkspaceLabel': 'กรุณาเข้าสู่ระบบก่อนเปิดพื้นที่ทำงาน',
  'loginBeforeTrackLabel': 'กรุณาเข้าสู่ระบบก่อนสร้างเส้นทาง',
  'noMatchingGoalLabel': 'ไม่พบเป้าหมายการเรียนรู้ที่ตรงกัน',
  'noImageAssetIdLabel': 'เซิร์ฟเวอร์ไม่ได้ส่ง id ของไฟล์รูปภาพกลับมา',
  'activeGoalConflictLabel': 'คุณมีเป้าหมายที่ใช้งานอยู่สำหรับ "{0}" แล้ว ',
  'signInFailedLabel': 'เข้าสู่ระบบไม่สำเร็จ: {0}',
  'registrationFailedLabel': 'ลงทะเบียนไม่สำเร็จ: {0}',
  'googleSignInFailedLabel': 'เข้าสู่ระบบด้วย Google ไม่สำเร็จ: {0}',
  'googleSignInCancelledLabel': 'ยกเลิกการเข้าสู่ระบบด้วย Google แล้ว',
  'createGoalBeforePretestLabel': 'สร้างเป้าหมายการเรียนรู้ก่อนเปิดแบบทดสอบก่อนเรียน',
  'invalidPretestQuestionLabel': 'แบ็กเอนด์ส่งคำถามแบบทดสอบก่อนเรียนที่ไม่ถูกต้องกลับมา',
  'chooseAnswerFirstLabel': 'เลือกคำตอบก่อนดำเนินการต่อ',
  'noNextQuestionLabel': 'แบ็กเอนด์ไม่ได้ส่งคำถามถัดไปหรือผลวินิจฉัยกลับมา',
  'invalidEvidenceImageLabel': 'แบ็กเอนด์ส่งรูปภาพหลักฐานที่ไม่ถูกต้องกลับมา',
  'createGoalBeforePathLabel': 'สร้างเป้าหมายการเรียนรู้ก่อนเลือกเส้นทาง',
  'loginBeforePretestLabel': 'กรุณาเข้าสู่ระบบก่อนทำแบบทดสอบก่อนเรียน',
  'openPretestBeforeSubmitLabel': 'เปิดแบบทดสอบก่อนเรียนที่สร้างไว้ก่อนส่ง',
  'pathSelectedLabel': 'เลือกเส้นทางแล้ว',
  'adaptivePathReadyLabel': 'เส้นทางการเรียนรู้แบบปรับตัวของคุณพร้อมแล้ว',
  'continueSelectedPathLabel': 'ดำเนินการต่อด้วยเส้นทางที่เลือก',
  'modulesCountLabel': '{0} โมดูล',
  'adaptiveDiagnosisLabel': 'การวินิจฉัยแบบปรับตัว',
  'adaptivePretestCompleteLabel': 'ทำแบบทดสอบก่อนเรียนแบบปรับตัวเสร็จแล้ว',
  'scoreMetaLabel': 'คะแนน {0}%',
  'correctCountMetaLabel': 'ถูก {0}/{1}',
  'pathDescriptionLabel.review_only': 'เริ่มด้วยการทบทวนสั้น ๆ และแบบฝึกหัดขั้นสูง',
  'pathDescriptionLabel.target_reinforcement': 'ฝึกแนวคิดเป้าหมายในระดับกลางและยาก',
  'pathDescriptionLabel.target_intro': 'เริ่มจากบทนำของแนวคิดเป้าหมาย',
  'pathDescriptionLabel.repair_prerequisites': 'แก้ช่องว่างความรู้พื้นฐานก่อนกลับไปยังเป้าหมาย',
  'pathDescriptionLabel.full_foundation_path': 'สร้างรากฐานที่ลึกกว่าขึ้นใหม่ก่อน',
  'pathDescriptionLabel.default': 'เรียนแนวคิดเป้าหมายตั้งแต่พื้นฐาน',
  'questionProgressLabel': 'คำถามที่ {0} จาก {1}',
  'conceptNotFoundLabel': 'ไม่พบแนวคิดในหลักสูตรในเครื่อง',
  'conceptCodeNotFoundLabel': 'ไม่พบแนวคิด "{0}" ในหลักสูตรในเครื่อง',
  'evidenceUploadNeedsBackendLabel': 'การอัปโหลดหลักฐานรูปภาพต้องใช้โหมดแบบทดสอบก่อนเรียนผ่านแบ็กเอนด์',
  'emptyPathOptionLabel': 'ตัวเลือกเส้นทางต้องไม่ว่างเปล่า',
  'localDiagnosisUnavailableLabel': 'ยังไม่มีผลวินิจฉัยในเครื่อง กรุณาทำแบบทดสอบก่อนเรียนให้เสร็จก่อน',
  'localPretestStateInvalidLabel': 'สถานะแบบทดสอบก่อนเรียนในเครื่องไม่ถูกต้อง',
  'localPretestSessionInvalidLabel': 'เซสชันแบบทดสอบก่อนเรียนในเครื่องไม่ถูกต้อง',
  'questionMismatchLabel': 'คำถามไม่ตรงกัน โหลดแบบทดสอบก่อนเรียนใหม่แล้วลองอีกครั้ง',
  'optionNotFoundLabel': 'ไม่พบตัวเลือกที่เลือกไว้สำหรับคำถามนี้',
  'offlineCurriculumMissingLabel': 'ไม่มีหลักสูตรออฟไลน์บนอุปกรณ์นี้',
  'targetConceptNotChosenLabel': 'ยังไม่ได้เลือกแนวคิดเป้าหมาย เปิดเป้าหมายการเรียนรู้แล้วเลือกโหนดเป้าหมายก่อน',
  'targetConceptNotFoundLabel': 'ไม่พบแนวคิดเป้าหมาย "{0}" ในหลักสูตรในเครื่อง',
  'backendPretestNotConfiguredLabel': 'ยังไม่ได้กำหนดค่าที่เก็บแบบทดสอบก่อนเรียนของแบ็กเอนด์',
  'chooseBestAnswerLabel': 'เลือกคำตอบที่ดีที่สุดสำหรับ {0}',
  'reviewWorkingStepsLabel': 'ตรวจทานขั้นตอนการทำของคุณเพื่อยืนยันคำตอบที่เลือก',
  'emptyTopicLabel': 'หัวข้อการเรียนรู้ต้องไม่ว่างเปล่า',
  'noMatchingConceptLabel': 'ยังไม่มีแนวคิดที่ตรงกัน ลองเพิ่มคำค้นที่เจาะจงขึ้น',
  'searchAllSubjectsLabel': 'ค้นหาในทุกวิชาในเครื่องแล้ว',
  'searchLimitedSubjectLabel': 'จำกัดการค้นหาเฉพาะวิชาที่เลือก',
  'resolutionNotFoundLabel': 'ไม่พบผลการระบุ ค้นหาโหนดเป้าหมายอีกครั้ง',
  'resolutionMissingLabel': 'ไม่พบผลการระบุ',
  'noTargetNodeLabel': 'ยังไม่ได้เลือกโหนดเป้าหมายสำหรับแบบทดสอบก่อนเรียน',
  'noMatchingConceptRetryLabel': 'ไม่พบแนวคิดที่ตรงกัน ลองค้นด้วยคำอื่น',
  'localCurriculumMissingLabel': 'ยังไม่มีหลักสูตรในเครื่อง กรุณาซิงก์หลักสูตรก่อน',
  'localNodeNotFoundLabel': 'ไม่พบโหนด "{0}" ในหลักสูตรในเครื่อง',
  'targetConceptFallbackTitle': 'แนวคิดเป้าหมาย',
  'tutorHintDerivativeLabel': 'คำใบ้: ดูว่าค่าของฟังก์ชันเปลี่ยนอย่างไรเมื่อ x ขยับเล็กน้อย แล้วเปรียบเทียบจุดสองจุดที่ใกล้กันมาก',
  'tutorHintGenericLabel': 'คำใบ้: แบ่งปัญหาเป็นสามขั้นตอนย่อย ตรวจสอบสมมติฐานในแต่ละขั้น แล้วทำทีละขั้น',
  'tutorEvaluateCloseLabel': 'ขั้นตอนของคุณใกล้เคียงแล้ว ตอนนี้อธิบายว่าทำไมกฎนั้นจึงใช้กับโจทย์รูปแบบนี้',
  'tutorEvaluateInconsistentLabel': 'คำตอบของคุณยังไม่สอดคล้องกัน ตรวจสอบขั้นตอนแรกอีกครั้ง แล้วเขียนเหตุผลของการแปลงแต่ละขั้นใหม่',
  'reasoningTooShortLabel': 'การให้เหตุผลของคุณยังสั้นเกินไป เพิ่มเหตุผลที่เลือกใช้การดำเนินการนั้น',
  'reasoningClearLabel': 'การให้เหตุผลของคุณชัดเจนเชิงโครงสร้างแล้ว ตอนนี้สนับสนุนด้วยตัวอย่างเชิงตัวเลขสั้น ๆ หนึ่งตัวอย่าง',
  'quizPromptLabel': "ลองทำดู: ถ้า f(x)=x^2 อนุพันธ์ f'(x) คืออะไร และเพราะอะไร?",
  'summaryFallbackLabel': 'สรุปสั้น ๆ: โฟกัสที่แนวคิดหลัก กฎสำคัญหนึ่งข้อ และข้อผิดพลาดที่พบบ่อยหนึ่งอย่างที่ควรเลี่ยง',
  'explainDerivativeLabel': 'อนุพันธ์อธิบายว่าค่าของฟังก์ชันเปลี่ยนเร็วแค่ไหนเทียบกับ x ลองนึกภาพเป็นความชันของเส้นสัมผัส ณ จุดหนึ่งบนเส้นโค้ง',
  'explainGenericLabel': 'เราเริ่มจากนิยามหลัก ต่อด้วยตัวอย่างสั้น ๆ แล้วตรวจสอบกลับด้วยคำถามยืนยันความเข้าใจ',
  'heuristicReasoningFeedback': 'การให้เหตุผลถูกประเมินด้วยฮิวริสติกในเครื่อง เนื่องจากการประเมินด้วย LiteRT ไม่พร้อมใช้งาน',
  'carelessMistakeFeedback': 'ข้อปรนัยตอบผิด แต่มีสัญญาณการให้เหตุผลบางส่วนที่ค่อนข้างชัด',
  'partialReasoningFeedback': 'ให้เหตุผลได้บางส่วน แต่ยังไม่พอที่จะสนับสนุนคำตอบ',
  'unrelatedReasoningFeedback': 'การให้เหตุผลยังไม่เกี่ยวข้องโดยตรงกับแนวคิดหลัก',
  'diagnosisSummaryLabel.review_only': 'คุณพร้อมแล้วในเรื่อง {0} ทบทวนสั้น ๆ ก็เพียงพอ',
  'diagnosisSummaryLabel.target_reinforcement': 'คุณเข้าใจพื้นฐานของ {0} แล้ว แต่ต้องฝึกที่ยากขึ้น',
  'diagnosisSummaryLabel.target_from_basics': '{0} เริ่มก่อตัวแล้ว แต่ยังไม่มั่นคงในระดับกลาง',
  'diagnosisSummaryLabel.target_intro': '{0} ยังเป็นช่องว่างหลัก เริ่มจากบทนำของแนวคิด',
  'diagnosisSummaryLabel.repair_prerequisites': 'ความรู้พื้นฐานบางอย่างของ {0} ต้องเสริมให้แน่นก่อน',
  'diagnosisSummaryLabel.full_foundation_path': 'รากฐานก่อน {0} ต้องสร้างใหม่จากความรู้พื้นฐานที่ลึกที่สุด',
  'diagnosisSummaryLabel.default': 'การวินิจฉัยสำหรับ {0} เสร็จสมบูรณ์แล้ว',
  'diagnosisFocusLabels.review_only.0': 'สรุปแนวคิดเป้าหมายอีกครั้ง',
  'diagnosisFocusLabels.review_only.1': 'ทำแบบฝึกเสริมเบา ๆ 1-2 ข้อ',
  'diagnosisFocusLabels.target_reinforcement.0': 'ฝึกระดับกลางถึงยากในเป้าหมาย',
  'diagnosisFocusLabels.target_reinforcement.1': 'ปรับปรุงคุณภาพการเขียนให้เหตุผล',
  'diagnosisFocusLabels.target_from_basics.0': 'ทบทวนพื้นฐานก่อนถึงเป้าหมาย',
  'diagnosisFocusLabels.target_from_basics.1': 'ฝึกทีละขั้นจากง่ายไปปานกลาง',
  'diagnosisFocusLabels.target_intro.0': 'เริ่มจากบทนำของแนวคิดเป้าหมาย',
  'diagnosisFocusLabels.target_intro.1': 'ใช้ตัวอย่างรูปธรรมก่อนสัญลักษณ์',
  'diagnosisFocusLabels.repair_prerequisites.0': 'เสริมโหนดความรู้พื้นฐานที่อ่อนหรือขาดหาย',
  'diagnosisFocusLabels.repair_prerequisites.1': 'กลับไปยังเป้าหมายเมื่อความรู้พื้นฐานมั่นคงแล้ว',
  'diagnosisFocusLabels.full_foundation_path.0': 'สร้างใหม่จากความรู้พื้นฐานที่ลึกที่สุด',
  'diagnosisFocusLabels.full_foundation_path.1': 'ไต่ขึ้นทีละขั้นตามความลึกของกราฟ',
  'offlineWritingNotesLabel': 'AI กำลังเขียนโน้ตส่วนตัวของคุณ...',
  'offlineSessionNotFoundLabel': 'ไม่พบเซสชันแบบทดสอบก่อนเรียน',
  'offlineInvalidStateLabel': 'สถานะแบบทดสอบก่อนเรียนไม่ถูกต้อง',
  'offlineNotesReadyLabel': 'โน้ต AI ส่วนตัวของคุณพร้อมแล้ว',
  'offlineNotesFailedLabel': 'AI ไม่สามารถเขียนโน้ตส่วนตัวสำหรับเซสชันนี้ได้',
  'offlineRuntimeNotReadyLabel': 'โมเดล LiteRT ยังไม่พร้อมหรือยังไม่ได้ติดตั้ง กำลังใช้ตัวสำรองในเครื่อง',
  'offlineGeneratingAttemptLabel': 'กำลังสร้างคำถามในเครื่อง (ครั้งที่ {0}/{1} หมดเวลาใน {2} วินาที)...',
  'offlineOutputInvalidLabel': 'ผลลัพธ์ของโมเดลยังไม่ถูกต้อง กำลังลองใหม่ ({0}/{1})',
  'offlineValidLevelsLabel': 'โมเดลสร้างระดับที่ถูกต้องได้ {0} ระดับ ({1})',
  'offlineAttemptTimeoutLabel': 'ความพยายามครั้งที่ {0} หมดเวลา ({1}วิ) กำลังลองใหม่...',
  'offlineAttemptFailedLabel': 'ความพยายามครั้งที่ {0} ล้มเหลว: {1} จะดำเนินการลองใหม่ครั้งถัดไป',
  'offlineGenerationDoneLabel': 'สร้างคำถามเสร็จแล้ว',
  'offlineGenerationPartialLabel': 'คำถามบางข้อถูกต้อง ข้ามไป: {0}',
  'offlineGenerationFailedLabel': 'สร้างคำถามไม่สำเร็จ กำลังใช้เทมเพลตสำรอง',
  'offlineGenerationFallbackLabel': 'สร้างคำถามในเครื่องไม่สำเร็จ กำลังใช้เทมเพลตสำรอง',
  'offlinePreparingModelLabel': 'กำลังเตรียมโมเดลในเครื่อง...',
  'devModeLabel': 'โหมดนักพัฒนา',
  'devBypassTitle': 'การข้ามสำหรับนักพัฒนา',
  'devBypassSubtitle': 'ข้ามการยืนยันตัวตนจริงในบิลด์ดีบัก',
  'devOnboardingIncompleteLabel': 'เข้าสู่ระบบแล้ว แต่ยังตั้งค่าเริ่มต้นไม่เสร็จ',
  'startAtOnboardingLabel': 'เริ่มที่การตั้งค่าเริ่มต้น',
  'jumpToHomeLabel': 'ไปที่หน้าแรกเลย',
  'devSignedInLabel': 'เข้าสู่ระบบและทำเครื่องหมายว่าตั้งค่าเริ่มต้นเสร็จแล้ว',
  'demoLimitsFromGraphsTitle': 'ลิมิตจากกราฟ',
  'demoLimitsFromGraphsReason': 'ทำไมต้องตอนนี้? เพราะจะปลดล็อกความต่อเนื่องและ\nสัญชาตญาณเรื่องอนุพันธ์อันดับหนึ่ง',
  'demoDerivativeRulesTitle': 'กฎการหาอนุพันธ์',
  'demoFunctionCompositionTitle': 'ทบทวนการประกอบฟังก์ชัน',
  'demoContinueCalculusTitle': 'เรียนแคลคูลัส I ต่อ',
  'demoContinueCalculusSubtitle': 'ลิมิต อนุพันธ์ การประยุกต์',
  'demoLinearAlgebraTitle': 'พีชคณิตเชิงเส้น',
  'demoLinearAlgebraSubtitle': 'เวกเตอร์ เมทริกซ์ การแปลง',
  'demoDiscreteMathTitle': 'คณิตศาสตร์ไม่ต่อเนื่อง',
  'demoDiscreteMathSubtitle': 'ตรรกศาสตร์ เซต กราฟ การนับ',
  'demoDerivativesIntuitionTitle': 'สัญชาตญาณเรื่องอนุพันธ์',
  'demoDerivativesIntuitionSubtitle': 'อนุพันธ์บอกอะไรเรา?',
  'demoLimitsFromGraphsSubtitle': 'เข้าใกล้ค่าหนึ่งโดยไม่แตะค่านั้น',
  'demoCalculusOneLabel': 'แคลคูลัส I',
  'demoCalculusLabel': 'แคลคูลัส',
  'demoDerivativeRulesReason': 'ทำไมต้องตอนนี้? คุณพร้อมแล้วหลังเรียนลิมิตและ\nการตีความความชัน',
  'demoFunctionCompositionReason': 'ทำไมต้องตอนนี้? จำเป็นก่อนเรียนกฎลูกโซ่และ\nการหาอนุพันธ์โดยปริยาย',
  'demoLessonMetaLabel': '{0} นาที   •   {1}',
  'reviewNowShortLabel': 'ทบทวน',
  'demoCurrentTrackMeta': 'เส้นทางปัจจุบัน   •   เสร็จ {0}%',
  'demoCreatedTrackMeta': 'เส้นทางที่สร้างไว้   •   เสร็จ {0}%',
  'demoCreatedTrackReadyMeta': 'เส้นทางที่สร้างไว้   •   พร้อมเรียนต่อ',
  'gradeValue': 'ชั้น {0}',
  'subjectLabel.Math': 'คณิตศาสตร์',
  'subjectLabel.Matematika': 'คณิตศาสตร์',
  'subjectLabel.Physics': 'ฟิสิกส์',
  'subjectLabel.Fisika': 'ฟิสิกส์',
  'subjectLabel.Chemistry': 'เคมี',
  'subjectLabel.Kimia': 'เคมี',
  'subjectLabel.Biology': 'ชีววิทยา',
  'subjectLabel.Biologi': 'ชีววิทยา',
  'subjectLabel.Science': 'วิทยาศาสตร์',
  'subjectLabel.IPA': 'วิทยาศาสตร์',
  'subjectLabel.IPAS': 'วิทยาศาสตร์',
  'subjectDescription.Math': 'พีชคณิต เรขาคณิต แคลคูลัส',
  'subjectDescription.Physics': 'กลศาสตร์ คลื่น อุณหพลศาสตร์',
  'subjectDescription.Chemistry': 'ปริมาณสัมพันธ์ ปฏิกิริยา',
  'subjectDescription.Biology': 'เซลล์ พันธุศาสตร์ นิเวศวิทยา',
  'difficultyLabel.easy': 'ง่าย',
  'difficultyLabel.medium': 'ปานกลาง',
  'difficultyLabel.hard': 'ยาก',
  'estimatedDurationLabel': 'ประมาณ {0}   •   {1}',
  'layerLabel': 'ชั้นที่ {0}',
  'nodeStatusLabel.MASTERED': 'เชี่ยวชาญ',
  'nodeStatusLabel.REVIEW': 'ทบทวน',
  'nodeStatusLabel.READY': 'พร้อม',
  'nodeStatusLabel.GAP': 'ช่องว่าง',
  'nodeStatusLabel.LOCKED': 'ล็อก',
  'weekShortLabels': 'อา|จ|อ|พ|พฤ|ศ|ส',
  'diagnosisPromptInstructions': '\nWrite a diagnosis of the learner\'s pretest in Thai (ภาษาไทย). Not a summary, not encouragement - a DIAGNOSIS.\nEvery field of the JSON output must be written in Thai (ภาษาไทย).\nUse ONLY the data in "nodes" below.\nTone: casual, addressed directly to the learner ("You ..."), no jargon.\nIf siswa_pakai_canvas=true, mention that the learner wrote or sketched while working (an effort signal).\n\nRules for each field:\n- "summary" (2-3 sentences, roughly 80-120 words):\n  name the specific target concept + 1 thing already understood (cite a correct question) + 1 thing still missing (cite a wrong question).\n  Avoid motivational lines.\n- "strengths" (1-3 points, each 1-2 full sentences):\n  format: "On the question about [core of the question], you [correct step]."\n  Cite reasoning_siswa whenever it is available.\n- "gaps" (1-3 points, each 2-3 full sentences):\n  format: "On the question about [core of the question], you chose [siswa_pilih] when the answer was [jawaban_benar]. [Contrast reasoning_siswa with expected_reasoning or explain the error]."\n- "evidence_notes" (0-2 points):\n  describe concrete cross-question patterns (e.g. empty reasoning on hard questions, canvas effort appearing, etc).\n- "recommended_focus" (1-3 points):\n  concrete practice that directly fixes the gap (name the sub-topic, not "practice more").\n\nFORBIDDEN: generic lines ("needs more practice", "the concept is weak").\nAlways reference the actual question content from the data.',
  'offlineQuestionPromptInstructions': '\nWrite short adaptive pretest questions in Thai (ภาษาไทย).\nEvery question, option, and explanation must be written in Thai (ภาษาไทย).\nOnly output these difficulty keys: {0}.\nEvery question must have 4 unique options and exactly 1 correct answer.\nAvoid long explanations. Keep it concise.\nThe "explanation" field MUST be concrete numbered steps (e.g. "1) ... 2) ... 3) ..."),\nnot a general definition of the concept.',
  'diagnosisSystemPrompt': "You are WICARA's on-device pretest diagnostic writer. Write a specific narrative in Thai (ภาษาไทย), grounded in the given questions and the learner's answers, not generalities. Output valid JSON only.",
  'knowledgeGraph.Mathematics Prerequisite Map': 'แผนที่ความรู้พื้นฐานคณิตศาสตร์',
  'knowledgeGraph.Knowledge Map': 'แผนที่ความรู้',
  'knowledgeGraph.Primary Math': 'คณิตศาสตร์ประถมศึกษา',
  'knowledgeGraph.Lower Secondary': 'มัธยมศึกษาตอนต้น',
  'knowledgeGraph.Algebra and Functions': 'พีชคณิตและฟังก์ชัน',
  'knowledgeGraph.Precalculus': 'พรีแคลคูลัส',
  'knowledgeGraph.Limits and Continuity': 'ลิมิตและความต่อเนื่อง',
  'knowledgeGraph.Calculus 1': 'แคลคูลัส 1',
  'knowledgeGraph.Calculus 2': 'แคลคูลัส 2',
  'knowledgeGraph.Calculus 3': 'แคลคูลัส 3',
  'knowledgeGraph.Counting': 'การนับ',
  'knowledgeGraph.Place Value': 'ค่าประจำหลัก',
  'knowledgeGraph.Arithmetic Operations': 'การดำเนินการทางคณิตศาสตร์',
  'knowledgeGraph.Fractions and Decimals': 'เศษส่วนและทศนิยม',
  'knowledgeGraph.Basic Shapes and Measurement': 'รูปทรงพื้นฐานและการวัด',
  'knowledgeGraph.Tables, Charts, and Mean': 'ตาราง แผนภูมิ และค่าเฉลี่ย',
  'knowledgeGraph.Integers and Rational Numbers': 'จำนวนเต็มและจำนวนตรรกยะ',
  'knowledgeGraph.Exponents and Roots Basics': 'พื้นฐานเลขยกกำลังและราก',
  'knowledgeGraph.Linear Equations': 'สมการเชิงเส้น',
  'knowledgeGraph.Coordinate Graphing': 'การเขียนกราฟบนระบบพิกัด',
  'knowledgeGraph.Slope and Intercepts': 'ความชันและจุดตัดแกน',
  'knowledgeGraph.Pythagorean Theorem': 'ทฤษฎีบทพีทาโกรัส',
  'knowledgeGraph.Functions, Domain, and Range': 'ฟังก์ชัน โดเมน และเรนจ์',
  'knowledgeGraph.Function Composition and Inverses': 'การประกอบฟังก์ชันและฟังก์ชันผกผัน',
  'knowledgeGraph.Exponential and Logarithmic Functions': 'ฟังก์ชันเลขชี้กำลังและลอการิทึม',
  'knowledgeGraph.Quadratic and Polynomial Functions': 'ฟังก์ชันกำลังสองและพหุนาม',
  'knowledgeGraph.Rational Functions': 'ฟังก์ชันตรรกยะ',
  'knowledgeGraph.Sequences, Series, Sigma Notation': 'ลำดับ อนุกรม สัญกรณ์ซิกมา',
  'knowledgeGraph.Analytic Geometry and Conics': 'เรขาคณิตวิเคราะห์และภาคตัดกรวย',
  'knowledgeGraph.Trigonometric Functions and Graphs': 'ฟังก์ชันตรีโกณมิติและกราฟ',
  'knowledgeGraph.Trigonometric Identities and Equations': 'เอกลักษณ์และสมการตรีโกณมิติ',
  'knowledgeGraph.Vectors, Parametric, and Polar Basics': 'พื้นฐานเวกเตอร์ พาราเมตริก และเชิงขั้ว',
  'knowledgeGraph.Precalculus Fluency': 'ความคล่องแคล่วพรีแคลคูลัส',
  'knowledgeGraph.Intuitive Limits': 'ลิมิตเชิงสัญชาตญาณ',
  'knowledgeGraph.Limit Laws and Algebraic Techniques': 'กฎของลิมิตและเทคนิคเชิงพีชคณิต',
  'knowledgeGraph.Trigonometric Limits and Squeeze Theorem': 'ลิมิตตรีโกณมิติและทฤษฎีบทแซนด์วิช',
  'knowledgeGraph.Continuity and Intermediate Value Theorem': 'ความต่อเนื่องและทฤษฎีบทค่าระหว่างกลาง',
  'knowledgeGraph.Derivative Definition': 'นิยามของอนุพันธ์',
  'knowledgeGraph.Derivative Rules': 'กฎการหาอนุพันธ์',
  'knowledgeGraph.Chain Rule and Implicit Differentiation': 'กฎลูกโซ่และการหาอนุพันธ์โดยปริยาย',
  'knowledgeGraph.Related Rates, Optimization, Curve Sketching': 'อัตราสัมพัทธ์ การหาค่าเหมาะที่สุด การร่างเส้นโค้ง',
  'knowledgeGraph.Antiderivatives, Riemann Sums, Definite Integrals': 'ปฏิยานุพันธ์ ผลรวมรีมันน์ ปริพันธ์จำกัดเขต',
  'knowledgeGraph.Fundamental Theorem of Calculus': 'ทฤษฎีบทมูลฐานของแคลคูลัส',
  'knowledgeGraph.Integration Techniques': 'เทคนิคการหาปริพันธ์',
  'knowledgeGraph.Area, Volume, Work, Fluid Force': 'พื้นที่ ปริมาตร งาน แรงของไหล',
  'knowledgeGraph.Convergence Tests and Power Series': 'การทดสอบการลู่เข้าและอนุกรมกำลัง',
  'knowledgeGraph.Parametric and Polar Calculus': 'แคลคูลัสพาราเมตริกและเชิงขั้ว',
  'knowledgeGraph.3D Coordinates and Vector Operations': 'พิกัดสามมิติและการดำเนินการเวกเตอร์',
  'knowledgeGraph.Partial Derivatives and Gradients': 'อนุพันธ์ย่อยและเกรเดียนต์',
  'knowledgeGraph.Double and Triple Integrals': 'ปริพันธ์สองชั้นและสามชั้น',
  'knowledgeGraph.Vector Fields, Line Integrals, Green, Stokes, Divergence': 'สนามเวกเตอร์ ปริพันธ์ตามเส้น กรีน สโตกส์ ไดเวอร์เจนซ์',
  'workspace.topicTitle': 'หัวข้อการเรียนรู้',
  'workspace.startChatTitle': 'เริ่มเรียน',
  'workspace.startChatBody': 'ติวเตอร์จะนำทางคุณจากผลวินิจฉัยและเฟสการเรียนที่จัดเก็บไว้ในแบ็กเอนด์',
  'workspace.startChatButtonLabel': 'เริ่มแชทเพื่อเรียน',
  'workspace.loadingDescription': 'กำลังเชื่อมโมดูลนี้กับบริบทการเรียนในแบ็กเอนด์',
  'workspace.syncedDescription': 'บทสนทนา แคนวาส สื่อ และสถานะเฟส ถูกซิงก์กับแบ็กเอนด์',
  'workspace.workspaceTitleLabel': 'พื้นที่ทำงาน',
  'workspace.newChatLabel': 'แชทใหม่',
  'workspace.chatHistoryTitle': 'ประวัติแชท',
  'workspace.advancePhaseLabel': 'ไปเฟสถัดไป',
  'workspace.advancingPhaseLabel': 'กำลังไปเฟสถัดไป...',
  'workspace.phaseTransitionHint': "แตะ 'ไปเฟสถัดไป' เมื่อคุณพร้อม",
  'workspace.startPosttestButtonLabel': 'เริ่มแบบทดสอบหลังเรียน',
  'workspace.posttestReadyBody': 'เริ่มแบบทดสอบหลังเรียนตอนนี้ไหม? การทำเช่นนี้จะปิดโมดูลพื้นที่ทำงานและเตรียมเซสชันแบบทดสอบหลังเรียน',
  'workspace.cancelLabel': 'ยกเลิก',
  'workspace.startPosttestDialogLabel': 'เริ่มแบบทดสอบหลังเรียน',
  'workspace.posttestUnavailableMessage': 'แบบทดสอบหลังเรียนยังไม่พร้อม ทำต่อตามคำแนะนำของติวเตอร์',
  'workspace.workspaceNotReadyMessage': 'พื้นที่ทำงานยังไม่พร้อม',
  'workspace.openTrackModuleMessage': 'เปิดโมดูลเส้นทางจากหน้าแรกหรือคิวก่อนใช้พื้นที่ทำงาน',
  'workspace.chatLoadingMessage': 'เซสชันแชทกำลังโหลดอยู่',
  'workspace.connectingWorkspaceMessage': 'กำลังเชื่อมต่อพื้นที่ทำงานแบ็กเอนด์...',
  'workspace.savingEvidenceMessage': 'กำลังบันทึกหลักฐานในพื้นที่ทำงาน...',
  'workspace.queueingVideoMessage': 'กำลังจัดคิวสร้างวิดีโอ...',
  'workspace.videoQueuedMessage': 'วิดีโออยู่ในคิวแล้ว กำลังรอ worker...',
  'workspace.videoTimedOutMessage': 'การสร้างวิดีโอหมดเวลาหลังจาก {0} นาที',
  'workspace.generationTimeoutMessage': 'หมดเวลาการสร้าง',
  'workspace.buildingScenesMessage': 'กำลังสร้างฉาก คำบรรยาย และเรนเดอร์...',
  'workspace.generatingVideoTitle': 'กำลังสร้างวิดีโอ',
  'workspace.generatedVideoFallbackTitle': 'วิดีโอที่สร้างขึ้น',
  'workspace.savedGeneratedVideoTitle': 'วิดีโอที่บันทึกไว้',
  'workspace.generatedVideoSubtitle': 'เรนเดอร์วิดีโอเสร็จแล้วและพร้อมในพื้นที่ทำงานของคุณ',
  'workspace.aiVideoChip': 'วิดีโอ AI',
  'workspace.readyUrlChip': 'URL พร้อมแล้ว',
  'workspace.playGeneratedVideoLabel': 'เล่นวิดีโอ',
  'workspace.videoUrlUnavailableLabel': 'URL วิดีโอไม่พร้อมใช้งาน',
  'workspace.videoGenerationFailedTitle': 'สร้างวิดีโอไม่สำเร็จ',
  'workspace.videoGenerationFailedMessage': 'สร้างวิดีโอไม่สำเร็จ',
  'workspace.retryGenerateVideoLabel': 'ลองสร้างวิดีโออีกครั้ง',
  'workspace.generatingVideoButtonLabel': 'กำลังสร้างวิดีโอ...',
  'workspace.generateVideoFromChatLabel': 'สร้างวิดีโอจากแชทนี้',
  'workspace.generatingVideoContextMessage': 'กำลังสร้างวิดีโอจากบริบทบทสนทนาล่าสุดของคุณ...',
  'workspace.videoReadyMessage': 'วิดีโอพร้อมแล้ว คุณเล่นได้จากการ์ดแชทล่าสุด',
  'workspace.failedToLoadVideoMessage': 'โหลดวิดีโอจาก URL แบ็กเอนด์ไม่สำเร็จ',
  'workspace.openFullscreenTooltip': 'เปิดเต็มหน้าจอ',
  'workspace.durationChipLabel': 'ความยาว {0}',
  'workspace.canvasAttachedPrompt': 'แนบงานบนแคนวาสแล้ว เพิ่มภาพร่างอื่นได้หากต้องการ',
  'workspace.canvasPrompt': 'ต้องการกระดานไวท์บอร์ดไหม? เปิดแคนวาสแล้วส่งภาพร่างของคุณที่นี่',
  'workspace.openCanvasLabel': 'เปิดแคนวาส',
  'workspace.useCanvasLabel': 'ใช้แคนวาส',
  'workspace.canvasSentLabel': 'ส่งแคนวาสแล้ว',
  'workspace.explanationCardLabel': 'การ์ดคำอธิบาย',
  'workspace.evidenceRequestLabel': 'หลักฐานที่ขอ',
  'workspace.nextActionsLabel': 'การดำเนินการถัดไป',
  'workspace.canvasSnapshotSentLabel': 'ส่งสแนปชอตแคนวาสแล้ว',
  'workspace.canvasSnapshotSentCountLabel': 'ส่งสแนปชอตแคนวาสแล้ว ({0} รอย)',
  'workspace.canvasMarksLabel': '{0} รอย',
  'workspace.canvasMarksAttachedLabel': '{0} รอย - แนบกระดาษแล้ว',
  'workspace.historyButtonLabel': 'ประวัติ ({0})',
  'workspace.historyMessageCountLabel': '{0} ข้อความ',
  'workspace.workspaceSyncFailedMessage': 'ซิงก์พื้นที่ทำงานไม่สำเร็จ: {0}',
  'workspace.imageSentLabel': 'ส่งรูปภาพแล้ว',
  'workspace.videoRequestedNote': 'มีการขอวิดีโอที่นี่',
  'workspace.canvasUploadFailedMessage': 'อัปโหลดรูปแคนวาสไม่สำเร็จ ติวเตอร์ได้รับเฉพาะข้อความ: {0}',
  'workspace.resumingVideoMessage': 'กำลังเชื่อมกลับไปยังการเรนเดอร์ที่กำลังทำงาน...',
  'workspace.resumeVideoLabel': 'เชื่อมต่ออีกครั้ง',
  'workspace.tutorOfflineTitle': 'ติวเตอร์ AI ไม่พร้อมใช้งาน',
  'workspace.tutorOfflineBody': 'คำตอบด้านล่างใช้ข้อความสำรอง เฟสของคุณจะยังไม่เดินหน้าจนกว่าติวเตอร์จะกลับมา ลองอีกครั้งในไม่ช้า',
  'workspace.feedbackCorrectLabel': 'ถูกต้อง',
  'workspace.feedbackPartialLabel': 'เกือบถูก',
  'workspace.feedbackIncorrectLabel': 'ยังไม่ถูก',
  'workspace.misconceptionLabel': 'พบความเข้าใจคลาดเคลื่อน',
  'workspace.masteryDeltaUpLabel': 'ความเชี่ยวชาญ +{0}%',
  'workspace.masteryDeltaDownLabel': 'ความเชี่ยวชาญ -{0}%',
  'workspace.masteryDeltaFlatLabel': 'ความเชี่ยวชาญไม่เปลี่ยนแปลง',
  'workspace.hintLevelLabel': 'ระดับคำใบ้ {0}',
  'workspace.whyThisModuleLabel': 'ทำไมต้องโมดูลนี้?',
  'workspace.deleteSessionLabel': 'ลบเซสชัน',
  'workspace.deleteSessionConfirmBody': 'เซสชันแชทนี้จะถูกลบถาวร ดำเนินการต่อไหม?',
  'loadingPosttestLabel': 'กำลังโหลดแบบทดสอบหลังเรียน',
  'preparingAdaptivePosttestFromBackendLabel': 'กำลังเตรียมแบบทดสอบหลังเรียนแบบปรับตัวจากแบ็กเอนด์',
  'posttestUnavailableLabel': 'แบบทดสอบหลังเรียนไม่พร้อมใช้งาน',
  'backendReturnedNoPosttestQuestionsLabel': 'แบ็กเอนด์ไม่ได้ส่งคำถามแบบทดสอบหลังเรียนกลับมา',
  'tryAgainLabel2': 'ลองอีกครั้ง',
  'questionsMediumHardBasedWhatLabel': 'คำถาม 10 ข้อ: ปานกลาง 3 ข้อ และยาก 7 ข้อ อิงจากสิ่งที่คุณได้เรียน',
  'continueLabel2': 'ดำเนินการต่อ',
  'finishPosttestLabel': 'ทำแบบทดสอบหลังเรียนให้เสร็จ',
  'loadingDailyEvalsLabel': 'กำลังโหลดการประเมินประจำวัน',
  'fetchingSpacedReviewQuestionsFromLabel': 'กำลังดึงคำถามทบทวนแบบเว้นระยะจากแบ็กเอนด์',
  'dailyEvalsUnavailableLabel': 'การประเมินประจำวันไม่พร้อมใช้งาน',
  'backendReturnedNoReviewQuestionsLabel': 'แบ็กเอนด์ไม่ได้ส่งคำถามทบทวนกลับมา',
  'dashboardUnavailableLabel': 'แดชบอร์ดไม่พร้อมใช้งาน',
  'retryLabel2': 'ลองใหม่',
  'loadingDashboardLabel': 'กำลังโหลดแดชบอร์ด',
  'fetchingProfileFromBackendLabel': 'กำลังดึงโปรไฟล์ของคุณจากแบ็กเอนด์',
  'elementarySchoolLabel': 'ประถมศึกษา',
  'juniorHighSchoolLabel': 'มัธยมศึกษาตอนต้น',
  'seniorHighSchoolLabel': 'มัธยมศึกษาตอนปลาย',
  'universityLabel': 'มหาวิทยาลัย',
  'pretestProgressLabel': 'แบบทดสอบก่อนเรียนกำลังดำเนินอยู่',
  'submittedAnswersSavedContinueFromLabel': 'คำตอบที่คุณส่งถูกบันทึกไว้แล้ว ทำต่อจากคำถามล่าสุดของคุณ',
  'continuePretestLabel': 'ทำแบบทดสอบก่อนเรียนต่อ',
  'createLearningGoalLabel': 'สร้างเป้าหมายการเรียนรู้',
  'createLearningGoalSoWicaraLabel': 'สร้างเป้าหมายการเรียนรู้เพื่อให้ WICARA เตรียมเส้นทางและพื้นที่ทำงานให้',
  'pickGoalSubjectBeforeOpeningLabel': 'เลือกเป้าหมายในวิชานี้ก่อนเปิดพื้นที่ทำงาน',
  'nextModuleLabel': 'โมดูลถัดไป',
  'progressLabel2': 'กำลังดำเนินการ',
  'readyLabel': 'พร้อม',
  'completedLabel': 'เสร็จสิ้นแล้ว',
  'pausedLabel': 'หยุดชั่วคราว',
  'needsReviewLabel2': 'ต้องทบทวน',
  'activeLabel': 'ใช้งานอยู่',
  'noModuleReadyYetLabel': 'ยังไม่มีโมดูลที่พร้อม',
  'goalDoesNotHaveActiveLabel': 'เป้าหมายนี้ยังไม่มีโมดูลที่ใช้งานอยู่',
  'createChooseAnotherGoalStartLabel': 'สร้างหรือเลือกเป้าหมายอื่นเพื่อเริ่มเรียน',
  'noGeneratedVideosReadyYetLabel': 'ยังไม่มีวิดีโอที่สร้างเสร็จ',
  'videosFromBackendJobsSavedLabel': 'วิดีโอจากงานฝั่งแบ็กเอนด์จะถูกบันทึกไว้ที่นี่',
  'noDailyEvaluationAssignedYetLabel': 'ยังไม่มีการประเมินประจำวันที่ได้รับมอบหมาย',
  'noEvaluationLabel': 'ไม่มีการประเมิน',
  'answerConfidenceLevelLabel': 'ระดับความมั่นใจในคำตอบ',
  'howConfidentAnswerLabel': 'คุณมั่นใจในคำตอบของคุณแค่ไหน?',
  'chooseNotConfidentVeryConfidentLabel': 'เลือก 0 (ไม่มั่นใจ) ถึง 10 (มั่นใจมาก)',
  'masteryConfirmedLabel': 'ยืนยันความเชี่ยวชาญแล้ว',
  'reviewNeededFromPosttestResultsLabel': 'ต้องทบทวนตามผลแบบทดสอบหลังเรียน',
  'posttestResultsLabel': 'ผลแบบทดสอบหลังเรียน',
  'scoreSummaryLearningProgressionDecisionLabel': 'สรุปคะแนนและการตัดสินความก้าวหน้าการเรียนมาจากแบ็กเอนด์',
  'correctnessLabel': 'ความถูกต้อง',
  'correctLabel2': 'ถูกต้อง',
  'decisionLabel': 'การตัดสิน',
  'trackProgressLabel': 'ความก้าวหน้าของเส้นทาง',
  'continueLearningLabel2': 'เรียนต่อ',
  'reviewWeakAreasLabel': 'ทบทวนจุดที่ยังอ่อน',
  'moduleCompleteNextModuleNowLabel': 'โมดูลนี้เสร็จสมบูรณ์แล้ว และโมดูลถัดไปพร้อมใช้งานแล้ว',
  'learningGoalCompleteLabel': 'เป้าหมายการเรียนรู้นี้เสร็จสมบูรณ์แล้ว',
  'backendConfirmedModuleAsPassedLabel': 'แบ็กเอนด์ยืนยันว่าโมดูลนี้ผ่านแล้ว รีเฟรชหน้าแรกเพื่อดูขั้นถัดไปของเส้นทาง',
  'backendRequiresReviewRemainingWeakLabel': 'แบ็กเอนด์กำหนดให้ทบทวนจุดอ่อนที่เหลือก่อนลองใหม่',
  'conceptResultsLabel': 'ผลลัพธ์รายแนวคิด',
  'noPosttestNodesHaveBeenLabel': 'ยังไม่มีโหนดแบบทดสอบหลังเรียนที่ถูกประเมิน',
  'scoreLabel2': 'คะแนน',
  'profileUpdatedLabel': 'อัปเดตโปรไฟล์แล้ว',
  'localAiLitertLmLabel': 'AI ในเครื่อง (LiteRT-LM)',
  'installInitializeModelLabel': 'ติดตั้งและเริ่มต้นโมเดล',
  'reportUnavailableLabel': 'รายงานไม่พร้อมใช้งาน',
  'openDetailsLabel': 'เปิดรายละเอียด',
  'loadingWeekLabel': 'กำลังโหลดสัปดาห์นี้',
  'syncingLabel': 'กำลังซิงก์',
  'fetchingReportDataFromBackendLabel': 'กำลังดึงข้อมูลรายงานจากแบ็กเอนด์',
  'noDataYetLabel': 'ยังไม่มีข้อมูล',
  'startLabel': 'เริ่ม',
  'takeDailyEvaluationsFirstPopulateLabel': 'ทำการประเมินประจำวันก่อนเพื่อให้แผนภูมินี้มีข้อมูล',
  'weekTrendLabel': 'แนวโน้ม 4 สัปดาห์',
  'ptsLabel': 'คะแนน',
  'averageAccuracyLabel': 'ความถูกต้องเฉลี่ย',
  'scoresLabel': 'คะแนน',
  'preTestPostTestChangeLabel': 'ก่อนเรียน หลังเรียน และการเปลี่ยนแปลง แสดงการขยับของคะแนนเฉลี่ย',
  'preTestLabel2': 'ก่อนเรียน',
  'postTestLabel2': 'หลังเรียน',
  'changeLabel': 'การเปลี่ยนแปลง',
  'learningReportUnavailableLabel': 'รายงานการเรียนไม่พร้อมใช้งาน',
  'loadingLearningReportLabel': 'กำลังโหลดรายงานการเรียน',
  'fetchingWeeklyProgressSummaryLabel': 'กำลังดึงสรุปความก้าวหน้ารายสัปดาห์',
  'weekSummaryLabel': 'สรุปสัปดาห์นี้',
  'answerAccuracyLabel': 'ความถูกต้องของคำตอบ',
  'fixedGapsLabel2': 'ช่องว่างที่แก้ไขแล้ว',
  'remainingGapsLabel2': 'ช่องว่างที่เหลือ',
  'answerAccuracyPercentageCorrectAnswersLabel': 'ความถูกต้องของคำตอบ = เปอร์เซ็นต์ของคำตอบที่ถูกในช่วงวันที่เลือก',
  'weekProgressLabel': 'ความก้าวหน้า 4 สัปดาห์',
  'trackAccuracyAttemptVolumeGapLabel': 'ติดตามความถูกต้อง จำนวนครั้งที่ทำ และการขยับของช่องว่างในแต่ละสัปดาห์',
  'effortVsImpactLabel': 'ความพยายามเทียบกับผลลัพธ์',
  'attemptsLabel': 'จำนวนครั้ง',
  'activeDaysLabel': 'วันที่ใช้งาน',
  'impactLabel': 'ผลลัพธ์',
  'strongConceptsVsNeedsImprovementLabel': 'แนวคิดที่แข็งแรง เทียบกับ ที่ต้องปรับปรุง',
  'focusConceptsBiggestLiftOnesLabel': 'โฟกัสที่แนวคิดที่พัฒนามากที่สุดและแนวคิดที่ยังเสี่ยง',
  'numberRightShowsConceptMasteryLabel': 'ตัวเลขทางขวาแสดงการเปลี่ยนแปลงความเชี่ยวชาญของแนวคิด (%) ในช่วงนี้',
  'nowStrongLabel': 'ตอนนี้แข็งแรงแล้ว',
  'noConceptsShowedSignificantImprovementLabel': 'ไม่มีแนวคิดใดพัฒนาขึ้นอย่างมีนัยสำคัญในสัปดาห์นี้',
  'needsImprovementLabel': 'ต้องปรับปรุง',
  'noRiskConceptsRangeLabel': 'ไม่มีแนวคิดที่เสี่ยงในช่วงนี้',
  'weekLabel2': 'สัปดาห์นี้',
  'lastWeekLabel': 'สัปดาห์ที่แล้ว',
  'lastWeeksLabel': '4 สัปดาห์ที่ผ่านมา',
  'averageScoreLabel': 'คะแนนเฉลี่ย',
  'notEnoughMatchedPreTestLabel': 'ยังมีข้อมูลก่อนเรียนและหลังเรียนที่จับคู่กันไม่เพียงพอ',
  'reportRequestTimedOutPleaseLabel': 'คำขอรายงานหมดเวลา กรุณาลองอีกครั้ง',
  'reportCouldNotLoadedPleaseLabel': 'โหลดรายงานไม่สำเร็จ กรุณาลองอีกครั้ง',
  'completeDataLabel': 'ข้อมูลครบถ้วน',
  'partialDataLabel': 'ข้อมูลบางส่วน',
  'earlyDataLabel': 'ข้อมูลช่วงต้น',
  'highLeverageLabel': 'ให้ผลสูง',
  'steadyLabel': 'คงที่',
  'needsFocusLabel': 'ต้องโฟกัส',
  'noSignalLabel': 'ไม่มีสัญญาณ',
  'reportBuiltFromSufficientlyCompleteLabel': 'รายงานนี้สร้างจากประวัติที่ครบถ้วนเพียงพอ',
  'dataExistsButComparisonHistoryLabel': 'มีข้อมูลอยู่ แต่ประวัติสำหรับเปรียบเทียบยังไม่ครบ',
  'dataStillThinSoSomeLabel': 'ข้อมูลยังน้อย ข้อมูลเชิงลึกบางส่วนจึงเป็นการประมาณเบื้องต้น',
  'dataQualityStatusNotDefinedLabel': 'ยังไม่ได้กำหนดสถานะคุณภาพข้อมูล',
  'overallLabel2': 'โดยรวม',
  'applicationLabel2': 'การประยุกต์ใช้',
  'analysisLabel2': 'การวิเคราะห์',
  'weekLabel3': '0 สัปดาห์นี้',
  'learningPerformanceLabel': 'ผลการเรียนรู้',
  'noAssessmentAttemptsRangeYetLabel': 'ยังไม่มีการทำแบบประเมินในช่วงนี้ ทำการประเมินประจำวันเพื่อสร้างกราฟนี้',
  'useAsLearningGoalLabel': 'ใช้สิ่งนี้เป็นเป้าหมายการเรียนรู้ของคุณไหม?',
  'chooseAnotherNodeLabel': 'เลือกโหนดอื่น',
  'startPretestLabel': 'เริ่มแบบทดสอบก่อนเรียน',
  'activeGoalFoundLabel': 'พบเป้าหมายที่ใช้งานอยู่',
  'backLabel2': 'ย้อนกลับ',
  'continueExistingGoalLabel': 'ทำเป้าหมายเดิมต่อ',
  'useAsNewGoalLabel': 'ใช้เป็นเป้าหมายใหม่',
  'visualizePrerequisitesGapsNextConceptsLabel': 'แสดงภาพความรู้พื้นฐาน ช่องว่าง และแนวคิดถัดไป',
  'alreadyHaveActiveGoalNodeLabel': 'คุณมีเป้าหมายที่ใช้งานอยู่สำหรับโหนดนี้แล้ว:',
  'canContinueGoalGoBackLabel': 'คุณสามารถทำเป้าหมายนี้ต่อ หรือย้อนกลับไปเลือกโหนดใหม่',
  'findLearningGoalNodeLabel': 'ค้นหาโหนดเป้าหมายการเรียนรู้',
  'searchAgainLabel': 'ค้นหาอีกครั้ง',
  'searchAgainNewQueryLabel': 'ค้นหาอีกครั้งด้วยคำค้นใหม่',
  'sureWantTakeLabel': 'คุณแน่ใจหรือไม่ว่าต้องการเลือกสิ่งนี้?',
  'nodeDetailLabel': 'รายละเอียดโหนด',
  'descriptionLabel': 'คำอธิบาย',
  'subjectLabel2': 'วิชา',
  'matchLabel': 'ความตรงกัน',
  'seeGraphLabel': 'ดูกราฟ',
  'lockLabel': 'ล็อก',
  'findLearningGoalFirstLabel': 'ค้นหาเป้าหมายการเรียนรู้ก่อน',
  'typeGoalThenWicaraWillLabel': 'พิมพ์เป้าหมายของคุณ แล้ว WICARA จะจับคู่กับโหนดเนื้อหา แบบทดสอบก่อนเรียนจะเริ่มหลังจากคุณยืนยันโหนดแล้วเท่านั้น',
  'nodeNotCertainLabel': 'โหนดยังไม่แน่ชัด',
  'tryAddingGradeSubjectMoreLabel': 'ลองเพิ่มระดับชั้น วิชา หรือหัวข้อที่เจาะจงขึ้น',
  'pickClosestCandidateLabel': 'เลือกตัวเลือกที่ใกล้เคียงที่สุด',
  'recommendedNodeLabel': 'โหนดที่แนะนำ',
  'otherPossibleNodesLabel': 'โหนดอื่นที่เป็นไปได้',
  'editPromptLabel': 'แก้ไขพรอมต์',
  'viewDetailLabel': 'ดูรายละเอียด',
  'descriptionNotFoundLabel': 'ไม่พบคำอธิบาย',
  'nodeBelowGradeLevelCanLabel': 'โหนดนี้ต่ำกว่าระดับชั้นของคุณ ช่วยเสริมพื้นฐานได้',
  'nodeAboveGradeLevelMayLabel': 'โหนดนี้สูงกว่าระดับชั้นของคุณ อาจรู้สึกท้าทายกว่า',
  'nodeFitsGradeLevelLabel': 'โหนดนี้เหมาะกับระดับชั้นของคุณ',
  'mathLabel': 'คณิตศาสตร์',
  'physicsLabel': 'ฟิสิกส์',
  'chemistryLabel': 'เคมี',
  'biologyLabel': 'ชีววิทยา',
  'uploadingWorkImageLabel': 'กำลังอัปโหลดรูปงานของคุณ...',
  'answerSentEvaluatingWorkPreparingLabel': 'ส่งคำตอบแล้ว กำลังประเมินงานของคุณและเตรียมคำถามถัดไป...',
  'submitAnswerLabel': 'ส่งคำตอบ',
  'addReasoningSketchLabel': 'เพิ่มการให้เหตุผล / ภาพร่าง',
  'hideWorkEvidenceLabel': 'ซ่อนหลักฐานการทำงาน',
  'workEvidenceLabel': 'หลักฐานการทำงาน',
  'typeStepsUploadPhotoWorkLabel': 'พิมพ์ขั้นตอนของคุณ อัปโหลดรูปงานของคุณ หรือใช้ทั้งสองอย่าง AI จะอ่านรูปเป็นขั้นตอนการแก้โจทย์',
  'writeSolutionStepsLabel': 'เขียนขั้นตอนการแก้โจทย์ของคุณ...',
  'uploadWorkImageLabel': 'อัปโหลดรูปงาน',
  'removeImageLabel': 'ลบรูปภาพ',
  'submitAnswerEvidenceLabel': 'ส่งคำตอบพร้อมหลักฐาน',
  'correctLabel3': 'ถูก',
  'noAnswersLabel': 'ไม่มีคำตอบ',
  'officialMcqScoreLabel': 'คะแนนปรนัยอย่างเป็นทางการ',
  'reportLabel': 'รายงาน',
  'whatLooksStrongLabel': 'จุดที่ดูแข็งแรง',
  'whatNeedsWorkLabel': 'จุดที่ต้องปรับปรุง',
  'evidenceNotesLabel': 'บันทึกหลักฐาน',
  'checkedNodesLabel': 'โหนดที่ตรวจแล้ว',
  'levelLabel': 'ระดับ',
  'nextPathFocusLabel': 'โฟกัสเส้นทางถัดไป',
  'reasoningSuggestsMisconceptionNodeLabel': 'การให้เหตุผลบ่งชี้ความเข้าใจคลาดเคลื่อนที่โหนดนี้',
  'therePossibleCarelessChoiceDespiteLabel': 'อาจเป็นการเลือกด้วยความไม่รอบคอบ แม้การให้เหตุผลจะสมเหตุสมผล',
  'evidenceWasStoredButNoLabel': 'บันทึกหลักฐานแล้ว แต่ไม่มีขั้นตอนที่เขียนไว้ให้วิเคราะห์',
  'noSubjectGoalsYetLabel': 'ยังไม่มีเป้าหมาย{0}',
  'subjectGoalsLabel': 'เป้าหมาย{0}',
  'percentCompleteLabel': 'เสร็จ {0}%',
  'moduleStatusLabel': 'สถานะโมดูล: {0}',
  'moduleStatusWithMinutesLabel': '{0} นาที - สถานะโมดูล: {1}',
  'sessionReturnsToPhaseLabel': 'เซสชันกลับไปยังเฟส {0} เพื่อแก้ไข{1}',
  'targetPassedLabel': 'ถูก {0}/{1} เป้าหมายนี้ผ่าน',
  'conceptMarkedForReviewLabel': 'ถูก {0}/{1} แบ็กเอนด์ทำเครื่องหมายให้ทบทวนแนวคิดนี้',
  'accuracyPercentLabel': 'ความถูกต้อง {0}%',
  'fixedGapsDeltaLabel': '+{0} สัปดาห์นี้',
  'remainingGapsDeltaLabel': '{0} สัปดาห์นี้',
  'weeklyPointSummaryLabel': '{0} ครั้ง • แก้ช่องว่างแล้ว {1} • เหลือ {2}',
  'positiveDeltaThisWeekLabel': '+{0} สัปดาห์นี้',
  'deltaThisWeekLabel': '{0} สัปดาห์นี้',
  'activeGoalConflictBodyLabel': 'คุณมีเป้าหมายที่ใช้งานอยู่สำหรับ "{0}" แล้ว คุณจะทำเป้าหมายนั้นต่อ หรือย้อนกลับไปเลือกโหนดใหม่ก็ได้',
  'reasoningQualityLabel': 'คุณภาพการให้เหตุผล: {0}{1}',
  'learnConceptInGraphLabel': 'เรียนรู้ {0} ในกราฟความรู้พื้นฐาน',
  'outputValidJsonOnlyLabel': 'ส่งออกเฉพาะ JSON ที่ถูกต้อง:',
  'workspace.collapseLabel': 'ย่อ',
  'workspace.detailsLabel': 'รายละเอียด',
  'workspace.finalTargetLabel': 'เป้าหมายสุดท้าย: {0}',
  'workspace.phaseTransitionReadyLabel': 'พร้อมเปลี่ยนเฟส',
  'workspace.continueThisPhaseLabel': 'เรียนต่อในเฟสนี้',
};
