/// Bahasa Melayu translations for `OnboardingCopy`.
///
/// Keys match member names (`member.case` for switch arms). Templated members
/// use `{0}`, `{1}` … placeholders; list members join items with `|`.
/// Missing keys fall back to English.
///
/// Authored without native-speaker review — proofread before release.
library;

const copyMs = <String, String>{
  'letsSetYouUpTitle': 'Mari kita sediakan akaun anda',
  'letsSetYouUpSubtitle':
      'Ceritakan sedikit tentang diri anda untuk\nmemperibadikan pembelajaran anda.',
  'fullNameLabel': 'Nama penuh',
  'countryLabel': 'Negara',
  'gradeLevelLabel': 'Tahap darjah',
  'preferredLanguageLabel': 'Bahasa pilihan',
  'continueLabel': 'Teruskan',
  'improveExperienceNote':
      'Kami akan terus menambah baik pengalaman ini\nkhas untuk anda.',
  'chooseSubjectsTitle': 'Pilih mata pelajaran anda',
  'chooseSubjectsSubtitle':
      'Pilih mata pelajaran yang ingin anda pelajari.\nAnda boleh mengubahnya bila-bila masa.',
  'customizeLaterNote': 'Anda boleh menyesuaikan lagi kemudian.',
  'preferencesTitle': 'Bagaimana anda mahu belajar?',
  'preferencesSubtitle':
      'Pilih keutamaan anda. Anda boleh mengubahnya\nbila-bila masa.',
  'studyGoalLabel': 'Matlamat pembelajaran',
  'dailyStudyTimeLabel': 'Masa belajar harian',
  'adaptivePretestLabel': 'Teruskan ke praujian adaptif',
  'personalizePathNote':
      'Ini membantu kami memperibadikan laluan pembelajaran anda.',
  'preferenceCallout':
      'WICARA menyesuaikan diri dengan anda, rentak anda,\ngaya anda, dan matlamat anda.',
  'profileTitle': 'Profil',
  'profileSubtitle': 'Urus keutamaan pembelajaran dan akaun anda.',
  'homeLabel': 'Utama',
  'learnLabel': 'Belajar',
  'progressLabel': 'Kemajuan',
  'learningSetupTitle': 'Tetapan pembelajaran',
  'preferencesSectionTitle': 'Keutamaan',
  'subjectsLabel': 'Mata pelajaran',
  'logoutLabel': 'Log keluar',
  'welcomeBack': 'Selamat kembali,\n',
  'homeSubtitle':
      'Bersedia untuk terus belajar dan membina sesuatu yang hebat hari ini?',
  'languageLabel': 'Bahasa',
  'getStartedLabel': 'Mula',
  'alreadyHaveAccountLabel': 'Saya sudah mempunyai akaun',
  'signInTitle': 'Selamat kembali',
  'signInSubtitle': 'Log masuk untuk meneruskan pembelajaran anda',
  'registerTitle': 'Cipta akaun anda',
  'registerSubtitle':
      'Daftar sekali, kemudian teruskan laluan pembelajaran anda',
  'emailOrPhoneLabel': 'E-mel atau nombor telefon',
  'emailOrPhoneHint': 'Masukkan e-mel atau nombor telefon anda',
  'emailLabel': 'E-mel',
  'emailHint': 'Masukkan e-mel anda',
  'passwordLabel': 'Kata laluan',
  'passwordHint': 'Masukkan kata laluan anda',
  'fullNameHint': 'Masukkan nama penuh anda',
  'forgotPasswordLabel': 'Lupa kata laluan?',
  'signInLabel': 'Log masuk',
  'registerLabel': 'Daftar',
  'logInLabel': 'Log masuk',
  'orContinueWithLabel': 'atau teruskan dengan',
  'securityNoteLabel': 'Data anda peribadi dan selamat.',
  'cancelLabel': 'Batal',
  'applyLabel': 'Guna',
  'searchLabel': 'Cari',
  'recommendedLabel': 'Disyorkan',
  'tracksLabel': 'Trek',
  'galleryLabel': 'Galeri',
  'viewAllLabel': 'Lihat semua',
  'nextUpLabel': 'Seterusnya',
  'exploreLabel': 'Terokai',
  'currentStreakLabel': 'Rentetan semasa',
  'backToHomeLabel': 'Kembali ke Utama',
  'continueLearningLabel': 'Teruskan Belajar',
  'learningGoalTitle': 'Apa yang anda ingin pelajari?',
  'learningGoalSubtitle':
      'Taip matlamat anda dahulu. WICARA akan mencari nod bahan yang sepadan, kemudian praujian bermula selepas anda mengesahkannya.',
  'learningTopicLabel': 'Topik pembelajaran',
  'generatePretestLabel': 'Jana Praujian',
  'typeATopicHint': 'Taip satu topik',
  'loadingPretestLabel': 'Memuatkan praujian',
  'pretestUnavailableLabel': 'Praujian tidak tersedia',
  'tryAgainLabel': 'Cuba lagi',
  'preTestLabel': 'Praujian',
  'postTestLabel': 'Pascaujian',
  'refreshLabel': 'Muat semula',
  'retryLabel': 'Cuba lagi',
  'backLabel': 'Kembali',
  'undoLabel': 'Buat asal',
  'redoLabel': 'Buat semula',
  'teacherReviewLabel': 'Semakan guru',
  'insightsLabel': 'Cerapan',
  'knowledgeMapLabel': 'Peta Pengetahuan',
  'learningReportLabel': 'Laporan Pembelajaran',
  'reviewNowLabel': 'Semak sekarang',
  'reviewDueLabel': 'Semakan tertunggak',
  'studyGoalOptionalLabel': 'Matlamat belajar (pilihan)',
  'dailyStudyTimeOptionalLabel': 'Masa belajar harian (pilihan)',
  'learnSubtitleRecommended': 'Trek yang dicadangkan untuk membantu anda mencapai matlamat.',
  'learnSubtitleTracks': 'Terokai trek pembelajaran anda atau cipta yang baharu di sini.',
  'learnSubtitleGallery': 'Semak semula video dan ringkasan daripada perjalanan pembelajaran anda.',
  'todaysLearningQueueLabel': 'Baris gilir pembelajaran hari ini',
  'continueSessionLabel': 'Teruskan sesi',
  'wantToLearnSomethingNewLabel': 'Mahu belajar sesuatu yang baharu?',
  'exploreTracksDescription': 'Terokai trek yang anda cipta atau mulakan yang lain.',
  'streakDaysLabel': '{0} hari',
  'dailyEvaluationLabel': 'Penilaian harian',
  'dailyEvaluationPrompt': '. Pilih skor keyakinan jika mahu, kemudian buat semakan harian anda.',
  'takeDailyEvaluationLabel': 'Buat Penilaian Harian',
  'dailyEvalsWordmark': 'Penilaian Harian',
  'dailyEvalsQuickCheckin': 'Semakan pantas untuk laluan pembelajaran hari ini.',
  'finishDailyEvalsLabel': 'Selesaikan Penilaian Harian',
  'dailyQuestionProgressLabel': '{0} daripada {1}',
  'reviewDueSummaryLabel': '{0} item sedia untuk disemak',
  'retentionForecastLabel': 'Ramalan ingatan anda',
  'retentionForecastBasisLabel': 'Berdasarkan MVP keluk lupa Ebbinghaus.',
  'retentionCoachingLabel': 'Teruskan mengulang kaji untuk menaikkan keluk dan meningkatkan ingatan jangka panjang.',
  'evaluationCompleteLabel': 'Penilaian Selesai 🎉',
  'evaluationCompleteSubtitle': 'Syabas! Anda sedang membina pengetahuan yang kekal.',
  'reviewedLabel': 'Telah disemak',
  'toReviewAgainLabel': 'Perlu disemak semula',
  'scoreLabel': 'Skor',
  'reviewedConceptsLabel': 'Konsep yang disemak',
  'noReviewedConceptsLabel': 'Belum ada konsep yang disemak',
  'continueLearningReason': 'Pergi ke laluan pembelajaran anda.',
  'statusGoodLabel': 'Baik',
  'statusStrongLabel': 'Kukuh',
  'statusReviewLabel': 'Semak',
  'retentionLiftLabel': 'Peningkatan Ingatan',
  'daysUntilNextReviewLabel': 'Hari Sehingga Semakan Seterusnya',
  'learnSomethingNewLabel': 'Belajar sesuatu yang baharu',
  'newTrackDescription': 'Cipta trek baharu di luar senarai semasa anda.',
  'newTrackLabel': 'Trek baharu',
  'progressSubtitle': 'Mulakan dengan laporan pembelajaran anda, kemudian terokai peta pengetahuan.',
  'learningReportDescription': 'Prestasi mingguan, jurang yang dibaiki, konsep yang dibuka.',
  'fixedGapsLabel': 'Jurang yang dibaiki',
  'remainingGapsLabel': 'Jurang yang tinggal',
  'thisWeekFixedDelta': '+4 minggu ini',
  'thisWeekRemainingDelta': '-2 minggu ini',
  'learningReportHint': 'Tuding atau ketik sesuatu minggu untuk pratonton pertumbuhan, jurang yang dibaiki, dan peningkatan ingatan.',
  'retentionDeltaLabel': '+{0}% ingatan',
  'weekLabel': 'M{0}',
  'knowledgeMapDescription': 'Terokai domain mata pelajaran dan laluan prasyarat.',
  'fallbackGraphLabel': 'Graf sandaran statik',
  'liveCurriculumGraphLabel': 'Graf pengetahuan langsung',
  'nodeCountLabel': '{0} nod',
  'masteryConfidenceLabel': 'Keyakinan penguasaan',
  'aboutThisConceptLabel': 'Tentang konsep ini',
  'relatedConceptsLabel': 'Konsep berkaitan',
  'noDirectRelatedConceptLabel': 'Tiada konsep berkaitan secara langsung',
  'crossSubjectConnectionsLabel': 'Sambungan merentas mata pelajaran',
  'graphOfGraphsHint': 'Pautan Graph of Graphs kelihatan apabila tersedia.',
  'conceptBridgeFallbackLabel': 'Jambatan konsep',
  'conceptFallbackDescription': 'Konsep dalam graf prasyarat.',
  'confidenceQuestionLabel': 'Sejauh mana keyakinan anda?',
  'yourKnowledgeStateLabel': 'Keadaan pengetahuan anda',
  'personalizedPathGeneratedLabel': 'Laluan peribadi dijana',
  'personalizedPathDescription': 'Mulakan dengan prasyarat, kemudian latih soalan punca utama.',
  'continueToMyPathLabel': 'Teruskan ke laluan saya',
  'missingPrerequisiteGapsLabel': 'Jurang prasyarat yang hilang',
  'learnerLabel': 'Pelajar',
  'statusLabel': 'Status',
  'couldNotLoadQueueLabel': 'Tidak dapat memuatkan baris gilir',
  'nothingToReviewLabel': 'Tiada apa-apa untuk disemak',
  'reviewItemLabel': 'Item semakan',
  'flaggedForReviewLabel': 'Ditanda untuk semakan.',
  'learningGoalDiagnosisLabel': 'Diagnosis matlamat pembelajaran',
  'learnerAskedLabel': 'Pelajar bertanya',
  'subjectSingularLabel': 'Mata pelajaran',
  'suggestedConceptIdLabel': 'Id konsep yang dicadangkan',
  'confidenceLabel': 'Keyakinan',
  'reasoningEvaluationLabel': 'Penilaian penaakulan',
  'learnerReasoningLabel': 'Penaakulan pelajar',
  'answerScoreLabel': 'Skor jawapan',
  'reasoningScoreLabel': 'Skor penaakulan',
  'evidenceScoreLabel': 'Skor bukti',
  'overrideConceptIdLabel': 'Gantikan id konsep prasyarat yang didiagnosis. Pengesahan menetapkan status diagnosis kepada "disahkan".',
  'correctedOfReviewedLabel': '{0} dibetulkan daripada {1} yang disemak',
  'noReviewedItemsLabel': 'Belum ada item yang disemak.',
  'reviewedCountLabel': '{0} disemak',
  'darkCorrectedLightReviewedLabel': 'Gelap = dibetulkan · cerah = disemak',
  'reviewArtifactLabel.question': 'Soalan',
  'reviewArtifactLabel.diagnosis': 'Diagnosis',
  'reviewArtifactLabel.evaluation': 'Penilaian',
  'reviewArtifactLabel.open': 'Terbuka',
  'reviewArtifactLabel.approved': 'Diluluskan',
  'reviewArtifactLabel.rejected': 'Ditolak',
  'reviewArtifactLabel.corrected': 'Dibetulkan',
  'reviewArtifactLabel.all': 'Semua',
  'reviewArtifactLabel.low_confidence': 'Keyakinan rendah',
  'reviewArtifactLabel.risk_signal': 'Isyarat risiko',
  'reviewArtifactLabel.sampled': 'Disampel',
  'reviewArtifactLabel.learner_flag': 'Tanda pelajar',
  'overallMasteryLabel': 'Penguasaan keseluruhan',
  'streakSummaryLabel': '🔥 rentetan {0} hari · terbaik {1} · {2} hari aktif',
  'masteryBySubjectLabel': 'Penguasaan mengikut mata pelajaran',
  'noSubjectDataLabel': 'Belum ada data mata pelajaran.',
  'streakDaysShortLabel': '{0}h',
  'scoreTrendLabel': 'Aliran skor',
  'needsReviewLabel': 'Perlu semakan ({0})',
  'edgeAiStatusReadFailedLabel': 'Gagal membaca status runtime edge: {0}',
  'edgeAiStatusChecking': 'memeriksa',
  'edgeAiStatusUnknown': 'tidak diketahui',
  'edgeAiStatusReady': 'sedia',
  'edgeAiStatusNeedsInit': 'perlu-mula',
  'edgeAiStatusNeedsInstall': 'perlu-pasang',
  'todaysTopicLabel': 'Topik hari ini: ',
  'notConfidentLabel': 'Tidak yakin',
  'veryConfidentLabel': 'Sangat yakin',
  'nextQuestionLabel': 'Soalan seterusnya',
  'highImpactLabel': 'Impak tinggi',
  'maintainedLabel': 'Dikekalkan',
  'correctLabel': 'Betul',
  'pendingLabel': 'Menunggu',
  'recommendedNextActionsLabel': 'Tindakan seterusnya yang disyorkan',
  'spacedRepetitionImpactLabel': 'Kesan ulangan berjarak',
  'memoryStrengthenedLabel': 'Anda telah mengukuhkan ingatan anda.',
  'contentGalleryLabel': 'Galeri Kandungan',
  'contentGalleryDescription': 'Semua video yang dijana sebelum ini ada di sini, sedia dimainkan semula bersama nota yang disusun WICARA untuk anda.',
  'notesLabel': 'Nota',
  'cheatsheetSummaryLabel': 'Ringkasan lembaran rujukan',
  'recommendedForCurrentReadinessLabel': 'Disyorkan untuk Kalkulus I berdasarkan\njurang dan kesediaan semasa anda.',
  'fixedShortLabel': '+4 dibaiki',
  'overallLabel': 'Keseluruhan',
  'applicationLabel': 'Aplikasi',
  'analysisLabel': 'Analisis',
  'completeLabel': 'Selesai',
  'skillGrowthLabel': 'Pertumbuhan kemahiran',
  'remainingCountLabel': '{0} lagi',
  'loadingCurriculumLabel': 'Memuatkan kurikulum daripada backend...',
  'prerequisiteLayerLabel': 'Lapisan prasyarat',
  'combinedLayerLabel': '{0} + {1} lagi',
  'prerequisitesLabel': 'Prasyarat',
  'noDirectPrerequisiteLabel': 'Tiada prasyarat langsung',
  'relatedBadgeLabel': 'BERKAITAN',
  'bypassForWebDevLabel': 'Pintasan untuk pembangunan web',
  'passwordResetMockedMessage': 'Set semula kata laluan masih tiruan buat masa ini.',
  'emailRequiredMessage': 'Masukkan e-mel anda',
  'fullNameRequiredMessage': 'Masukkan nama penuh anda',
  'registrationEmailValidationMessage': 'Gunakan alamat e-mel untuk pendaftaran',
  'passwordMinLengthMessage': 'Kata laluan mesti sekurang-kurangnya 6 aksara',
  'adaptivePretestReadyNextLabel': 'Praujian adaptif sedia seterusnya',
  'adaptivePretestReadyDescription': 'Beberapa soalan akan menentukur titik permulaan anda.',
  'pretestGeneratedCompleteLabel': 'Praujian selesai dijana!',
  'openingAdaptivePretestLabel': 'Membuka praujian adaptif anda sekarang.',
  'lowLabel': 'Rendah',
  'highLabel': 'Tinggi',
  'basedOnYourResponsesLabel': 'Berdasarkan jawapan anda.',
  'whatsNextLabel': 'Apa seterusnya',
  'retakePretestAnytimeLabel': 'Anda boleh mengambil semula praujian bila-bila masa.',
  'currentTopicLabel': 'Topik semasa',
  'askOrReflectHereHint': 'Tanya atau renungkan di sini...',
  'speechReadAloud': 'Baca dengan kuat',
  'speechReadAloudHint': 'Baca kandungan ini menggunakan pertuturan',
  'speechStop': 'Berhenti bertutur',
  'speechStopHint': 'Hentikan pertuturan atau input suara yang aktif',
  'speechPause': 'Jeda',
  'speechResume': 'Sambung',
  'speechSpeed': 'Kelajuan pertuturan',
  'speechSpeedValue': '{0} kali',
  'speechVoiceInput': 'Input suara',
  'speechVoiceInputHint': 'Mula atau hentikan rakaman suara',
  'speechListening': 'Mendengar...',
  'speechProcessing': 'Memproses...',
  'speechSpeaking': 'Bertutur',
  'speechPaused': 'Pertuturan dijeda',
  'speechError': 'Ralat pertuturan',
  'speechMicPermissionDenied': 'Kebenaran mikrofon ditolak',
  'speechMicPermissionInstructions': 'Benarkan mikrofon dalam tetapan peranti untuk menggunakan input suara.',
  'speechServiceUnavailable': 'Perkhidmatan pertuturan tidak tersedia',
  'correctionMetricsLabel': 'Metrik pembetulan',
  'typeLabel': 'Jenis',
  'triggerLabel': 'Pencetus',
  'allFilterLabel': 'semua',
  'noAiOutputsMatchFiltersLabel': 'Tiada output AI yang sepadan dengan penapis ini buat masa ini.',
  'noSummaryLabel': '(tiada ringkasan)',
  'itemNotFoundLabel': 'Item tidak dijumpai.',
  'approveThisOutputLabel': 'Luluskan output ini',
  'rejectThisOutputLabel': 'Tolak output ini',
  'optionalNoteHint': 'Nota pilihan',
  'whyIsItWrongHint': 'Kenapa ia salah? (wajib)',
  'approveLabel': 'Luluskan',
  'rejectLabel': 'Tolak',
  'correctLabelAction': 'Betulkan',
  'approvedLabel': 'Diluluskan',
  'rejectedLabel': 'Ditolak',
  'correctionSavedLabel': 'Pembetulan disimpan',
  'correctionFailedLabel': 'Pembetulan gagal',
  'resolveSuccessLabel': '{0} · pelajar tidak terjejas secara masa nyata',
  'resolveFailureLabel': '{0} gagal',
  'flaggedBecauseLabel': 'Ditanda kerana: {0}',
  'artifactLabel': 'Artifak',
  'artifactUnavailableLabel': 'Artifak asas tidak dapat dimuatkan (mungkin telah dibuang). Rekod semakan masih tersedia.',
  'generatedQuestionLabel': 'Soalan yang dijana',
  'promptLabel': 'Gesaan',
  'helperLabel': 'Pembantu',
  'optionsLabel': 'Pilihan',
  'expectedReasoningLabel': 'Penaakulan yang dijangka',
  'generationSourceLabel': 'Sumber penjanaan',
  'noneLabel': '(tiada)',
  'alternativesLabel': 'Alternatif',
  'candidateCountLabel': '{0} calon',
  'modelLabel': 'Model',
  'isCorrectLabel': 'Betul?',
  'yesLabel': 'Ya',
  'noLabel': 'Tidak',
  'diagnosticSignalLabel': 'Isyarat diagnostik',
  'historyLabel': 'Sejarah',
  'correctArtifactTitle': 'Betulkan {0}',
  'saveCorrectionLabel': 'Simpan pembetulan',
  'artifactNotCorrectableLabel': 'Jenis artifak ini tidak boleh dibetulkan.',
  'optionsTapCorrectLabel': 'Pilihan (ketik bulatan untuk menanda yang betul)',
  'optionNumberLabel': 'Pilihan {0}',
  'teacherFeedbackLabel': 'Maklum balas guru',
  'auditNoteLabel': 'Nota (log audit)',
  'humanCorrectionRateLabel': 'Kadar pembetulan manusia',
  'backlogLabel': 'Tunggakan',
  'oldestBacklogLabel': 'terlama {0}h',
  'noneOpenLabel': 'tiada yang terbuka',
  'correctionRateByTypeLabel': 'Kadar pembetulan mengikut jenis',
  'triggerPrecisionLabel': 'Ketepatan pencetus',
  'triggerPrecisionDescription': 'Daripada item yang ditanda oleh pencetus, berapa banyak yang benar-benar perlu dibaiki (dibetulkan atau ditolak). Lebih tinggi = pencetus itu berbaloi dengan masa guru.',
  'noResolvedItemsLabel': 'Belum ada item yang diselesaikan.',
  'lastFourteenDaysLabel': '14 hari lepas',
  'noActivityFourteenDaysLabel': 'Tiada aktiviti dalam 14 hari lepas.',
  'noMetricsYetLabel': 'Belum ada metrik.',
  'flagForTeacherLabel': 'Tandakan untuk guru',
  'flagForTeacherDescription': 'Beritahu kami apa yang kelihatan salah. Guru akan menyemaknya — pembelajaran anda tetap diteruskan.',
  'flagReasonHint': 'cth. jawapan yang ditanda nampak salah',
  'sendLabel': 'Hantar',
  'flagSentLabel': 'Dihantar kepada guru untuk semakan. Terima kasih!',
  'flagFailedLabel': 'Tidak dapat menghantar tanda buat masa ini.',
  'flaggedLabel': 'Ditanda',
  'looksWrongLabel': 'Nampak salah?',
  'insightsUnavailableLabel': 'Wawasan tidak tersedia',
  'insightsSummaryLabel': '{0} mata pelajaran · {1} konsep · {2} percubaan',
  'masteredCountLabel': '{0}/{1} dikuasai',
  'masteredLabel': 'Dikuasai',
  'attemptsPerDayLabel': 'Percubaan/hari',
  'periodLabel': 'Tempoh:',
  'trendPeriodLabel.month': 'bulan',
  'trendPeriodLabel.all': 'semua',
  'notEnoughHistoryLabel': 'Sejarah belum mencukupi.',
  'nothingAtRiskLabel': 'Tiada yang berisiko — syabas!',
  'atRiskDetailLabel': '{0} · penguasaan {1}{2}',
  'overdueSuffixLabel': ' · lewat {0}h',
  'edgeAiSettingsTitle': 'Tetapan AI tempatan',
  'edgeAiSettingsSubtitle': 'Pasang, mulakan, dan uji model LiteRT-LM di satu tempat.',
  'edgeAiHideModelUrlLabel': 'Sembunyikan URL model',
  'edgeAiShowModelUrlLabel': 'Tukar URL model (lanjutan)',
  'edgeAiModelUrlLabel': 'URL model (.litertlm)',
  'edgeAiInstallingLabel': 'Memasang...',
  'edgeAiInstallModelLabel': 'Pasang model',
  'edgeAiReinstallLabel': 'Pasang semula',
  'edgeAiInitializingLabel': 'Memulakan...',
  'edgeAiInitializeLabel': 'Mulakan',
  'edgeAiUnloadLabel': 'Nyahmuat',
  'edgeAiRunningLabel': 'Menjalankan...',
  'edgeAiRunTestPromptLabel': 'Jalankan gesaan ujian',
  'edgeAiDownloadLabel': 'Muat turun model: {0}',
  'edgeAiDownloadedLabel': '{0} dimuat turun',
  'edgeAiEnterModelUrlLabel': 'Masukkan URL model dahulu.',
  'edgeAiModelAlreadyPresentLabel': 'Model sudah ada pada peranti ini ({0}).',
  'edgeAiModelReinstalledLabel': 'Model dipasang semula ({0} dalam {1} ms).',
  'edgeAiModelInstalledLabel': 'Model dipasang ({0} dalam {1} ms).',
  'edgeAiInstallFailedLabel': 'Pemasangan model gagal: {0}',
  'edgeAiUnloadedLabel': 'Model dinyahmuat daripada memori runtime.',
  'edgeAiUnloadFailedLabel': 'Nyahmuat model gagal: {0}',
  'edgeAiInitializeCorruptLabel': 'Permulaan gagal. Lazimnya fail model rosak atau tidak sepadan dengan runtime peranti ini. Cuba pasang semula, kemudian mulakan lagi.',
  'edgeAiInitializeFailedLabel': 'Permulaan gagal: {0}',
  'edgeAiGenerationFailedLabel': 'Penjanaan tempatan gagal: {0}',
  'edgeAiStatusUnavailable': 'tidak tersedia',
  'edgeAiModelNotReadyTitle': 'Model tempatan belum sedia',
  'edgeAiModelNotReadyMessage': 'Model AI tempatan belum sedia. Pasang dan mulakannya sebelum memulakan praujian.',
  'edgeAiOpenSettingsLabel': 'Buka tetapan AI tempatan',
  'edgeAiCheckingReadinessLabel': 'Memeriksa kesediaan model AI tempatan...',
  'edgeAiPickTargetNodeLabel': 'Pilih nod sasaran dalam Matlamat Pembelajaran sebelum memulakan praujian.',
  'edgeAiFinishInstallLabel': 'Model tempatan belum sedia. Selesaikan pemasangan/permulaan, kemudian mulakan praujian semula.',
  'edgeAiModelMissingTitle': 'Model AI tempatan belum dipasang',
  'edgeAiModelMissingMessage': 'Wicara lebih stabil setelah model LiteRT dimuat turun. Buka tetapan AI tempatan sekarang?',
  'edgeAiDownloadModelLabel': 'Muat turun model',
  'edgeAiModelNotInitializedTitle': 'Model AI tempatan belum sedia',
  'edgeAiModelNotInitializedMessage': 'Model ada pada peranti ini tetapi belum dimulakan. Mulakan sekarang?',
  'edgeAiOpenSettingsShortLabel': 'Buka tetapan',
  'edgeAiInitializingModelLabel': 'Memulakan model tempatan...',
  'edgeAiModelReadyLabel': 'Model tempatan sedia digunakan.',
  'edgeAiInitializedNotReadyLabel': 'Permulaan selesai tetapi runtime belum sedia. Cuba buka tetapan AI tempatan.',
  'edgeAiTestPrompt': 'Jawab dalam Bahasa Melayu. Terangkan terbitan sebagai kadar perubahan dalam 2 ayat, kemudian berikan 1 soalan semakan kefahaman.',
  'edgeAiInitializeModelFailedLabel': 'Permulaan model gagal: {0}',
  'tapToOpenLabel': 'Ketik untuk membuka',
  'resetZoomLabel': 'Set semula zum',
  'videoFailedToLoadLabel': 'Video gagal dimuatkan. Cuba lagi.',
  'videoUrlMissingLabel': 'URL video tiada untuk artifak ini.',
  'videoLoadFailedLabel': 'Gagal memuatkan video ini.',
  'openFullscreenLabel': 'Buka skrin penuh',
  'videoPreviewWebOnlyLabel': 'Pratonton video tersedia pada binaan demo web.',
  'penSizeLabel': 'Saiz pen {0}',
  'penColorLabel': 'Warna pen',
  'saveWorkLabel': 'Simpan kerja',
  'sendToChatLabel': 'Hantar ke sembang',
  'canvasStatusLabel.draftEmpty': 'Draf kosong',
  'canvasStatusLabel.unsavedSketch': 'Lakaran belum disimpan',
  'canvasStatusLabel.unsavedChanges': 'Perubahan belum disimpan',
  'canvasStatusLabel.sentToChat': 'Dihantar ke sembang',
  'canvasStatusLabel.default': 'Disimpan, sedia dihantar',
  'canvasClearTitle': 'Kosongkan kanvas?',
  'canvasClearMessage': 'Ini akan membuang lakaran semasa dan nota kertas yang dilampirkan.',
  'canvasLabel': 'Kanvas',
  'canvasWorkspaceLabel': 'Ruang kerja kanvas',
  'canvasLargeHint': 'Gunakan ruang kerja yang lebih besar untuk gambar rajah dan nota.',
  'canvasSmallHint': 'Kerjakan penaakulan sebelum menghantar.',
  'canvasClosePanelLabel': 'Tutup panel',
  'canvasLargerPanelLabel': 'Panel lebih besar',
  'canvasResetViewLabel': 'Set semula paparan',
  'canvasHideGridLabel': 'Sembunyikan grid',
  'canvasShowGridLabel': 'Tunjukkan grid',
  'canvasClearLabel': 'Kosongkan kanvas',
  'canvasUploadImageLabel': 'Muat naik imej',
  'canvasKeepLabel': 'Kekalkan',
  'canvasClearShortLabel': 'Kosongkan',
  'canvasViewSectionLabel': 'Paparan',
  'canvasEditSectionLabel': 'Sunting',
  'canvasZoomOutLabel': 'Zum keluar',
  'canvasZoomInLabel': 'Zum masuk',
  'canvasPenLabel': 'Pen',
  'canvasPenTooltip': 'Mod pen',
  'canvasHandLabel': 'Tangan',
  'canvasHandTooltip': 'Mod tangan',
  'canvasEraseLabel': 'Padam',
  'canvasEraseTooltip': 'Mod pemadam',
  'canvasShapeLabel': 'Bentuk',
  'canvasShapeTooltip': 'Pembantu bentuk',
  'canvasLineShapeLabel': 'Bentuk garisan',
  'canvasArrowShapeLabel': 'Bentuk anak panah',
  'canvasRectangleShapeLabel': 'Bentuk segi empat tepat',
  'canvasPaperAttachedLabel': 'Kerja kertas\ndilampirkan',
  'canvasEmptyHintLabel': 'Lakarkan formula, gambar rajah, atau langkah kerja di sini.',
  'preparingAdaptiveQuestionsLabel': 'Menyediakan soalan adaptif...',
  'noLocalQuestionLabel': 'Penjana praujian tempatan tidak mengembalikan sebarang soalan.',
  'chooseAnswerBeforeReasoningLabel': 'Pilih jawapan sebelum menambah kerja anda.',
  'imageUnreadableLabel': 'Fail imej tidak dapat dibaca.',
  'imageTooLargeLabel': 'Imej mestilah 10 MB atau lebih kecil.',
  'adaptiveProbingLabel': 'Penyiasatan adaptif  •  Teori Ruang Pengetahuan',
  'missingPrerequisiteSkillLabel': 'Prasyarat hilang: pemacu punca',
  'missingPrerequisiteMessageLabel': 'Jurang itu nampak seperti memilih alat sebelum menamakan pemacu kecacatan, bukti, dan rantaian punca yang berkemungkinan.',
  'improvedLabel': 'Bertambah baik',
  'stagnantLabel': 'Mendatar',
  'reviewDueConceptsLabel': 'Semak konsep yang tertunggak',
  'dueThisWeekLabel': 'Tertunggak minggu ini',
  'preVsPostTestLabel': 'Praujian vs Pascaujian',
  'weeklyNarrativeLabel': 'Naratif mingguan',
  'focusLabel': 'Fokus',
  'answerScoredByAiLabel': 'Jawapan dinilai oleh AI.',
  'scoringOffLabel': 'Pemarkahan tersasar?',
  'laterLabel': 'Nanti',
  'trackWithoutModuleLabel': 'Trek telah dicipta, tetapi belum ada modul ruang kerja yang tersedia.',
  'workspaceAutoOpenFailedLabel': 'Tidak dapat membuka ruang kerja secara automatik selepas praujian.',
  'retentionLiftShortLabel': 'Peningkatan Ingatan',
  'remainingLabel': 'Baki',
  'weeklyReportLabel': 'Laporan Mingguan',
  'retentionLabel': 'Ingatan',
  'posttestMasteryCheckLabel': 'Semakan Penguasaan Pascaujian',
  'noSubjectsSelectedLabel': 'Tiada mata pelajaran dipilih',
  'thisWeekLabel': 'Minggu ini',
  'consistencyCompoundingLabel': 'Konsistensi sedang berganda.',
  'serverTimeoutLabel': 'Pelayan WICARA mengambil masa terlalu lama untuk membalas. Sila cuba lagi.',
  'uploadTimeoutLabel': 'Pelayan WICARA mengambil masa terlalu lama untuk memuat naik imej. Sila cuba lagi.',
  'serverUnreachableLabel': 'Tidak dapat menghubungi pelayan WICARA di {0}. {1}',
  'loginBeforeDashboardLabel': 'Sila log masuk sebelum membuka papan pemuka.',
  'loginBeforeOnboardingLabel': 'Sila log masuk sebelum memulakan onboarding.',
  'loginBeforeWorkspaceLabel': 'Sila log masuk sebelum membuka ruang kerja.',
  'loginBeforeTrackLabel': 'Sila log masuk sebelum mencipta trek.',
  'noMatchingGoalLabel': 'Tiada matlamat pembelajaran yang sepadan ditemui.',
  'noImageAssetIdLabel': 'Pelayan tidak mengembalikan id aset imej.',
  'activeGoalConflictLabel': 'Anda sudah mempunyai matlamat aktif untuk "{0}". ',
  'signInFailedLabel': 'Log masuk gagal: {0}',
  'registrationFailedLabel': 'Pendaftaran gagal: {0}',
  'googleSignInFailedLabel': 'Log masuk Google gagal: {0}',
  'googleSignInCancelledLabel': 'Log masuk Google dibatalkan.',
  'createGoalBeforePretestLabel': 'Cipta matlamat pembelajaran sebelum membuka praujian.',
  'invalidPretestQuestionLabel': 'Backend mengembalikan soalan praujian yang tidak sah.',
  'chooseAnswerFirstLabel': 'Pilih jawapan sebelum meneruskan.',
  'noNextQuestionLabel': 'Backend tidak mengembalikan soalan seterusnya atau diagnosis.',
  'invalidEvidenceImageLabel': 'Backend mengembalikan imej bukti yang tidak sah.',
  'createGoalBeforePathLabel': 'Cipta matlamat pembelajaran sebelum memilih laluan.',
  'loginBeforePretestLabel': 'Sila log masuk sebelum mengambil praujian.',
  'openPretestBeforeSubmitLabel': 'Buka praujian yang telah dijana sebelum menghantar.',
  'pathSelectedLabel': 'Laluan dipilih',
  'adaptivePathReadyLabel': 'Laluan pembelajaran adaptif anda sudah sedia.',
  'continueSelectedPathLabel': 'Teruskan dengan laluan yang dipilih.',
  'modulesCountLabel': '{0} modul',
  'adaptiveDiagnosisLabel': 'Diagnosis adaptif',
  'adaptivePretestCompleteLabel': 'Praujian adaptif selesai',
  'scoreMetaLabel': 'Skor {0}%',
  'correctCountMetaLabel': '{0}/{1} betul',
  'pathDescriptionLabel.review_only': 'Mulakan dengan ulang kaji ringkas dan latihan lanjutan.',
  'pathDescriptionLabel.target_reinforcement': 'Berlatih konsep sasaran pada tahap sederhana dan sukar.',
  'pathDescriptionLabel.target_intro': 'Mulakan daripada pengenalan konsep sasaran.',
  'pathDescriptionLabel.repair_prerequisites': 'Baiki jurang prasyarat sebelum kembali ke sasaran.',
  'pathDescriptionLabel.full_foundation_path': 'Bina semula asas yang lebih mendalam dahulu.',
  'pathDescriptionLabel.default': 'Pelajari konsep sasaran daripada asas.',
  'questionProgressLabel': 'Soalan {0} daripada {1}',
  'conceptNotFoundLabel': 'Konsep tidak dijumpai dalam kurikulum tempatan.',
  'conceptCodeNotFoundLabel': 'Konsep "{0}" tidak dijumpai dalam kurikulum tempatan.',
  'evidenceUploadNeedsBackendLabel': 'Muat naik bukti imej memerlukan mod praujian backend.',
  'emptyPathOptionLabel': 'Pilihan laluan tidak boleh kosong.',
  'localDiagnosisUnavailableLabel': 'Diagnosis tempatan belum tersedia. Selesaikan praujian dahulu.',
  'localPretestStateInvalidLabel': 'Keadaan praujian tempatan tidak sah.',
  'localPretestSessionInvalidLabel': 'Sesi praujian tempatan tidak sah.',
  'questionMismatchLabel': 'Soalan tidak sepadan. Muat semula praujian dan cuba lagi.',
  'optionNotFoundLabel': 'Pilihan yang dipilih tidak dijumpai untuk soalan ini.',
  'offlineCurriculumMissingLabel': 'Kurikulum luar talian tidak tersedia pada peranti ini.',
  'targetConceptNotChosenLabel': 'Tiada konsep sasaran dipilih. Buka Matlamat Pembelajaran dan pilih nod sasaran dahulu.',
  'targetConceptNotFoundLabel': 'Konsep sasaran "{0}" tidak dijumpai dalam kurikulum tempatan.',
  'backendPretestNotConfiguredLabel': 'Repositori praujian backend belum dikonfigurasikan.',
  'chooseBestAnswerLabel': 'Pilih jawapan terbaik untuk {0}.',
  'reviewWorkingStepsLabel': 'Semak langkah kerja anda untuk mengesahkan pilihan jawapan.',
  'emptyTopicLabel': 'Topik pembelajaran tidak boleh kosong.',
  'noMatchingConceptLabel': 'Belum ada konsep yang sepadan. Cuba tambah kata kunci yang lebih spesifik.',
  'searchAllSubjectsLabel': 'Dicari merentas semua mata pelajaran tempatan.',
  'searchLimitedSubjectLabel': 'Carian terhad kepada mata pelajaran yang dipilih.',
  'resolutionNotFoundLabel': 'Resolusi tidak dijumpai. Cari nod matlamat sekali lagi.',
  'resolutionMissingLabel': 'Resolusi tidak dijumpai.',
  'noTargetNodeLabel': 'Tiada nod sasaran dipilih untuk praujian.',
  'noMatchingConceptRetryLabel': 'Tiada konsep sepadan dijumpai. Cuba pertanyaan lain.',
  'localCurriculumMissingLabel': 'Kurikulum tempatan belum tersedia. Segerakkan kurikulum dahulu.',
  'localNodeNotFoundLabel': 'Nod "{0}" tidak dijumpai dalam kurikulum tempatan.',
  'targetConceptFallbackTitle': 'Konsep sasaran',
  'tutorHintDerivativeLabel': 'Petunjuk: perhatikan bagaimana nilai fungsi berubah apabila x beranjak sedikit, kemudian bandingkan dua titik yang sangat dekat.',
  'tutorHintGenericLabel': 'Petunjuk: pecahkan masalah kepada tiga langkah kecil, semak andaian pada setiap langkah, kemudian selesaikan satu demi satu.',
  'tutorEvaluateCloseLabel': 'Langkah anda sudah hampir betul. Kini terangkan mengapa peraturan itu terpakai pada bentuk masalah ini.',
  'tutorEvaluateInconsistentLabel': 'Jawapan anda belum konsisten. Semak semula langkah pertama, kemudian tulis semula sebab bagi setiap penjelmaan.',
  'reasoningTooShortLabel': 'Penaakulan anda masih terlalu pendek; tambahkan sebab anda memilih operasi itu.',
  'reasoningClearLabel': 'Penaakulan anda jelas dari segi struktur; kini sokongnya dengan satu contoh berangka yang ringkas.',
  'quizPromptLabel': "Cuba ini: jika f(x)=x^2, apakah terbitan f'(x), dan mengapa?",
  'summaryFallbackLabel': 'Ringkasnya: fokus pada konsep teras, satu peraturan utama, dan satu kesilapan lazim yang perlu dielakkan.',
  'explainDerivativeLabel': 'Terbitan menerangkan sepantas mana nilai fungsi berubah terhadap x. Bayangkannya sebagai kecerunan garis tangen pada satu titik pada lengkung.',
  'explainGenericLabel': 'Kita mulakan daripada definisi teras, beralih kepada contoh ringkas, kemudian menyemak semula dengan soalan pengesahan.',
  'heuristicReasoningFeedback': 'Penaakulan dinilai dengan heuristik tempatan kerana penilaian LiteRT tidak tersedia.',
  'carelessMistakeFeedback': 'Pilihan gandanya salah, tetapi terdapat isyarat penaakulan separa yang agak kuat.',
  'partialReasoningFeedback': 'Penaakulan separa, tetapi belum cukup untuk menyokong jawapan.',
  'unrelatedReasoningFeedback': 'Penaakulan itu belum berkait terus dengan konsep teras.',
  'diagnosisSummaryLabel.review_only': 'Anda sudah bersedia dalam {0}; ulang kaji ringkas sudah memadai.',
  'diagnosisSummaryLabel.target_reinforcement': 'Anda memahami asas {0}, tetapi perlukan latihan yang lebih sukar.',
  'diagnosisSummaryLabel.target_from_basics': '{0} sedang terbentuk, tetapi belum stabil pada tahap sederhana.',
  'diagnosisSummaryLabel.target_intro': '{0} masih menjadi jurang utama; mulakan daripada pengenalan konsep.',
  'diagnosisSummaryLabel.repair_prerequisites': 'Beberapa prasyarat untuk {0} perlu diperkukuh dahulu.',
  'diagnosisSummaryLabel.full_foundation_path': 'Asas sebelum {0} perlu dibina semula daripada prasyarat yang paling mendalam.',
  'diagnosisSummaryLabel.default': 'Diagnosis untuk {0} telah selesai.',
  'diagnosisFocusLabels.review_only.0': 'Ringkaskan semula konsep sasaran',
  'diagnosisFocusLabels.review_only.1': 'Buat 1-2 soalan pengukuhan ringan',
  'diagnosisFocusLabels.target_reinforcement.0': 'Berlatih tahap sederhana ke sukar pada sasaran',
  'diagnosisFocusLabels.target_reinforcement.1': 'Tingkatkan kualiti penaakulan bertulis',
  'diagnosisFocusLabels.target_from_basics.0': 'Ulang asas tepat sebelum sasaran',
  'diagnosisFocusLabels.target_from_basics.1': 'Berlatih secara berperingkat dari mudah ke sederhana',
  'diagnosisFocusLabels.target_intro.0': 'Mulakan daripada pengenalan konsep sasaran',
  'diagnosisFocusLabels.target_intro.1': 'Gunakan contoh konkrit sebelum yang simbolik',
  'diagnosisFocusLabels.repair_prerequisites.0': 'Perkukuh nod prasyarat yang rapuh atau hilang',
  'diagnosisFocusLabels.repair_prerequisites.1': 'Kembali ke sasaran sebaik prasyarat stabil',
  'diagnosisFocusLabels.full_foundation_path.0': 'Bina semula daripada prasyarat yang paling mendalam',
  'diagnosisFocusLabels.full_foundation_path.1': 'Naik secara berperingkat mengikut kedalaman graf',
  'offlineWritingNotesLabel': 'AI sedang menulis nota peribadi anda...',
  'offlineSessionNotFoundLabel': 'Sesi praujian tidak dijumpai.',
  'offlineInvalidStateLabel': 'Keadaan praujian tidak sah.',
  'offlineNotesReadyLabel': 'Nota AI peribadi anda sudah sedia.',
  'offlineNotesFailedLabel': 'AI tidak dapat menulis nota peribadi untuk sesi ini.',
  'offlineRuntimeNotReadyLabel': 'Model LiteRT belum sedia atau belum dipasang. Menggunakan sandaran tempatan.',
  'offlineGeneratingAttemptLabel': 'Menjana soalan tempatan (percubaan {0}/{1}, had masa {2}s)...',
  'offlineOutputInvalidLabel': 'Output model belum sah, mencuba semula ({0}/{1}).',
  'offlineValidLevelsLabel': 'Model menghasilkan {0} tahap yang sah ({1}).',
  'offlineAttemptTimeoutLabel': 'Percubaan {0} tamat masa ({1}s). Mencuba semula...',
  'offlineAttemptFailedLabel': 'Percubaan {0} gagal: {1}. Meneruskan dengan cubaan seterusnya.',
  'offlineGenerationDoneLabel': 'Penjanaan soalan selesai.',
  'offlineGenerationPartialLabel': 'Sebahagian soalan sah. Dilangkau: {0}.',
  'offlineGenerationFailedLabel': 'Penjanaan soalan gagal. Menggunakan templat sandaran.',
  'offlineGenerationFallbackLabel': 'Penjanaan soalan tempatan gagal. Menggunakan templat sandaran.',
  'offlinePreparingModelLabel': 'Menyediakan model tempatan...',
  'devModeLabel': 'Mod Pembangun',
  'devBypassTitle': 'Pintasan Pembangun',
  'devBypassSubtitle': 'Langkau pengesahan sebenar dalam binaan nyahpepijat.',
  'devOnboardingIncompleteLabel': 'Telah log masuk, tetapi onboarding belum selesai.',
  'startAtOnboardingLabel': 'Mula dari onboarding',
  'jumpToHomeLabel': 'Terus ke laman utama',
  'devSignedInLabel': 'Telah log masuk dan onboarding ditanda selesai.',
  'demoLimitsFromGraphsTitle': 'Had daripada graf',
  'demoLimitsFromGraphsReason': 'Kenapa sekarang? Ini membuka kesinambungan dan\nintuisi terbitan pertama.',
  'demoDerivativeRulesTitle': 'Peraturan terbitan',
  'demoFunctionCompositionTitle': 'Ulang kaji gubahan fungsi',
  'demoContinueCalculusTitle': 'Teruskan Kalkulus I',
  'demoContinueCalculusSubtitle': 'Had, terbitan, aplikasi',
  'demoLinearAlgebraTitle': 'Aljabar Linear',
  'demoLinearAlgebraSubtitle': 'Vektor, matriks, transformasi',
  'demoDiscreteMathTitle': 'Matematik Diskret',
  'demoDiscreteMathSubtitle': 'Logik, set, graf, pembilangan',
  'demoDerivativesIntuitionTitle': 'Intuisi terbitan',
  'demoDerivativesIntuitionSubtitle': 'Apa yang diberitahu oleh terbitan?',
  'demoLimitsFromGraphsSubtitle': 'Menghampiri sesuatu nilai tanpa menyentuhnya',
  'demoCalculusOneLabel': 'Kalkulus I',
  'demoCalculusLabel': 'Kalkulus',
  'demoDerivativeRulesReason': 'Kenapa sekarang? Anda sudah bersedia selepas had dan\ntafsiran kecerunan.',
  'demoFunctionCompositionReason': 'Kenapa sekarang? Diperlukan sebelum peraturan rantai dan\npembezaan tersirat.',
  'demoLessonMetaLabel': '{0} min   •   {1}',
  'reviewNowShortLabel': 'Semak',
  'demoCurrentTrackMeta': 'Trek semasa   •   {0}% selesai',
  'demoCreatedTrackMeta': 'Trek dicipta   •   {0}% selesai',
  'demoCreatedTrackReadyMeta': 'Trek dicipta   •   sedia diteruskan',
  'gradeValue': 'Darjah {0}',
  'subjectLabel.Math': 'Matematik',
  'subjectLabel.Matematika': 'Matematik',
  'subjectLabel.Physics': 'Fizik',
  'subjectLabel.Fisika': 'Fizik',
  'subjectLabel.Chemistry': 'Kimia',
  'subjectLabel.Kimia': 'Kimia',
  'subjectLabel.Biology': 'Biologi',
  'subjectLabel.Biologi': 'Biologi',
  'subjectLabel.Science': 'Sains',
  'subjectLabel.IPA': 'Sains',
  'subjectLabel.IPAS': 'Sains',
  'subjectDescription.Math': 'Aljabar, Geometri, Kalkulus',
  'subjectDescription.Physics': 'Mekanik, Gelombang, Termo',
  'subjectDescription.Chemistry': 'Stoikiometri, Tindak balas',
  'subjectDescription.Biology': 'Sel, Genetik, Ekologi',
  'difficultyLabel.easy': 'Mudah',
  'difficultyLabel.medium': 'Sederhana',
  'difficultyLabel.hard': 'Sukar',
  'estimatedDurationLabel': 'Anggaran {0}   •   {1}',
  'layerLabel': 'Lapisan {0}',
  'nodeStatusLabel.MASTERED': 'DIKUASAI',
  'nodeStatusLabel.REVIEW': 'SEMAK',
  'nodeStatusLabel.READY': 'SEDIA',
  'nodeStatusLabel.GAP': 'JURANG',
  'nodeStatusLabel.LOCKED': 'TERKUNCI',
  'weekShortLabels': 'A|I|S|R|K|J|S',
  'diagnosisPromptInstructions': '\nWrite a diagnosis of the learner\'s pretest in Bahasa Melayu. Not a summary, not encouragement - a DIAGNOSIS.\nEvery field of the JSON output must be written in Bahasa Melayu.\nUse ONLY the data in "nodes" below.\nTone: casual, addressed directly to the learner ("You ..."), no jargon.\nIf siswa_pakai_canvas=true, mention that the learner wrote or sketched while working (an effort signal).\n\nRules for each field:\n- "summary" (2-3 sentences, roughly 80-120 words):\n  name the specific target concept + 1 thing already understood (cite a correct question) + 1 thing still missing (cite a wrong question).\n  Avoid motivational lines.\n- "strengths" (1-3 points, each 1-2 full sentences):\n  format: "On the question about [core of the question], you [correct step]."\n  Cite reasoning_siswa whenever it is available.\n- "gaps" (1-3 points, each 2-3 full sentences):\n  format: "On the question about [core of the question], you chose [siswa_pilih] when the answer was [jawaban_benar]. [Contrast reasoning_siswa with expected_reasoning or explain the error]."\n- "evidence_notes" (0-2 points):\n  describe concrete cross-question patterns (e.g. empty reasoning on hard questions, canvas effort appearing, etc).\n- "recommended_focus" (1-3 points):\n  concrete practice that directly fixes the gap (name the sub-topic, not "practice more").\n\nFORBIDDEN: generic lines ("needs more practice", "the concept is weak").\nAlways reference the actual question content from the data.',
  'offlineQuestionPromptInstructions': '\nWrite short adaptive pretest questions in Bahasa Melayu.\nEvery question, option, and explanation must be written in Bahasa Melayu.\nOnly output these difficulty keys: {0}.\nEvery question must have 4 unique options and exactly 1 correct answer.\nAvoid long explanations. Keep it concise.\nThe "explanation" field MUST be concrete numbered steps (e.g. "1) ... 2) ... 3) ..."),\nnot a general definition of the concept.',
  'diagnosisSystemPrompt': "You are WICARA's on-device pretest diagnostic writer. Write a specific narrative in Bahasa Melayu, grounded in the given questions and the learner's answers, not generalities. Output valid JSON only.",
  'knowledgeGraph.Mathematics Prerequisite Map': 'Peta Prasyarat Matematik',
  'knowledgeGraph.Knowledge Map': 'Peta Pengetahuan',
  'knowledgeGraph.Primary Math': 'Matematik Sekolah Rendah',
  'knowledgeGraph.Lower Secondary': 'Menengah Rendah',
  'knowledgeGraph.Algebra and Functions': 'Aljabar dan Fungsi',
  'knowledgeGraph.Precalculus': 'Prakalkulus',
  'knowledgeGraph.Limits and Continuity': 'Had dan Kesinambungan',
  'knowledgeGraph.Calculus 1': 'Kalkulus 1',
  'knowledgeGraph.Calculus 2': 'Kalkulus 2',
  'knowledgeGraph.Calculus 3': 'Kalkulus 3',
  'knowledgeGraph.Counting': 'Membilang',
  'knowledgeGraph.Place Value': 'Nilai Tempat',
  'knowledgeGraph.Arithmetic Operations': 'Operasi Aritmetik',
  'knowledgeGraph.Fractions and Decimals': 'Pecahan dan Perpuluhan',
  'knowledgeGraph.Basic Shapes and Measurement': 'Bentuk Asas dan Pengukuran',
  'knowledgeGraph.Tables, Charts, and Mean': 'Jadual, Carta, dan Min',
  'knowledgeGraph.Integers and Rational Numbers': 'Integer dan Nombor Nisbah',
  'knowledgeGraph.Exponents and Roots Basics': 'Asas Eksponen dan Punca',
  'knowledgeGraph.Linear Equations': 'Persamaan Linear',
  'knowledgeGraph.Coordinate Graphing': 'Melukis Graf Koordinat',
  'knowledgeGraph.Slope and Intercepts': 'Kecerunan dan Pintasan',
  'knowledgeGraph.Pythagorean Theorem': 'Teorem Pythagoras',
  'knowledgeGraph.Functions, Domain, and Range': 'Fungsi, Domain, dan Julat',
  'knowledgeGraph.Function Composition and Inverses': 'Gubahan Fungsi dan Songsangan',
  'knowledgeGraph.Exponential and Logarithmic Functions': 'Fungsi Eksponen dan Logaritma',
  'knowledgeGraph.Quadratic and Polynomial Functions': 'Fungsi Kuadratik dan Polinomial',
  'knowledgeGraph.Rational Functions': 'Fungsi Nisbah',
  'knowledgeGraph.Sequences, Series, Sigma Notation': 'Jujukan, Siri, Tatatanda Sigma',
  'knowledgeGraph.Analytic Geometry and Conics': 'Geometri Analitik dan Keratan Kon',
  'knowledgeGraph.Trigonometric Functions and Graphs': 'Fungsi Trigonometri dan Grafnya',
  'knowledgeGraph.Trigonometric Identities and Equations': 'Identiti dan Persamaan Trigonometri',
  'knowledgeGraph.Vectors, Parametric, and Polar Basics': 'Asas Vektor, Parametrik, dan Polar',
  'knowledgeGraph.Precalculus Fluency': 'Kefasihan Prakalkulus',
  'knowledgeGraph.Intuitive Limits': 'Had secara Intuitif',
  'knowledgeGraph.Limit Laws and Algebraic Techniques': 'Hukum Had dan Teknik Aljabar',
  'knowledgeGraph.Trigonometric Limits and Squeeze Theorem': 'Had Trigonometri dan Teorem Apit',
  'knowledgeGraph.Continuity and Intermediate Value Theorem': 'Kesinambungan dan Teorem Nilai Perantaraan',
  'knowledgeGraph.Derivative Definition': 'Takrif Terbitan',
  'knowledgeGraph.Derivative Rules': 'Peraturan Terbitan',
  'knowledgeGraph.Chain Rule and Implicit Differentiation': 'Peraturan Rantai dan Pembezaan Tersirat',
  'knowledgeGraph.Related Rates, Optimization, Curve Sketching': 'Kadar Berkaitan, Pengoptimuman, Lakaran Lengkung',
  'knowledgeGraph.Antiderivatives, Riemann Sums, Definite Integrals': 'Antiterbitan, Hasil Tambah Riemann, Kamiran Tentu',
  'knowledgeGraph.Fundamental Theorem of Calculus': 'Teorem Asas Kalkulus',
  'knowledgeGraph.Integration Techniques': 'Teknik Pengamiran',
  'knowledgeGraph.Area, Volume, Work, Fluid Force': 'Luas, Isi Padu, Kerja, Daya Bendalir',
  'knowledgeGraph.Convergence Tests and Power Series': 'Ujian Penumpuan dan Siri Kuasa',
  'knowledgeGraph.Parametric and Polar Calculus': 'Kalkulus Parametrik dan Polar',
  'knowledgeGraph.3D Coordinates and Vector Operations': 'Koordinat 3D dan Operasi Vektor',
  'knowledgeGraph.Partial Derivatives and Gradients': 'Terbitan Separa dan Kecerunan',
  'knowledgeGraph.Double and Triple Integrals': 'Kamiran Berganda Dua dan Tiga',
  'knowledgeGraph.Vector Fields, Line Integrals, Green, Stokes, Divergence': 'Medan Vektor, Kamiran Garis, Green, Stokes, Divergens',
  'workspace.topicTitle': 'Topik pembelajaran',
  'workspace.startChatTitle': 'Mulakan sesi belajar',
  'workspace.startChatBody': 'Tutor akan membimbing anda daripada diagnosis dan fasa pembelajaran yang disimpan oleh backend.',
  'workspace.startChatButtonLabel': 'Mula chat belajar',
  'workspace.loadingDescription': 'Menghubungkan modul ini dengan konteks pembelajaran backend.',
  'workspace.syncedDescription': 'Perbualan, kanvas, media, dan keadaan fasa disegerakkan dengan backend.',
  'workspace.workspaceTitleLabel': 'Ruang kerja',
  'workspace.newChatLabel': 'Chat baharu',
  'workspace.chatHistoryTitle': 'Sejarah chat',
  'workspace.advancePhaseLabel': 'Fasa seterusnya',
  'workspace.advancingPhaseLabel': 'Meneruskan fasa...',
  'workspace.phaseTransitionHint': "Tekan 'Fasa seterusnya' apabila anda sudah bersedia.",
  'workspace.startPosttestButtonLabel': 'Mula Pascaujian',
  'workspace.posttestReadyBody': 'Mulakan pascaujian sekarang? Ini akan melengkapkan modul ruang kerja dan menyediakan sesi pascaujian.',
  'workspace.cancelLabel': 'Batal',
  'workspace.startPosttestDialogLabel': 'Mula pascaujian',
  'workspace.posttestUnavailableMessage': 'Pascaujian belum sedia. Teruskan mengikut panduan tutor.',
  'workspace.workspaceNotReadyMessage': 'Ruang kerja belum sedia.',
  'workspace.openTrackModuleMessage': 'Buka modul trek dari Laman Utama atau Baris Gilir sebelum menggunakan ruang kerja.',
  'workspace.chatLoadingMessage': 'Sesi chat masih dimuatkan.',
  'workspace.connectingWorkspaceMessage': 'Menghubungkan ke ruang kerja backend...',
  'workspace.savingEvidenceMessage': 'Menyimpan bukti ruang kerja...',
  'workspace.queueingVideoMessage': 'Menyediakan penjanaan video...',
  'workspace.videoQueuedMessage': 'Video dalam baris gilir. Menunggu worker...',
  'workspace.videoTimedOutMessage': 'Penjanaan video tamat masa selepas {0} minit.',
  'workspace.generationTimeoutMessage': 'Masa penjanaan tamat.',
  'workspace.buildingScenesMessage': 'Membina adegan, naratif, dan rendering...',
  'workspace.generatingVideoTitle': 'Menjana video',
  'workspace.generatedVideoFallbackTitle': 'Video yang dijana',
  'workspace.savedGeneratedVideoTitle': 'Video tersimpan',
  'workspace.generatedVideoSubtitle': 'Rendering video selesai dan sedia di ruang kerja anda.',
  'workspace.aiVideoChip': 'Video AI',
  'workspace.readyUrlChip': 'URL sedia',
  'workspace.playGeneratedVideoLabel': 'Mainkan video',
  'workspace.videoUrlUnavailableLabel': 'URL video tidak tersedia',
  'workspace.videoGenerationFailedTitle': 'Penjanaan video gagal',
  'workspace.videoGenerationFailedMessage': 'Penjanaan video gagal.',
  'workspace.retryGenerateVideoLabel': 'Cuba jana video lagi',
  'workspace.generatingVideoButtonLabel': 'Menjana video...',
  'workspace.generateVideoFromChatLabel': 'Jana video daripada chat ini',
  'workspace.generatingVideoContextMessage': 'Menjana video daripada konteks perbualan terkini anda...',
  'workspace.videoReadyMessage': 'Video sedia. Anda boleh memainkannya dari kad chat terbaharu.',
  'workspace.failedToLoadVideoMessage': 'Gagal memuatkan video daripada URL backend.',
  'workspace.openFullscreenTooltip': 'Buka skrin penuh',
  'workspace.durationChipLabel': 'Tempoh {0}',
  'workspace.canvasAttachedPrompt': 'Kerja kanvas telah dilampirkan. Tambah lakaran lain jika perlu.',
  'workspace.canvasPrompt': 'Perlukan papan putih? Buka kanvas dan hantar lakaran anda di sini.',
  'workspace.openCanvasLabel': 'Buka kanvas',
  'workspace.useCanvasLabel': 'Guna kanvas',
  'workspace.canvasSentLabel': 'Kanvas dihantar',
  'workspace.explanationCardLabel': 'Kad penjelasan',
  'workspace.evidenceRequestLabel': 'Bukti yang diminta',
  'workspace.nextActionsLabel': 'Tindakan seterusnya',
  'workspace.canvasSnapshotSentLabel': 'Snapshot kanvas dihantar',
  'workspace.canvasSnapshotSentCountLabel': 'Snapshot kanvas dihantar ({0} tanda)',
  'workspace.canvasMarksLabel': '{0} tanda',
  'workspace.canvasMarksAttachedLabel': '{0} tanda - kertas dilampirkan',
  'workspace.historyButtonLabel': 'Sejarah ({0})',
  'workspace.historyMessageCountLabel': '{0} mesej',
  'workspace.workspaceSyncFailedMessage': 'Penyegerakan ruang kerja gagal: {0}',
  'workspace.imageSentLabel': 'Imej dihantar',
  'workspace.videoRequestedNote': 'Video telah diminta di sini.',
  'workspace.canvasUploadFailedMessage': 'Muat naik imej kanvas gagal, tutor hanya menerima teks: {0}',
  'workspace.resumingVideoMessage': 'Menyambung semula kepada rendering yang sedang berjalan...',
  'workspace.resumeVideoLabel': 'Sambung semula',
  'workspace.tutorOfflineTitle': 'Tutor AI tidak tersedia',
  'workspace.tutorOfflineBody': 'Balasan di bawah menggunakan teks sandaran, jadi fasa anda tidak akan bergerak sehingga tutor kembali. Cuba lagi sebentar lagi.',
  'workspace.feedbackCorrectLabel': 'Tepat',
  'workspace.feedbackPartialLabel': 'Hampir tepat',
  'workspace.feedbackIncorrectLabel': 'Belum tepat',
  'workspace.misconceptionLabel': 'Miskonsepsi dikesan',
  'workspace.masteryDeltaUpLabel': 'Penguasaan +{0}%',
  'workspace.masteryDeltaDownLabel': 'Penguasaan -{0}%',
  'workspace.masteryDeltaFlatLabel': 'Penguasaan tidak berubah',
  'workspace.hintLevelLabel': 'Tahap bantuan {0}',
  'workspace.whyThisModuleLabel': 'Kenapa modul ini?',
  'workspace.deleteSessionLabel': 'Padam sesi',
  'workspace.deleteSessionConfirmBody': 'Sesi chat ini akan dipadam secara kekal. Teruskan?',
  'loadingPosttestLabel': 'Memuatkan Pascaujian',
  'preparingAdaptivePosttestFromBackendLabel': 'Menyediakan pascaujian adaptif daripada backend.',
  'posttestUnavailableLabel': 'Pascaujian tidak tersedia',
  'backendReturnedNoPosttestQuestionsLabel': 'Backend tidak mengembalikan sebarang soalan pascaujian.',
  'tryAgainLabel2': 'Cuba lagi',
  'questionsMediumHardBasedWhatLabel': '10 soalan: 3 sederhana dan 7 sukar berdasarkan apa yang anda pelajari.',
  'continueLabel2': 'Teruskan',
  'finishPosttestLabel': 'Selesaikan pascaujian',
  'loadingDailyEvalsLabel': 'Memuatkan Penilaian Harian',
  'fetchingSpacedReviewQuestionsFromLabel': 'Mengambil soalan ulangan berjarak daripada backend.',
  'dailyEvalsUnavailableLabel': 'Penilaian Harian tidak tersedia',
  'backendReturnedNoReviewQuestionsLabel': 'Backend tidak mengembalikan sebarang soalan semakan.',
  'dashboardUnavailableLabel': 'Papan pemuka tidak tersedia',
  'retryLabel2': 'Cuba semula',
  'loadingDashboardLabel': 'Memuatkan papan pemuka',
  'fetchingProfileFromBackendLabel': 'Mengambil profil anda daripada backend.',
  'elementarySchoolLabel': 'Sekolah rendah',
  'juniorHighSchoolLabel': 'Sekolah menengah rendah',
  'seniorHighSchoolLabel': 'Sekolah menengah atas',
  'universityLabel': 'Universiti',
  'pretestProgressLabel': 'Praujian sedang berjalan',
  'submittedAnswersSavedContinueFromLabel': 'Jawapan yang anda hantar telah disimpan. Teruskan dari soalan terakhir anda.',
  'continuePretestLabel': 'Teruskan praujian',
  'createLearningGoalLabel': 'Cipta matlamat pembelajaran',
  'createLearningGoalSoWicaraLabel': 'Cipta matlamat pembelajaran supaya WICARA boleh menyediakan trek dan ruang kerja.',
  'pickGoalSubjectBeforeOpeningLabel': 'Pilih matlamat dalam mata pelajaran ini sebelum membuka ruang kerja.',
  'nextModuleLabel': 'Modul seterusnya',
  'progressLabel2': 'Sedang berjalan',
  'readyLabel': 'Sedia',
  'completedLabel': 'Selesai',
  'pausedLabel': 'Dijeda',
  'needsReviewLabel2': 'Perlu semakan',
  'activeLabel': 'Aktif',
  'noModuleReadyYetLabel': 'Tiada modul yang sedia lagi',
  'goalDoesNotHaveActiveLabel': 'Matlamat ini belum mempunyai modul aktif.',
  'createChooseAnotherGoalStartLabel': 'Cipta atau pilih matlamat lain untuk mula belajar.',
  'noGeneratedVideosReadyYetLabel': 'Belum ada video yang dijana sedia.',
  'videosFromBackendJobsSavedLabel': 'Video daripada kerja backend disimpan di sini.',
  'noDailyEvaluationAssignedYetLabel': 'Belum ada penilaian harian yang ditugaskan.',
  'noEvaluationLabel': 'Tiada penilaian',
  'answerConfidenceLevelLabel': 'Tahap keyakinan jawapan',
  'howConfidentAnswerLabel': 'Sejauh mana anda yakin dengan jawapan anda?',
  'chooseNotConfidentVeryConfidentLabel': 'Pilih 0 (tidak yakin) hingga 10 (sangat yakin).',
  'masteryConfirmedLabel': 'Penguasaan disahkan',
  'reviewNeededFromPosttestResultsLabel': 'Semakan diperlukan daripada keputusan pascaujian',
  'posttestResultsLabel': 'Keputusan Pascaujian',
  'scoreSummaryLearningProgressionDecisionLabel': 'Ringkasan skor dan keputusan kemajuan pembelajaran datang daripada backend.',
  'correctnessLabel': 'Ketepatan',
  'correctLabel2': 'Betul',
  'decisionLabel': 'Keputusan',
  'trackProgressLabel': 'Kemajuan trek',
  'continueLearningLabel2': 'Teruskan belajar',
  'reviewWeakAreasLabel': 'Semak bahagian yang lemah',
  'moduleCompleteNextModuleNowLabel': 'Modul ini selesai dan modul seterusnya kini tersedia.',
  'learningGoalCompleteLabel': 'Matlamat pembelajaran ini telah selesai.',
  'backendConfirmedModuleAsPassedLabel': 'Backend mengesahkan modul ini lulus. Muat semula Laman Utama untuk melihat langkah trek seterusnya.',
  'backendRequiresReviewRemainingWeakLabel': 'Backend memerlukan semakan bahagian lemah yang tinggal sebelum percubaan seterusnya.',
  'conceptResultsLabel': 'Keputusan konsep',
  'noPosttestNodesHaveBeenLabel': 'Belum ada nod pascaujian yang dinilai.',
  'scoreLabel2': 'Skor',
  'profileUpdatedLabel': 'Profil dikemas kini.',
  'localAiLitertLmLabel': 'AI tempatan (LiteRT-LM)',
  'installInitializeModelLabel': 'Pasang & mulakan model',
  'reportUnavailableLabel': 'Laporan tidak tersedia',
  'openDetailsLabel': 'Buka butiran',
  'loadingWeekLabel': 'Memuatkan minggu ini',
  'syncingLabel': 'Menyegerakkan',
  'fetchingReportDataFromBackendLabel': 'Mengambil data laporan daripada backend.',
  'noDataYetLabel': 'Belum ada data',
  'startLabel': 'Mula',
  'takeDailyEvaluationsFirstPopulateLabel': 'Buat penilaian harian dahulu untuk mengisi carta ini.',
  'weekTrendLabel': 'Aliran 4 minggu',
  'ptsLabel': 'mata',
  'averageAccuracyLabel': 'Ketepatan purata',
  'scoresLabel': 'Skor',
  'preTestPostTestChangeLabel': 'Praujian, Pascaujian, dan Perubahan mewakili pergerakan skor purata.',
  'preTestLabel2': 'Praujian',
  'postTestLabel2': 'Pascaujian',
  'changeLabel': 'Perubahan',
  'learningReportUnavailableLabel': 'Laporan pembelajaran tidak tersedia',
  'loadingLearningReportLabel': 'Memuatkan Laporan Pembelajaran',
  'fetchingWeeklyProgressSummaryLabel': 'Mengambil ringkasan kemajuan mingguan.',
  'weekSummaryLabel': 'Ringkasan Minggu Ini',
  'answerAccuracyLabel': 'Ketepatan Jawapan',
  'fixedGapsLabel2': 'Jurang Dibaiki',
  'remainingGapsLabel2': 'Jurang Tinggal',
  'answerAccuracyPercentageCorrectAnswersLabel': 'Ketepatan jawapan = peratusan jawapan betul dalam julat tarikh yang dipilih.',
  'weekProgressLabel': 'Kemajuan 4 Minggu',
  'trackAccuracyAttemptVolumeGapLabel': 'Jejaki ketepatan, jumlah percubaan, dan pergerakan jurang setiap minggu.',
  'effortVsImpactLabel': 'Usaha lawan impak',
  'attemptsLabel': 'Percubaan',
  'activeDaysLabel': 'Hari aktif',
  'impactLabel': 'Impak',
  'strongConceptsVsNeedsImprovementLabel': 'Konsep Kukuh lawan Perlu Diperbaiki',
  'focusConceptsBiggestLiftOnesLabel': 'Fokus pada konsep dengan peningkatan terbesar dan yang masih berisiko.',
  'numberRightShowsConceptMasteryLabel': 'Nombor di sebelah kanan menunjukkan perubahan penguasaan konsep (%) dalam julat ini.',
  'nowStrongLabel': 'Kini Kukuh',
  'noConceptsShowedSignificantImprovementLabel': 'Tiada konsep menunjukkan peningkatan ketara minggu ini.',
  'needsImprovementLabel': 'Perlu Diperbaiki',
  'noRiskConceptsRangeLabel': 'Tiada konsep berisiko dalam julat ini.',
  'weekLabel2': 'Minggu ini',
  'lastWeekLabel': 'Minggu lepas',
  'lastWeeksLabel': '4 minggu lepas',
  'averageScoreLabel': 'Skor Purata',
  'notEnoughMatchedPreTestLabel': 'Belum cukup data praujian dan pascaujian yang berpadanan.',
  'reportRequestTimedOutPleaseLabel': 'Permintaan laporan tamat masa. Sila cuba lagi.',
  'reportCouldNotLoadedPleaseLabel': 'Laporan tidak dapat dimuatkan. Sila cuba lagi.',
  'completeDataLabel': 'Data Lengkap',
  'partialDataLabel': 'Data Separa',
  'earlyDataLabel': 'Data Awal',
  'highLeverageLabel': 'Kesan tinggi',
  'steadyLabel': 'Stabil',
  'needsFocusLabel': 'Perlu fokus',
  'noSignalLabel': 'Tiada isyarat',
  'reportBuiltFromSufficientlyCompleteLabel': 'Laporan ini dibina daripada sejarah yang cukup lengkap.',
  'dataExistsButComparisonHistoryLabel': 'Data wujud, tetapi sejarah perbandingan masih tidak lengkap.',
  'dataStillThinSoSomeLabel': 'Data masih sedikit, jadi sebahagian wawasan hanyalah anggaran awal.',
  'dataQualityStatusNotDefinedLabel': 'Status kualiti data belum ditakrifkan.',
  'overallLabel2': 'Keseluruhan',
  'applicationLabel2': 'Aplikasi',
  'analysisLabel2': 'Analisis',
  'weekLabel3': '0 minggu ini',
  'learningPerformanceLabel': 'Prestasi pembelajaran',
  'noAssessmentAttemptsRangeYetLabel': 'Belum ada percubaan penilaian dalam julat ini. Buat penilaian harian untuk membina graf ini.',
  'useAsLearningGoalLabel': 'Guna ini sebagai matlamat pembelajaran anda?',
  'chooseAnotherNodeLabel': 'Pilih nod lain',
  'startPretestLabel': 'Mula praujian',
  'activeGoalFoundLabel': 'Matlamat aktif dijumpai',
  'backLabel2': 'Kembali',
  'continueExistingGoalLabel': 'Teruskan matlamat sedia ada',
  'useAsNewGoalLabel': 'Guna sebagai matlamat baharu',
  'visualizePrerequisitesGapsNextConceptsLabel': 'Gambarkan prasyarat, jurang, dan konsep seterusnya.',
  'alreadyHaveActiveGoalNodeLabel': 'Anda sudah mempunyai matlamat aktif untuk nod ini:',
  'canContinueGoalGoBackLabel': 'Anda boleh meneruskan matlamat ini, atau kembali untuk memilih nod.',
  'findLearningGoalNodeLabel': 'Cari nod matlamat pembelajaran',
  'searchAgainLabel': 'Cari lagi',
  'searchAgainNewQueryLabel': 'Cari lagi dengan pertanyaan baharu',
  'sureWantTakeLabel': 'Adakah anda pasti mahu mengambil ini?',
  'nodeDetailLabel': 'Butiran nod',
  'descriptionLabel': 'Penerangan',
  'subjectLabel2': 'Mata pelajaran',
  'matchLabel': 'Padanan',
  'seeGraphLabel': 'Lihat graf',
  'lockLabel': 'Kunci',
  'findLearningGoalFirstLabel': 'Cari matlamat pembelajaran dahulu',
  'typeGoalThenWicaraWillLabel': 'Taip matlamat anda, kemudian WICARA akan memadankannya dengan nod bahan. Praujian bermula hanya selepas anda mengesahkan nod itu.',
  'nodeNotCertainLabel': 'Nod belum pasti',
  'tryAddingGradeSubjectMoreLabel': 'Cuba tambah darjah, mata pelajaran, atau topik yang lebih spesifik.',
  'pickClosestCandidateLabel': 'Pilih calon yang paling hampir',
  'recommendedNodeLabel': 'Nod yang disyorkan',
  'otherPossibleNodesLabel': 'Nod lain yang mungkin',
  'editPromptLabel': 'Ubah gesaan',
  'viewDetailLabel': 'Lihat butiran',
  'descriptionNotFoundLabel': 'Penerangan tidak dijumpai.',
  'nodeBelowGradeLevelCanLabel': 'Nod ini di bawah tahap darjah anda; ia boleh mengukuhkan asas.',
  'nodeAboveGradeLevelMayLabel': 'Nod ini di atas tahap darjah anda; ia mungkin terasa lebih mencabar.',
  'nodeFitsGradeLevelLabel': 'Nod ini sesuai dengan tahap darjah anda.',
  'mathLabel': 'Matematik',
  'physicsLabel': 'Fizik',
  'chemistryLabel': 'Kimia',
  'biologyLabel': 'Biologi',
  'uploadingWorkImageLabel': 'Memuat naik imej kerja anda...',
  'answerSentEvaluatingWorkPreparingLabel': 'Jawapan dihantar. Menilai kerja anda dan menyediakan soalan seterusnya...',
  'submitAnswerLabel': 'Hantar jawapan',
  'addReasoningSketchLabel': 'Tambah penaakulan / lakaran',
  'hideWorkEvidenceLabel': 'Sembunyikan bukti kerja',
  'workEvidenceLabel': 'Bukti kerja',
  'typeStepsUploadPhotoWorkLabel': 'Taip langkah anda, muat naik foto kerja anda, atau gunakan kedua-duanya. AI akan membaca imej itu sebagai langkah penyelesaian.',
  'writeSolutionStepsLabel': 'Tulis langkah penyelesaian anda...',
  'uploadWorkImageLabel': 'Muat naik imej kerja',
  'removeImageLabel': 'Buang imej',
  'submitAnswerEvidenceLabel': 'Hantar jawapan dengan bukti',
  'correctLabel3': 'betul',
  'noAnswersLabel': 'Tiada jawapan',
  'officialMcqScoreLabel': 'Skor rasmi aneka pilihan',
  'reportLabel': 'Laporan',
  'whatLooksStrongLabel': 'Apa yang kelihatan kukuh',
  'whatNeedsWorkLabel': 'Apa yang perlu diperbaiki',
  'evidenceNotesLabel': 'Nota bukti',
  'checkedNodesLabel': 'Nod yang disemak',
  'levelLabel': 'Tahap',
  'nextPathFocusLabel': 'Fokus laluan seterusnya',
  'reasoningSuggestsMisconceptionNodeLabel': 'Penaakulan menunjukkan miskonsepsi pada nod ini.',
  'therePossibleCarelessChoiceDespiteLabel': 'Ada kemungkinan pilihan cuai walaupun penaakulan munasabah.',
  'evidenceWasStoredButNoLabel': 'Bukti telah disimpan, tetapi tiada langkah bertulis untuk dianalisis.',
  'noSubjectGoalsYetLabel': 'Belum ada matlamat {0}',
  'subjectGoalsLabel': 'Matlamat {0}',
  'percentCompleteLabel': '{0}% selesai',
  'moduleStatusLabel': 'Status modul: {0}',
  'moduleStatusWithMinutesLabel': '{0} min - status modul: {1}',
  'sessionReturnsToPhaseLabel': 'Sesi kembali ke fasa {0} untuk pemulihan.{1}',
  'targetPassedLabel': '{0}/{1} betul. Sasaran ini lulus.',
  'conceptMarkedForReviewLabel': '{0}/{1} betul. Backend menandakan konsep ini untuk semakan.',
  'accuracyPercentLabel': 'Ketepatan {0}%',
  'fixedGapsDeltaLabel': '+{0} minggu ini',
  'remainingGapsDeltaLabel': '{0} minggu ini',
  'weeklyPointSummaryLabel': '{0} percubaan • {1} jurang dibaiki • {2} jurang tinggal',
  'positiveDeltaThisWeekLabel': '+{0} minggu ini',
  'deltaThisWeekLabel': '{0} minggu ini',
  'activeGoalConflictBodyLabel': 'Anda sudah mempunyai matlamat aktif untuk "{0}". Anda boleh meneruskan matlamat itu atau kembali memilih nod.',
  'reasoningQualityLabel': 'Kualiti penaakulan: {0}{1}.',
  'learnConceptInGraphLabel': 'Pelajari {0} dalam graf prasyarat.',
  'outputValidJsonOnlyLabel': 'Keluarkan JSON yang sah sahaja:',
  'workspace.collapseLabel': 'Ringkaskan',
  'workspace.detailsLabel': 'Butiran',
  'workspace.finalTargetLabel': 'Sasaran akhir: {0}',
  'workspace.phaseTransitionReadyLabel': 'Sedia beralih fasa',
  'workspace.continueThisPhaseLabel': 'Belajar di fasa ini',
};
