/// Tiếng Việt translations for `OnboardingCopy`.
///
/// Keys match member names (`member.case` for switch arms). Templated members
/// use `{0}`, `{1}` … placeholders; list members join items with `|`.
/// Missing keys fall back to English.
///
/// Authored without native-speaker review — proofread before release.
library;

const copyVi = <String, String>{
  'letsSetYouUpTitle': 'Hãy thiết lập tài khoản của bạn',
  'letsSetYouUpSubtitle':
      'Hãy cho chúng tôi biết đôi chút về bạn để\ncá nhân hoá việc học của bạn.',
  'fullNameLabel': 'Họ và tên',
  'countryLabel': 'Quốc gia',
  'gradeLevelLabel': 'Khối lớp',
  'preferredLanguageLabel': 'Ngôn ngữ ưa thích',
  'continueLabel': 'Tiếp tục',
  'improveExperienceNote':
      'Chúng tôi sẽ tiếp tục cải thiện trải nghiệm này\ndành riêng cho bạn.',
  'chooseSubjectsTitle': 'Chọn môn học của bạn',
  'chooseSubjectsSubtitle':
      'Chọn những môn bạn muốn học.\nBạn có thể thay đổi bất cứ lúc nào.',
  'customizeLaterNote': 'Bạn có thể tuỳ chỉnh thêm sau.',
  'preferencesTitle': 'Bạn muốn học như thế nào?',
  'preferencesSubtitle':
      'Chọn tuỳ chọn của bạn. Bạn có thể thay đổi\nbất cứ lúc nào.',
  'studyGoalLabel': 'Mục tiêu học tập',
  'dailyStudyTimeLabel': 'Thời gian học mỗi ngày',
  'adaptivePretestLabel': 'Tiếp tục đến bài kiểm tra đầu vào thích ứng',
  'personalizePathNote':
      'Điều này giúp chúng tôi cá nhân hoá lộ trình học của bạn.',
  'preferenceCallout':
      'WICARA thích ứng với bạn, nhịp độ, phong cách\nvà mục tiêu của bạn.',
  'profileTitle': 'Hồ sơ',
  'profileSubtitle': 'Quản lý tuỳ chọn học tập và tài khoản của bạn.',
  'homeLabel': 'Trang chủ',
  'learnLabel': 'Học',
  'progressLabel': 'Tiến độ',
  'learningSetupTitle': 'Thiết lập học tập',
  'preferencesSectionTitle': 'Tuỳ chọn',
  'subjectsLabel': 'Môn học',
  'logoutLabel': 'Đăng xuất',
  'welcomeBack': 'Chào mừng trở lại,\n',
  'homeSubtitle':
      'Sẵn sàng tiếp tục học và tạo nên điều tuyệt vời hôm nay chứ?',
  'languageLabel': 'Ngôn ngữ',
  'getStartedLabel': 'Bắt đầu',
  'alreadyHaveAccountLabel': 'Tôi đã có tài khoản',
  'signInTitle': 'Chào mừng trở lại',
  'signInSubtitle': 'Đăng nhập để tiếp tục việc học của bạn',
  'registerTitle': 'Tạo tài khoản của bạn',
  'registerSubtitle': 'Đăng ký một lần, rồi tiếp tục lộ trình học của bạn',
  'emailOrPhoneLabel': 'Email hoặc số điện thoại',
  'emailOrPhoneHint': 'Nhập email hoặc số điện thoại của bạn',
  'emailLabel': 'Email',
  'emailHint': 'Nhập email của bạn',
  'passwordLabel': 'Mật khẩu',
  'passwordHint': 'Nhập mật khẩu của bạn',
  'fullNameHint': 'Nhập họ và tên của bạn',
  'forgotPasswordLabel': 'Quên mật khẩu?',
  'signInLabel': 'Đăng nhập',
  'registerLabel': 'Đăng ký',
  'logInLabel': 'Đăng nhập',
  'orContinueWithLabel': 'hoặc tiếp tục với',
  'securityNoteLabel': 'Dữ liệu của bạn được bảo mật và riêng tư.',
  'cancelLabel': 'Huỷ',
  'applyLabel': 'Áp dụng',
  'searchLabel': 'Tìm kiếm',
  'recommendedLabel': 'Được đề xuất',
  'tracksLabel': 'Lộ trình',
  'galleryLabel': 'Thư viện',
  'viewAllLabel': 'Xem tất cả',
  'nextUpLabel': 'Tiếp theo',
  'exploreLabel': 'Khám phá',
  'currentStreakLabel': 'Chuỗi ngày hiện tại',
  'backToHomeLabel': 'Về Trang chủ',
  'continueLearningLabel': 'Tiếp tục học',
  'learningGoalTitle': 'Bạn muốn học gì?',
  'learningGoalSubtitle':
      'Hãy nhập mục tiêu của bạn trước. WICARA sẽ tìm nút kiến thức phù hợp, sau đó bài kiểm tra đầu vào bắt đầu khi bạn xác nhận.',
  'learningTopicLabel': 'Chủ đề học tập',
  'generatePretestLabel': 'Tạo bài kiểm tra đầu vào',
  'typeATopicHint': 'Nhập một chủ đề',
  'loadingPretestLabel': 'Đang tải bài kiểm tra đầu vào',
  'pretestUnavailableLabel': 'Bài kiểm tra đầu vào không khả dụng',
  'tryAgainLabel': 'Thử lại',
  'preTestLabel': 'Kiểm tra đầu vào',
  'postTestLabel': 'Kiểm tra đầu ra',
  'refreshLabel': 'Làm mới',
  'retryLabel': 'Thử lại',
  'backLabel': 'Quay lại',
  'undoLabel': 'Hoàn tác',
  'redoLabel': 'Làm lại',
  'teacherReviewLabel': 'Giáo viên duyệt',
  'insightsLabel': 'Phân tích',
  'knowledgeMapLabel': 'Bản đồ kiến thức',
  'learningReportLabel': 'Báo cáo học tập',
  'reviewNowLabel': 'Ôn ngay',
  'reviewDueLabel': 'Cần ôn tập',
  'studyGoalOptionalLabel': 'Mục tiêu học tập (tùy chọn)',
  'dailyStudyTimeOptionalLabel': 'Thời gian học mỗi ngày (tùy chọn)',
  'learnSubtitleRecommended': 'Các lộ trình gợi ý giúp bạn đạt được mục tiêu.',
  'learnSubtitleTracks': 'Khám phá lộ trình học của bạn hoặc tạo lộ trình mới tại đây.',
  'learnSubtitleGallery': 'Xem lại video và bản tóm tắt trong hành trình học của bạn.',
  'todaysLearningQueueLabel': 'Hàng chờ học hôm nay',
  'continueSessionLabel': 'Tiếp tục phiên học',
  'wantToLearnSomethingNewLabel': 'Bạn muốn học điều gì mới?',
  'exploreTracksDescription': 'Khám phá các lộ trình bạn đã tạo hoặc bắt đầu lộ trình khác.',
  'streakDaysLabel': '{0} ngày',
  'dailyEvaluationLabel': 'Đánh giá hằng ngày',
  'dailyEvaluationPrompt': '. Chọn mức độ tự tin nếu muốn, rồi làm bài kiểm tra hằng ngày.',
  'takeDailyEvaluationLabel': 'Làm đánh giá hằng ngày',
  'dailyEvalsWordmark': 'Đánh giá hằng ngày',
  'dailyEvalsQuickCheckin': 'Kiểm tra nhanh cho lộ trình học hôm nay.',
  'finishDailyEvalsLabel': 'Hoàn thành đánh giá hằng ngày',
  'dailyQuestionProgressLabel': '{0} trên {1}',
  'reviewDueSummaryLabel': '{0} mục sẵn sàng để ôn tập',
  'retentionForecastLabel': 'Dự báo ghi nhớ của bạn',
  'retentionForecastBasisLabel': 'Dựa trên MVP đường cong lãng quên Ebbinghaus.',
  'retentionCoachingLabel': 'Hãy tiếp tục ôn tập để nâng đường cong lên và cải thiện ghi nhớ dài hạn.',
  'evaluationCompleteLabel': 'Hoàn thành đánh giá 🎉',
  'evaluationCompleteSubtitle': 'Làm tốt lắm! Bạn đang xây dựng kiến thức bền vững.',
  'reviewedLabel': 'Đã ôn tập',
  'toReviewAgainLabel': 'Cần ôn lại',
  'scoreLabel': 'Điểm',
  'reviewedConceptsLabel': 'Các khái niệm đã ôn',
  'noReviewedConceptsLabel': 'Chưa ôn khái niệm nào',
  'continueLearningReason': 'Đi tới lộ trình học của bạn.',
  'statusGoodLabel': 'Tốt',
  'statusStrongLabel': 'Vững',
  'statusReviewLabel': 'Cần ôn',
  'retentionLiftLabel': 'Mức tăng ghi nhớ',
  'daysUntilNextReviewLabel': 'Số ngày đến lần ôn tiếp theo',
  'learnSomethingNewLabel': 'Học điều gì đó mới',
  'newTrackDescription': 'Tạo lộ trình mới ngoài danh sách hiện tại của bạn.',
  'newTrackLabel': 'Lộ trình mới',
  'progressSubtitle': 'Bắt đầu với báo cáo học tập, rồi khám phá bản đồ kiến thức.',
  'learningReportDescription': 'Hiệu suất hằng tuần, các lỗ hổng đã khắc phục, khái niệm đã mở khóa.',
  'fixedGapsLabel': 'Lỗ hổng đã khắc phục',
  'remainingGapsLabel': 'Lỗ hổng còn lại',
  'thisWeekFixedDelta': '+4 tuần này',
  'thisWeekRemainingDelta': '-2 tuần này',
  'learningReportHint': 'Di chuột hoặc chạm vào một tuần để xem trước mức tăng trưởng, lỗ hổng đã khắc phục và mức tăng ghi nhớ.',
  'retentionDeltaLabel': '+{0}% ghi nhớ',
  'weekLabel': 'T{0}',
  'knowledgeMapDescription': 'Khám phá các lĩnh vực môn học và lộ trình tiên quyết.',
  'fallbackGraphLabel': 'Đồ thị dự phòng tĩnh',
  'liveCurriculumGraphLabel': 'Đồ thị kiến thức trực tiếp',
  'nodeCountLabel': '{0} nút',
  'masteryConfidenceLabel': 'Độ tự tin thành thạo',
  'aboutThisConceptLabel': 'Về khái niệm này',
  'relatedConceptsLabel': 'Khái niệm liên quan',
  'noDirectRelatedConceptLabel': 'Không có khái niệm liên quan trực tiếp',
  'crossSubjectConnectionsLabel': 'Kết nối liên môn',
  'graphOfGraphsHint': 'Liên kết Graph of Graphs hiển thị khi có sẵn.',
  'conceptBridgeFallbackLabel': 'Cầu nối khái niệm',
  'conceptFallbackDescription': 'Khái niệm trong đồ thị tiên quyết.',
  'confidenceQuestionLabel': 'Bạn tự tin đến mức nào?',
  'yourKnowledgeStateLabel': 'Trạng thái kiến thức của bạn',
  'personalizedPathGeneratedLabel': 'Đã tạo lộ trình cá nhân hóa',
  'personalizedPathDescription': 'Bắt đầu với kiến thức tiên quyết, rồi luyện các câu hỏi truy nguyên nguyên nhân.',
  'continueToMyPathLabel': 'Tiếp tục tới lộ trình của tôi',
  'missingPrerequisiteGapsLabel': 'Lỗ hổng kiến thức tiên quyết',
  'learnerLabel': 'Người học',
  'statusLabel': 'Trạng thái',
  'couldNotLoadQueueLabel': 'Không thể tải hàng chờ',
  'nothingToReviewLabel': 'Không có gì để ôn tập',
  'reviewItemLabel': 'Mục ôn tập',
  'flaggedForReviewLabel': 'Đã đánh dấu để xem xét.',
  'learningGoalDiagnosisLabel': 'Chẩn đoán mục tiêu học tập',
  'learnerAskedLabel': 'Người học đã hỏi',
  'subjectSingularLabel': 'Môn học',
  'suggestedConceptIdLabel': 'Id khái niệm được đề xuất',
  'confidenceLabel': 'Độ tự tin',
  'reasoningEvaluationLabel': 'Đánh giá lập luận',
  'learnerReasoningLabel': 'Lập luận của người học',
  'answerScoreLabel': 'Điểm câu trả lời',
  'reasoningScoreLabel': 'Điểm lập luận',
  'evidenceScoreLabel': 'Điểm bằng chứng',
  'overrideConceptIdLabel': 'Ghi đè id khái niệm tiên quyết đã chẩn đoán. Xác nhận sẽ đặt trạng thái chẩn đoán thành "đã xác nhận".',
  'correctedOfReviewedLabel': '{0} đã sửa trên {1} đã xem xét',
  'noReviewedItemsLabel': 'Chưa có mục nào được xem xét.',
  'reviewedCountLabel': '{0} đã xem xét',
  'darkCorrectedLightReviewedLabel': 'Đậm = đã sửa · nhạt = đã xem xét',
  'reviewArtifactLabel.question': 'Câu hỏi',
  'reviewArtifactLabel.diagnosis': 'Chẩn đoán',
  'reviewArtifactLabel.evaluation': 'Đánh giá',
  'reviewArtifactLabel.open': 'Đang mở',
  'reviewArtifactLabel.approved': 'Đã duyệt',
  'reviewArtifactLabel.rejected': 'Bị từ chối',
  'reviewArtifactLabel.corrected': 'Đã sửa',
  'reviewArtifactLabel.all': 'Tất cả',
  'reviewArtifactLabel.low_confidence': 'Độ tự tin thấp',
  'reviewArtifactLabel.risk_signal': 'Tín hiệu rủi ro',
  'reviewArtifactLabel.sampled': 'Được lấy mẫu',
  'reviewArtifactLabel.learner_flag': 'Cờ người học',
  'overallMasteryLabel': 'Mức thành thạo tổng thể',
  'streakSummaryLabel': '🔥 chuỗi {0} ngày · tốt nhất {1} · {2} ngày hoạt động',
  'masteryBySubjectLabel': 'Mức thành thạo theo môn học',
  'noSubjectDataLabel': 'Chưa có dữ liệu môn học.',
  'streakDaysShortLabel': '{0}n',
  'scoreTrendLabel': 'Xu hướng điểm',
  'needsReviewLabel': 'Cần ôn tập ({0})',
  'edgeAiStatusReadFailedLabel': 'Không đọc được trạng thái edge runtime: {0}',
  'edgeAiStatusChecking': 'đang kiểm tra',
  'edgeAiStatusUnknown': 'không rõ',
  'edgeAiStatusReady': 'sẵn sàng',
  'edgeAiStatusNeedsInit': 'cần khởi tạo',
  'edgeAiStatusNeedsInstall': 'cần cài đặt',
  'todaysTopicLabel': 'Chủ đề hôm nay: ',
  'notConfidentLabel': 'Không tự tin',
  'veryConfidentLabel': 'Rất tự tin',
  'nextQuestionLabel': 'Câu hỏi tiếp theo',
  'highImpactLabel': 'Tác động cao',
  'maintainedLabel': 'Được duy trì',
  'correctLabel': 'Đúng',
  'pendingLabel': 'Đang chờ',
  'recommendedNextActionsLabel': 'Hành động tiếp theo được đề xuất',
  'spacedRepetitionImpactLabel': 'Tác động của lặp lại ngắt quãng',
  'memoryStrengthenedLabel': 'Bạn đã củng cố trí nhớ của mình.',
  'contentGalleryLabel': 'Thư viện nội dung',
  'contentGalleryDescription': 'Tất cả video đã tạo trước đây đều ở đây, sẵn sàng xem lại cùng ghi chú mà WICARA đã tổng hợp cho bạn.',
  'notesLabel': 'Ghi chú',
  'cheatsheetSummaryLabel': 'Tóm tắt bảng ghi nhớ',
  'recommendedForCurrentReadinessLabel': 'Được đề xuất cho Giải tích I dựa trên\ncác lỗ hổng và mức sẵn sàng hiện tại của bạn.',
  'fixedShortLabel': '+4 đã khắc phục',
  'overallLabel': 'Tổng thể',
  'applicationLabel': 'Ứng dụng',
  'analysisLabel': 'Phân tích',
  'completeLabel': 'Hoàn thành',
  'skillGrowthLabel': 'Sự phát triển kỹ năng',
  'remainingCountLabel': 'Còn {0}',
  'loadingCurriculumLabel': 'Đang tải chương trình học từ backend...',
  'prerequisiteLayerLabel': 'Lớp kiến thức tiên quyết',
  'combinedLayerLabel': '{0} + {1} nữa',
  'prerequisitesLabel': 'Kiến thức tiên quyết',
  'noDirectPrerequisiteLabel': 'Không có kiến thức tiên quyết trực tiếp',
  'relatedBadgeLabel': 'LIÊN QUAN',
  'bypassForWebDevLabel': 'Bỏ qua cho phát triển web',
  'passwordResetMockedMessage': 'Đặt lại mật khẩu hiện đang là bản mô phỏng.',
  'emailRequiredMessage': 'Nhập email của bạn',
  'fullNameRequiredMessage': 'Nhập họ tên của bạn',
  'registrationEmailValidationMessage': 'Dùng địa chỉ email để đăng ký',
  'passwordMinLengthMessage': 'Mật khẩu phải có ít nhất 6 ký tự',
  'adaptivePretestReadyNextLabel': 'Bài kiểm tra đầu vào thích ứng đã sẵn sàng',
  'adaptivePretestReadyDescription': 'Một vài câu hỏi sẽ hiệu chỉnh điểm khởi đầu của bạn.',
  'pretestGeneratedCompleteLabel': 'Đã tạo xong bài kiểm tra đầu vào!',
  'openingAdaptivePretestLabel': 'Đang mở bài kiểm tra đầu vào thích ứng của bạn.',
  'lowLabel': 'Thấp',
  'highLabel': 'Cao',
  'basedOnYourResponsesLabel': 'Dựa trên câu trả lời của bạn.',
  'whatsNextLabel': 'Tiếp theo là gì',
  'retakePretestAnytimeLabel': 'Bạn có thể làm lại bài kiểm tra đầu vào bất cứ lúc nào.',
  'currentTopicLabel': 'Chủ đề hiện tại',
  'askOrReflectHereHint': 'Đặt câu hỏi hoặc suy ngẫm tại đây...',
  'speechReadAloud': 'Đọc to',
  'speechReadAloudHint': 'Đọc nội dung này bằng giọng nói',
  'speechStop': 'Dừng đọc',
  'speechStopHint': 'Dừng giọng nói hoặc nhập liệu bằng giọng đang hoạt động',
  'speechPause': 'Tạm dừng',
  'speechResume': 'Tiếp tục',
  'speechSpeed': 'Tốc độ đọc',
  'speechSpeedValue': '{0} lần',
  'speechVoiceInput': 'Nhập bằng giọng nói',
  'speechVoiceInputHint': 'Bắt đầu hoặc dừng ghi âm',
  'speechListening': 'Đang nghe...',
  'speechProcessing': 'Đang xử lý...',
  'speechSpeaking': 'Đang đọc',
  'speechPaused': 'Đã tạm dừng đọc',
  'speechError': 'Lỗi giọng nói',
  'speechMicPermissionDenied': 'Quyền micro bị từ chối',
  'speechMicPermissionInstructions': 'Bật quyền micro trong cài đặt thiết bị để dùng nhập bằng giọng nói.',
  'speechServiceUnavailable': 'Dịch vụ giọng nói không khả dụng',
  'correctionMetricsLabel': 'Chỉ số hiệu chỉnh',
  'typeLabel': 'Loại',
  'triggerLabel': 'Yếu tố kích hoạt',
  'allFilterLabel': 'tất cả',
  'noAiOutputsMatchFiltersLabel': 'Hiện không có kết quả AI nào khớp với các bộ lọc này.',
  'noSummaryLabel': '(không có tóm tắt)',
  'itemNotFoundLabel': 'Không tìm thấy mục.',
  'approveThisOutputLabel': 'Duyệt kết quả này',
  'rejectThisOutputLabel': 'Từ chối kết quả này',
  'optionalNoteHint': 'Ghi chú tùy chọn',
  'whyIsItWrongHint': 'Vì sao sai? (bắt buộc)',
  'approveLabel': 'Duyệt',
  'rejectLabel': 'Từ chối',
  'correctLabelAction': 'Sửa',
  'approvedLabel': 'Đã duyệt',
  'rejectedLabel': 'Bị từ chối',
  'correctionSavedLabel': 'Đã lưu hiệu chỉnh',
  'correctionFailedLabel': 'Hiệu chỉnh thất bại',
  'resolveSuccessLabel': '{0} · người học không bị ảnh hưởng theo thời gian thực',
  'resolveFailureLabel': '{0} thất bại',
  'flaggedBecauseLabel': 'Được gắn cờ vì: {0}',
  'artifactLabel': 'Sản phẩm',
  'artifactUnavailableLabel': 'Không thể tải sản phẩm gốc (có thể đã bị xóa). Bản ghi xem xét vẫn còn.',
  'generatedQuestionLabel': 'Câu hỏi được tạo',
  'promptLabel': 'Câu lệnh',
  'helperLabel': 'Trợ giúp',
  'optionsLabel': 'Lựa chọn',
  'expectedReasoningLabel': 'Lập luận mong đợi',
  'generationSourceLabel': 'Nguồn tạo sinh',
  'noneLabel': '(không có)',
  'alternativesLabel': 'Phương án khác',
  'candidateCountLabel': '{0} ứng viên',
  'modelLabel': 'Mô hình',
  'isCorrectLabel': 'Đúng chứ?',
  'yesLabel': 'Có',
  'noLabel': 'Không',
  'diagnosticSignalLabel': 'Tín hiệu chẩn đoán',
  'historyLabel': 'Lịch sử',
  'correctArtifactTitle': 'Sửa {0}',
  'saveCorrectionLabel': 'Lưu hiệu chỉnh',
  'artifactNotCorrectableLabel': 'Loại sản phẩm này không thể sửa.',
  'optionsTapCorrectLabel': 'Lựa chọn (chạm vào vòng tròn để đánh dấu đáp án đúng)',
  'optionNumberLabel': 'Lựa chọn {0}',
  'teacherFeedbackLabel': 'Nhận xét của giáo viên',
  'auditNoteLabel': 'Ghi chú (nhật ký kiểm toán)',
  'humanCorrectionRateLabel': 'Tỷ lệ hiệu chỉnh bởi con người',
  'backlogLabel': 'Tồn đọng',
  'oldestBacklogLabel': 'cũ nhất {0}n',
  'noneOpenLabel': 'không có mục đang mở',
  'correctionRateByTypeLabel': 'Tỷ lệ hiệu chỉnh theo loại',
  'triggerPrecisionLabel': 'Độ chính xác của yếu tố kích hoạt',
  'triggerPrecisionDescription': 'Trong số các mục bị gắn cờ, bao nhiêu mục thực sự cần sửa (đã sửa hoặc bị từ chối). Càng cao thì yếu tố kích hoạt càng đáng thời gian của giáo viên.',
  'noResolvedItemsLabel': 'Chưa có mục nào được giải quyết.',
  'lastFourteenDaysLabel': '14 ngày qua',
  'noActivityFourteenDaysLabel': 'Không có hoạt động trong 14 ngày qua.',
  'noMetricsYetLabel': 'Chưa có chỉ số nào.',
  'flagForTeacherLabel': 'Gắn cờ cho giáo viên',
  'flagForTeacherDescription': 'Hãy cho chúng tôi biết điều gì có vẻ sai. Giáo viên sẽ xem lại — việc học của bạn vẫn tiếp tục.',
  'flagReasonHint': 'ví dụ: đáp án được đánh dấu có vẻ sai',
  'sendLabel': 'Gửi',
  'flagSentLabel': 'Đã gửi cho giáo viên xem xét. Cảm ơn bạn!',
  'flagFailedLabel': 'Hiện chưa gửi được cờ đánh dấu.',
  'flaggedLabel': 'Đã gắn cờ',
  'looksWrongLabel': 'Có vẻ sai?',
  'insightsUnavailableLabel': 'Không có thông tin chi tiết',
  'insightsSummaryLabel': '{0} môn học · {1} khái niệm · {2} lượt làm',
  'masteredCountLabel': '{0}/{1} đã thành thạo',
  'masteredLabel': 'Đã thành thạo',
  'attemptsPerDayLabel': 'Lượt làm/ngày',
  'periodLabel': 'Khoảng thời gian:',
  'trendPeriodLabel.month': 'tháng',
  'trendPeriodLabel.all': 'tất cả',
  'notEnoughHistoryLabel': 'Chưa đủ lịch sử.',
  'nothingAtRiskLabel': 'Không có gì rủi ro — làm tốt lắm!',
  'atRiskDetailLabel': '{0} · mức thành thạo {1}{2}',
  'overdueSuffixLabel': ' · trễ {0} ngày',
  'edgeAiSettingsTitle': 'Cài đặt AI cục bộ',
  'edgeAiSettingsSubtitle': 'Cài đặt, khởi tạo và thử nghiệm mô hình LiteRT-LM tại một nơi.',
  'edgeAiHideModelUrlLabel': 'Ẩn URL mô hình',
  'edgeAiShowModelUrlLabel': 'Đổi URL mô hình (nâng cao)',
  'edgeAiModelUrlLabel': 'URL mô hình (.litertlm)',
  'edgeAiInstallingLabel': 'Đang cài đặt...',
  'edgeAiInstallModelLabel': 'Cài đặt mô hình',
  'edgeAiReinstallLabel': 'Cài lại',
  'edgeAiInitializingLabel': 'Đang khởi tạo...',
  'edgeAiInitializeLabel': 'Khởi tạo',
  'edgeAiUnloadLabel': 'Gỡ khỏi bộ nhớ',
  'edgeAiRunningLabel': 'Đang chạy...',
  'edgeAiRunTestPromptLabel': 'Chạy câu lệnh thử',
  'edgeAiDownloadLabel': 'Tải mô hình: {0}',
  'edgeAiDownloadedLabel': 'Đã tải {0}',
  'edgeAiEnterModelUrlLabel': 'Nhập URL mô hình trước.',
  'edgeAiModelAlreadyPresentLabel': 'Mô hình đã có trên thiết bị này ({0}).',
  'edgeAiModelReinstalledLabel': 'Đã cài lại mô hình ({0} trong {1} ms).',
  'edgeAiModelInstalledLabel': 'Đã cài đặt mô hình ({0} trong {1} ms).',
  'edgeAiInstallFailedLabel': 'Cài đặt mô hình thất bại: {0}',
  'edgeAiUnloadedLabel': 'Đã gỡ mô hình khỏi bộ nhớ runtime.',
  'edgeAiUnloadFailedLabel': 'Gỡ mô hình thất bại: {0}',
  'edgeAiInitializeCorruptLabel': 'Khởi tạo thất bại. Thường là do tệp mô hình bị hỏng hoặc không khớp với runtime của thiết bị này. Hãy cài lại rồi khởi tạo lần nữa.',
  'edgeAiInitializeFailedLabel': 'Khởi tạo thất bại: {0}',
  'edgeAiGenerationFailedLabel': 'Tạo sinh cục bộ thất bại: {0}',
  'edgeAiStatusUnavailable': 'không khả dụng',
  'edgeAiModelNotReadyTitle': 'Mô hình cục bộ chưa sẵn sàng',
  'edgeAiModelNotReadyMessage': 'Mô hình AI cục bộ chưa sẵn sàng. Hãy cài đặt và khởi tạo trước khi bắt đầu bài kiểm tra đầu vào.',
  'edgeAiOpenSettingsLabel': 'Mở cài đặt AI cục bộ',
  'edgeAiCheckingReadinessLabel': 'Đang kiểm tra mức sẵn sàng của mô hình AI cục bộ...',
  'edgeAiPickTargetNodeLabel': 'Chọn nút mục tiêu trong Mục tiêu học tập trước khi bắt đầu bài kiểm tra đầu vào.',
  'edgeAiFinishInstallLabel': 'Mô hình cục bộ chưa sẵn sàng. Hoàn tất cài đặt/khởi tạo rồi bắt đầu lại bài kiểm tra đầu vào.',
  'edgeAiModelMissingTitle': 'Chưa cài mô hình AI cục bộ',
  'edgeAiModelMissingMessage': 'Wicara sẽ ổn định hơn khi mô hình LiteRT được tải xuống. Mở cài đặt AI cục bộ ngay?',
  'edgeAiDownloadModelLabel': 'Tải mô hình',
  'edgeAiModelNotInitializedTitle': 'Mô hình AI cục bộ chưa sẵn sàng',
  'edgeAiModelNotInitializedMessage': 'Mô hình đã có trên thiết bị nhưng chưa được khởi tạo. Khởi tạo ngay?',
  'edgeAiOpenSettingsShortLabel': 'Mở cài đặt',
  'edgeAiInitializingModelLabel': 'Đang khởi tạo mô hình cục bộ...',
  'edgeAiModelReadyLabel': 'Mô hình cục bộ đã sẵn sàng sử dụng.',
  'edgeAiInitializedNotReadyLabel': 'Đã khởi tạo xong nhưng runtime chưa sẵn sàng. Hãy thử mở cài đặt AI cục bộ.',
  'edgeAiTestPrompt': 'Trả lời bằng tiếng Việt. Giải thích đạo hàm như một tốc độ biến thiên trong 2 câu, rồi đưa ra 1 câu hỏi kiểm tra hiểu bài.',
  'edgeAiInitializeModelFailedLabel': 'Khởi tạo mô hình thất bại: {0}',
  'tapToOpenLabel': 'Chạm để mở',
  'resetZoomLabel': 'Đặt lại thu phóng',
  'videoFailedToLoadLabel': 'Không tải được video. Hãy thử lại.',
  'videoUrlMissingLabel': 'Thiếu URL video cho sản phẩm này.',
  'videoLoadFailedLabel': 'Không tải được video này.',
  'openFullscreenLabel': 'Mở toàn màn hình',
  'videoPreviewWebOnlyLabel': 'Xem trước video có sẵn trên bản demo web.',
  'penSizeLabel': 'Cỡ bút {0}',
  'penColorLabel': 'Màu bút',
  'saveWorkLabel': 'Lưu bài làm',
  'sendToChatLabel': 'Gửi vào trò chuyện',
  'canvasStatusLabel.draftEmpty': 'Bản nháp trống',
  'canvasStatusLabel.unsavedSketch': 'Bản phác chưa lưu',
  'canvasStatusLabel.unsavedChanges': 'Thay đổi chưa lưu',
  'canvasStatusLabel.sentToChat': 'Đã gửi vào trò chuyện',
  'canvasStatusLabel.default': 'Đã lưu, sẵn sàng gửi',
  'canvasClearTitle': 'Xóa canvas?',
  'canvasClearMessage': 'Thao tác này xóa bản phác hiện tại và ghi chú giấy đính kèm.',
  'canvasLabel': 'Canvas',
  'canvasWorkspaceLabel': 'Không gian làm việc canvas',
  'canvasLargeHint': 'Dùng không gian rộng hơn cho sơ đồ và ghi chú.',
  'canvasSmallHint': 'Hãy trình bày lập luận trước khi nộp.',
  'canvasClosePanelLabel': 'Đóng bảng',
  'canvasLargerPanelLabel': 'Bảng lớn hơn',
  'canvasResetViewLabel': 'Đặt lại khung nhìn',
  'canvasHideGridLabel': 'Ẩn lưới',
  'canvasShowGridLabel': 'Hiện lưới',
  'canvasClearLabel': 'Xóa canvas',
  'canvasUploadImageLabel': 'Tải ảnh lên',
  'canvasKeepLabel': 'Giữ lại',
  'canvasClearShortLabel': 'Xóa',
  'canvasViewSectionLabel': 'Xem',
  'canvasEditSectionLabel': 'Chỉnh sửa',
  'canvasZoomOutLabel': 'Thu nhỏ',
  'canvasZoomInLabel': 'Phóng to',
  'canvasPenLabel': 'Bút',
  'canvasPenTooltip': 'Chế độ bút',
  'canvasHandLabel': 'Tay',
  'canvasHandTooltip': 'Chế độ tay',
  'canvasEraseLabel': 'Tẩy',
  'canvasEraseTooltip': 'Chế độ tẩy',
  'canvasShapeLabel': 'Hình',
  'canvasShapeTooltip': 'Trợ giúp vẽ hình',
  'canvasLineShapeLabel': 'Hình đường thẳng',
  'canvasArrowShapeLabel': 'Hình mũi tên',
  'canvasRectangleShapeLabel': 'Hình chữ nhật',
  'canvasPaperAttachedLabel': 'Bài làm trên giấy\nđã đính kèm',
  'canvasEmptyHintLabel': 'Phác thảo công thức, sơ đồ hoặc các bước làm tại đây.',
  'preparingAdaptiveQuestionsLabel': 'Đang chuẩn bị câu hỏi thích ứng...',
  'noLocalQuestionLabel': 'Bộ tạo bài kiểm tra đầu vào cục bộ không trả về câu hỏi nào.',
  'chooseAnswerBeforeReasoningLabel': 'Chọn đáp án trước khi thêm phần trình bày.',
  'imageUnreadableLabel': 'Không đọc được tệp ảnh.',
  'imageTooLargeLabel': 'Ảnh phải có dung lượng tối đa 10 MB.',
  'adaptiveProbingLabel': 'Thăm dò thích ứng  •  Lý thuyết Không gian Tri thức',
  'missingPrerequisiteSkillLabel': 'Thiếu kiến thức tiên quyết: các yếu tố nguyên nhân',
  'missingPrerequisiteMessageLabel': 'Lỗ hổng có vẻ là chọn công cụ trước khi nêu tên yếu tố gây lỗi, bằng chứng và chuỗi nguyên nhân có khả năng.',
  'improvedLabel': 'Cải thiện',
  'stagnantLabel': 'Chững lại',
  'reviewDueConceptsLabel': 'Ôn các khái niệm đến hạn',
  'dueThisWeekLabel': 'Đến hạn tuần này',
  'preVsPostTestLabel': 'Kiểm tra trước và sau',
  'weeklyNarrativeLabel': 'Tường thuật hằng tuần',
  'focusLabel': 'Trọng tâm',
  'answerScoredByAiLabel': 'Câu trả lời được AI chấm điểm.',
  'scoringOffLabel': 'Chấm điểm sai?',
  'laterLabel': 'Để sau',
  'trackWithoutModuleLabel': 'Đã tạo lộ trình, nhưng chưa có mô-đun không gian làm việc nào.',
  'workspaceAutoOpenFailedLabel': 'Không thể tự động mở không gian làm việc sau bài kiểm tra đầu vào.',
  'retentionLiftShortLabel': 'Mức tăng ghi nhớ',
  'remainingLabel': 'Còn lại',
  'weeklyReportLabel': 'Báo cáo hằng tuần',
  'retentionLabel': 'Ghi nhớ',
  'posttestMasteryCheckLabel': 'Kiểm tra mức thành thạo sau bài học',
  'noSubjectsSelectedLabel': 'Chưa chọn môn học nào',
  'thisWeekLabel': 'Tuần này',
  'consistencyCompoundingLabel': 'Sự đều đặn đang cộng dồn.',
  'serverTimeoutLabel': 'Máy chủ WICARA phản hồi quá lâu. Vui lòng thử lại.',
  'uploadTimeoutLabel': 'Máy chủ WICARA tải ảnh lên quá lâu. Vui lòng thử lại.',
  'serverUnreachableLabel': 'Không thể kết nối tới máy chủ WICARA tại {0}. {1}',
  'loginBeforeDashboardLabel': 'Vui lòng đăng nhập trước khi mở bảng điều khiển.',
  'loginBeforeOnboardingLabel': 'Vui lòng đăng nhập trước khi bắt đầu onboarding.',
  'loginBeforeWorkspaceLabel': 'Vui lòng đăng nhập trước khi mở không gian làm việc.',
  'loginBeforeTrackLabel': 'Vui lòng đăng nhập trước khi tạo lộ trình.',
  'noMatchingGoalLabel': 'Không tìm thấy mục tiêu học tập phù hợp.',
  'noImageAssetIdLabel': 'Máy chủ không trả về id tài nguyên ảnh.',
  'activeGoalConflictLabel': 'Bạn đã có mục tiêu đang hoạt động cho "{0}". ',
  'signInFailedLabel': 'Đăng nhập thất bại: {0}',
  'registrationFailedLabel': 'Đăng ký thất bại: {0}',
  'googleSignInFailedLabel': 'Đăng nhập Google thất bại: {0}',
  'googleSignInCancelledLabel': 'Đã hủy đăng nhập Google.',
  'createGoalBeforePretestLabel': 'Hãy tạo mục tiêu học tập trước khi mở bài kiểm tra đầu vào.',
  'invalidPretestQuestionLabel': 'Backend trả về câu hỏi kiểm tra đầu vào không hợp lệ.',
  'chooseAnswerFirstLabel': 'Chọn đáp án trước khi tiếp tục.',
  'noNextQuestionLabel': 'Backend không trả về câu hỏi tiếp theo hoặc chẩn đoán.',
  'invalidEvidenceImageLabel': 'Backend trả về ảnh bằng chứng không hợp lệ.',
  'createGoalBeforePathLabel': 'Hãy tạo mục tiêu học tập trước khi chọn lộ trình.',
  'loginBeforePretestLabel': 'Vui lòng đăng nhập trước khi làm bài kiểm tra đầu vào.',
  'openPretestBeforeSubmitLabel': 'Hãy mở bài kiểm tra đầu vào đã tạo trước khi nộp.',
  'pathSelectedLabel': 'Đã chọn lộ trình',
  'adaptivePathReadyLabel': 'Lộ trình học thích ứng của bạn đã sẵn sàng.',
  'continueSelectedPathLabel': 'Tiếp tục với lộ trình đã chọn.',
  'modulesCountLabel': '{0} mô-đun',
  'adaptiveDiagnosisLabel': 'Chẩn đoán thích ứng',
  'adaptivePretestCompleteLabel': 'Hoàn thành bài kiểm tra đầu vào thích ứng',
  'scoreMetaLabel': 'Điểm {0}%',
  'correctCountMetaLabel': 'Đúng {0}/{1}',
  'pathDescriptionLabel.review_only': 'Bắt đầu bằng phần ôn ngắn và luyện tập nâng cao.',
  'pathDescriptionLabel.target_reinforcement': 'Luyện khái niệm mục tiêu ở mức trung bình và khó.',
  'pathDescriptionLabel.target_intro': 'Bắt đầu từ phần giới thiệu khái niệm mục tiêu.',
  'pathDescriptionLabel.repair_prerequisites': 'Khắc phục các lỗ hổng tiên quyết trước khi quay lại mục tiêu.',
  'pathDescriptionLabel.full_foundation_path': 'Xây dựng lại nền tảng sâu hơn trước.',
  'pathDescriptionLabel.default': 'Học khái niệm mục tiêu từ căn bản.',
  'questionProgressLabel': 'Câu hỏi {0} trên {1}',
  'conceptNotFoundLabel': 'Không tìm thấy khái niệm trong chương trình học cục bộ.',
  'conceptCodeNotFoundLabel': 'Không tìm thấy khái niệm "{0}" trong chương trình học cục bộ.',
  'evidenceUploadNeedsBackendLabel': 'Tải ảnh bằng chứng lên cần chế độ kiểm tra đầu vào qua backend.',
  'emptyPathOptionLabel': 'Lựa chọn lộ trình không được để trống.',
  'localDiagnosisUnavailableLabel': 'Chẩn đoán cục bộ chưa có. Hãy hoàn thành bài kiểm tra đầu vào trước.',
  'localPretestStateInvalidLabel': 'Trạng thái bài kiểm tra đầu vào cục bộ không hợp lệ.',
  'localPretestSessionInvalidLabel': 'Phiên kiểm tra đầu vào cục bộ không hợp lệ.',
  'questionMismatchLabel': 'Câu hỏi không khớp. Hãy tải lại bài kiểm tra đầu vào và thử lại.',
  'optionNotFoundLabel': 'Không tìm thấy lựa chọn đã chọn cho câu hỏi này.',
  'offlineCurriculumMissingLabel': 'Chương trình học ngoại tuyến không có trên thiết bị này.',
  'targetConceptNotChosenLabel': 'Chưa chọn khái niệm mục tiêu. Hãy mở Mục tiêu học tập và chọn nút mục tiêu trước.',
  'targetConceptNotFoundLabel': 'Không tìm thấy khái niệm mục tiêu "{0}" trong chương trình học cục bộ.',
  'backendPretestNotConfiguredLabel': 'Kho lưu trữ kiểm tra đầu vào backend chưa được cấu hình.',
  'chooseBestAnswerLabel': 'Chọn đáp án tốt nhất cho {0}.',
  'reviewWorkingStepsLabel': 'Xem lại các bước làm để xác nhận lựa chọn đáp án của bạn.',
  'emptyTopicLabel': 'Chủ đề học tập không được để trống.',
  'noMatchingConceptLabel': 'Chưa có khái niệm phù hợp. Hãy thử thêm từ khóa cụ thể hơn.',
  'searchAllSubjectsLabel': 'Đã tìm trên tất cả môn học cục bộ.',
  'searchLimitedSubjectLabel': 'Tìm kiếm giới hạn trong môn học đã chọn.',
  'resolutionNotFoundLabel': 'Không tìm thấy kết quả phân giải. Hãy tìm lại nút mục tiêu.',
  'resolutionMissingLabel': 'Không tìm thấy kết quả phân giải.',
  'noTargetNodeLabel': 'Chưa chọn nút mục tiêu cho bài kiểm tra đầu vào.',
  'noMatchingConceptRetryLabel': 'Không tìm thấy khái niệm phù hợp. Hãy thử truy vấn khác.',
  'localCurriculumMissingLabel': 'Chương trình học cục bộ chưa có. Hãy đồng bộ chương trình học trước.',
  'localNodeNotFoundLabel': 'Không tìm thấy nút "{0}" trong chương trình học cục bộ.',
  'targetConceptFallbackTitle': 'Khái niệm mục tiêu',
  'tutorHintDerivativeLabel': 'Gợi ý: hãy xem giá trị hàm số thay đổi thế nào khi x dịch nhẹ, rồi so sánh hai điểm rất gần nhau.',
  'tutorHintGenericLabel': 'Gợi ý: chia bài toán thành ba bước nhỏ, kiểm tra giả định ở mỗi bước, rồi giải lần lượt.',
  'tutorEvaluateCloseLabel': 'Các bước của bạn đã gần đúng. Bây giờ hãy giải thích vì sao quy tắc đó áp dụng cho dạng bài này.',
  'tutorEvaluateInconsistentLabel': 'Câu trả lời của bạn chưa nhất quán. Hãy kiểm tra lại bước đầu tiên, rồi viết lại lý do cho từng phép biến đổi.',
  'reasoningTooShortLabel': 'Lập luận của bạn còn quá ngắn; hãy bổ sung lý do bạn chọn phép toán đó.',
  'reasoningClearLabel': 'Lập luận của bạn rõ ràng về cấu trúc; giờ hãy củng cố bằng một ví dụ số ngắn.',
  'quizPromptLabel': "Thử xem: nếu f(x)=x^2 thì đạo hàm f'(x) là gì, và vì sao?",
  'summaryFallbackLabel': 'Tóm lại: tập trung vào khái niệm cốt lõi, một quy tắc chính và một lỗi thường gặp cần tránh.',
  'explainDerivativeLabel': 'Đạo hàm mô tả giá trị hàm số thay đổi nhanh thế nào theo x. Hãy hình dung đó là hệ số góc của tiếp tuyến tại một điểm trên đường cong.',
  'explainGenericLabel': 'Chúng ta bắt đầu từ định nghĩa cốt lõi, chuyển sang một ví dụ ngắn, rồi kiểm tra lại bằng một câu hỏi xác minh.',
  'heuristicReasoningFeedback': 'Lập luận được chấm bằng heuristic cục bộ vì chưa có đánh giá LiteRT.',
  'carelessMistakeFeedback': 'Câu trắc nghiệm sai, nhưng có tín hiệu lập luận một phần khá mạnh.',
  'partialReasoningFeedback': 'Lập luận một phần, nhưng chưa đủ để hỗ trợ đáp án.',
  'unrelatedReasoningFeedback': 'Lập luận chưa liên quan trực tiếp đến khái niệm cốt lõi.',
  'diagnosisSummaryLabel.review_only': 'Bạn đã sẵn sàng với {0}; chỉ cần ôn ngắn là đủ.',
  'diagnosisSummaryLabel.target_reinforcement': 'Bạn hiểu căn bản của {0}, nhưng cần luyện tập khó hơn.',
  'diagnosisSummaryLabel.target_from_basics': '{0} đang hình thành, nhưng chưa ổn định ở mức trung bình.',
  'diagnosisSummaryLabel.target_intro': '{0} vẫn là lỗ hổng chính; hãy bắt đầu từ phần giới thiệu khái niệm.',
  'diagnosisSummaryLabel.repair_prerequisites': 'Một số kiến thức tiên quyết cho {0} cần được củng cố trước.',
  'diagnosisSummaryLabel.full_foundation_path': 'Nền tảng trước {0} cần được xây lại từ những kiến thức tiên quyết sâu nhất.',
  'diagnosisSummaryLabel.default': 'Đã hoàn tất chẩn đoán cho {0}.',
  'diagnosisFocusLabels.review_only.0': 'Tóm tắt lại khái niệm mục tiêu',
  'diagnosisFocusLabels.review_only.1': 'Làm 1-2 câu củng cố nhẹ',
  'diagnosisFocusLabels.target_reinforcement.0': 'Luyện mức trung bình đến khó trên mục tiêu',
  'diagnosisFocusLabels.target_reinforcement.1': 'Nâng cao chất lượng lập luận viết',
  'diagnosisFocusLabels.target_from_basics.0': 'Làm lại nền tảng ngay trước mục tiêu',
  'diagnosisFocusLabels.target_from_basics.1': 'Luyện dần từ dễ đến trung bình',
  'diagnosisFocusLabels.target_intro.0': 'Bắt đầu từ phần giới thiệu khái niệm mục tiêu',
  'diagnosisFocusLabels.target_intro.1': 'Dùng ví dụ cụ thể trước khi dùng ký hiệu',
  'diagnosisFocusLabels.repair_prerequisites.0': 'Củng cố các nút tiên quyết yếu hoặc còn thiếu',
  'diagnosisFocusLabels.repair_prerequisites.1': 'Quay lại mục tiêu khi kiến thức tiên quyết đã vững',
  'diagnosisFocusLabels.full_foundation_path.0': 'Xây lại từ những kiến thức tiên quyết sâu nhất',
  'diagnosisFocusLabels.full_foundation_path.1': 'Leo dần theo độ sâu của đồ thị',
  'offlineWritingNotesLabel': 'AI đang viết ghi chú cá nhân cho bạn...',
  'offlineSessionNotFoundLabel': 'Không tìm thấy phiên kiểm tra đầu vào.',
  'offlineInvalidStateLabel': 'Trạng thái bài kiểm tra đầu vào không hợp lệ.',
  'offlineNotesReadyLabel': 'Ghi chú AI cá nhân của bạn đã sẵn sàng.',
  'offlineNotesFailedLabel': 'AI không thể viết ghi chú cá nhân cho phiên này.',
  'offlineRuntimeNotReadyLabel': 'Mô hình LiteRT chưa sẵn sàng hoặc chưa được cài. Đang dùng bản dự phòng cục bộ.',
  'offlineGeneratingAttemptLabel': 'Đang tạo câu hỏi cục bộ (lần {0}/{1}, giới hạn {2}s)...',
  'offlineOutputInvalidLabel': 'Kết quả mô hình chưa hợp lệ, đang thử lại ({0}/{1}).',
  'offlineValidLevelsLabel': 'Mô hình đã tạo {0} cấp độ hợp lệ ({1}).',
  'offlineAttemptTimeoutLabel': 'Lần thử {0} đã hết thời gian ({1}s). Đang thử lại...',
  'offlineAttemptFailedLabel': 'Lần thử {0} thất bại: {1}. Tiếp tục với lần thử kế tiếp.',
  'offlineGenerationDoneLabel': 'Đã tạo xong câu hỏi.',
  'offlineGenerationPartialLabel': 'Một số câu hỏi hợp lệ. Đã bỏ qua: {0}.',
  'offlineGenerationFailedLabel': 'Tạo câu hỏi thất bại. Đang dùng mẫu dự phòng.',
  'offlineGenerationFallbackLabel': 'Tạo câu hỏi cục bộ thất bại. Đang dùng mẫu dự phòng.',
  'offlinePreparingModelLabel': 'Đang chuẩn bị mô hình cục bộ...',
  'devModeLabel': 'Chế độ Dev',
  'devBypassTitle': 'Bỏ qua dành cho nhà phát triển',
  'devBypassSubtitle': 'Bỏ qua xác thực thật trong bản debug.',
  'devOnboardingIncompleteLabel': 'Đã đăng nhập, nhưng chưa hoàn tất onboarding.',
  'startAtOnboardingLabel': 'Bắt đầu từ onboarding',
  'jumpToHomeLabel': 'Đi thẳng tới trang chủ',
  'devSignedInLabel': 'Đã đăng nhập và đánh dấu hoàn tất onboarding.',
  'demoLimitsFromGraphsTitle': 'Giới hạn từ đồ thị',
  'demoLimitsFromGraphsReason': 'Vì sao bây giờ? Điều này mở khóa tính liên tục và\ntrực giác về đạo hàm bậc nhất.',
  'demoDerivativeRulesTitle': 'Quy tắc đạo hàm',
  'demoFunctionCompositionTitle': 'Ôn tập hợp thành hàm số',
  'demoContinueCalculusTitle': 'Tiếp tục Giải tích I',
  'demoContinueCalculusSubtitle': 'Giới hạn, đạo hàm, ứng dụng',
  'demoLinearAlgebraTitle': 'Đại số tuyến tính',
  'demoLinearAlgebraSubtitle': 'Vectơ, ma trận, phép biến đổi',
  'demoDiscreteMathTitle': 'Toán rời rạc',
  'demoDiscreteMathSubtitle': 'Logic, tập hợp, đồ thị, đếm',
  'demoDerivativesIntuitionTitle': 'Trực giác về đạo hàm',
  'demoDerivativesIntuitionSubtitle': 'Đạo hàm cho ta biết điều gì?',
  'demoLimitsFromGraphsSubtitle': 'Tiến gần một giá trị mà không chạm tới nó',
  'demoCalculusOneLabel': 'Giải tích I',
  'demoCalculusLabel': 'Giải tích',
  'demoDerivativeRulesReason': 'Vì sao bây giờ? Bạn đã sẵn sàng sau phần giới hạn và\ncách hiểu hệ số góc.',
  'demoFunctionCompositionReason': 'Vì sao bây giờ? Cần trước quy tắc chuỗi và\nvi phân ẩn.',
  'demoLessonMetaLabel': '{0} phút   •   {1}',
  'reviewNowShortLabel': 'Ôn tập',
  'demoCurrentTrackMeta': 'Lộ trình hiện tại   •   hoàn thành {0}%',
  'demoCreatedTrackMeta': 'Lộ trình đã tạo   •   hoàn thành {0}%',
  'demoCreatedTrackReadyMeta': 'Lộ trình đã tạo   •   sẵn sàng tiếp tục',
  'gradeValue': 'Lớp {0}',
  'subjectLabel.Math': 'Toán',
  'subjectLabel.Matematika': 'Toán',
  'subjectLabel.Physics': 'Vật lý',
  'subjectLabel.Fisika': 'Vật lý',
  'subjectLabel.Chemistry': 'Hóa học',
  'subjectLabel.Kimia': 'Hóa học',
  'subjectLabel.Biology': 'Sinh học',
  'subjectLabel.Biologi': 'Sinh học',
  'subjectLabel.Science': 'Khoa học',
  'subjectLabel.IPA': 'Khoa học',
  'subjectLabel.IPAS': 'Khoa học',
  'subjectDescription.Math': 'Đại số, Hình học, Giải tích',
  'subjectDescription.Physics': 'Cơ học, Sóng, Nhiệt',
  'subjectDescription.Chemistry': 'Hóa lượng, Phản ứng',
  'subjectDescription.Biology': 'Tế bào, Di truyền, Sinh thái',
  'difficultyLabel.easy': 'Dễ',
  'difficultyLabel.medium': 'Trung bình',
  'difficultyLabel.hard': 'Khó',
  'estimatedDurationLabel': 'Ước tính {0}   •   {1}',
  'layerLabel': 'Lớp {0}',
  'nodeStatusLabel.MASTERED': 'ĐÃ THÀNH THẠO',
  'nodeStatusLabel.REVIEW': 'CẦN ÔN',
  'nodeStatusLabel.READY': 'SẴN SÀNG',
  'nodeStatusLabel.GAP': 'LỖ HỔNG',
  'nodeStatusLabel.LOCKED': 'ĐÃ KHÓA',
  'weekShortLabels': 'CN|T2|T3|T4|T5|T6|T7',
  'diagnosisPromptInstructions': '\nWrite a diagnosis of the learner\'s pretest in Vietnamese (tiếng Việt). Not a summary, not encouragement - a DIAGNOSIS.\nEvery field of the JSON output must be written in Vietnamese (tiếng Việt).\nUse ONLY the data in "nodes" below.\nTone: casual, addressed directly to the learner ("You ..."), no jargon.\nIf siswa_pakai_canvas=true, mention that the learner wrote or sketched while working (an effort signal).\n\nRules for each field:\n- "summary" (2-3 sentences, roughly 80-120 words):\n  name the specific target concept + 1 thing already understood (cite a correct question) + 1 thing still missing (cite a wrong question).\n  Avoid motivational lines.\n- "strengths" (1-3 points, each 1-2 full sentences):\n  format: "On the question about [core of the question], you [correct step]."\n  Cite reasoning_siswa whenever it is available.\n- "gaps" (1-3 points, each 2-3 full sentences):\n  format: "On the question about [core of the question], you chose [siswa_pilih] when the answer was [jawaban_benar]. [Contrast reasoning_siswa with expected_reasoning or explain the error]."\n- "evidence_notes" (0-2 points):\n  describe concrete cross-question patterns (e.g. empty reasoning on hard questions, canvas effort appearing, etc).\n- "recommended_focus" (1-3 points):\n  concrete practice that directly fixes the gap (name the sub-topic, not "practice more").\n\nFORBIDDEN: generic lines ("needs more practice", "the concept is weak").\nAlways reference the actual question content from the data.',
  'offlineQuestionPromptInstructions': '\nWrite short adaptive pretest questions in Vietnamese (tiếng Việt).\nEvery question, option, and explanation must be written in Vietnamese (tiếng Việt).\nOnly output these difficulty keys: {0}.\nEvery question must have 4 unique options and exactly 1 correct answer.\nAvoid long explanations. Keep it concise.\nThe "explanation" field MUST be concrete numbered steps (e.g. "1) ... 2) ... 3) ..."),\nnot a general definition of the concept.',
  'diagnosisSystemPrompt': "You are WICARA's on-device pretest diagnostic writer. Write a specific narrative in Vietnamese (tiếng Việt), grounded in the given questions and the learner's answers, not generalities. Output valid JSON only.",
  'knowledgeGraph.Mathematics Prerequisite Map': 'Bản đồ kiến thức tiên quyết Toán học',
  'knowledgeGraph.Knowledge Map': 'Bản đồ kiến thức',
  'knowledgeGraph.Primary Math': 'Toán tiểu học',
  'knowledgeGraph.Lower Secondary': 'Trung học cơ sở',
  'knowledgeGraph.Algebra and Functions': 'Đại số và Hàm số',
  'knowledgeGraph.Precalculus': 'Tiền giải tích',
  'knowledgeGraph.Limits and Continuity': 'Giới hạn và Tính liên tục',
  'knowledgeGraph.Calculus 1': 'Giải tích 1',
  'knowledgeGraph.Calculus 2': 'Giải tích 2',
  'knowledgeGraph.Calculus 3': 'Giải tích 3',
  'knowledgeGraph.Counting': 'Đếm số',
  'knowledgeGraph.Place Value': 'Giá trị theo vị trí',
  'knowledgeGraph.Arithmetic Operations': 'Các phép toán số học',
  'knowledgeGraph.Fractions and Decimals': 'Phân số và Số thập phân',
  'knowledgeGraph.Basic Shapes and Measurement': 'Hình cơ bản và Đo lường',
  'knowledgeGraph.Tables, Charts, and Mean': 'Bảng, Biểu đồ và Số trung bình',
  'knowledgeGraph.Integers and Rational Numbers': 'Số nguyên và Số hữu tỉ',
  'knowledgeGraph.Exponents and Roots Basics': 'Cơ bản về Lũy thừa và Căn',
  'knowledgeGraph.Linear Equations': 'Phương trình tuyến tính',
  'knowledgeGraph.Coordinate Graphing': 'Vẽ đồ thị tọa độ',
  'knowledgeGraph.Slope and Intercepts': 'Hệ số góc và Giao điểm trục',
  'knowledgeGraph.Pythagorean Theorem': 'Định lý Pythagoras',
  'knowledgeGraph.Functions, Domain, and Range': 'Hàm số, Tập xác định và Tập giá trị',
  'knowledgeGraph.Function Composition and Inverses': 'Hợp hàm và Hàm ngược',
  'knowledgeGraph.Exponential and Logarithmic Functions': 'Hàm mũ và Hàm lôgarit',
  'knowledgeGraph.Quadratic and Polynomial Functions': 'Hàm bậc hai và Hàm đa thức',
  'knowledgeGraph.Rational Functions': 'Hàm phân thức',
  'knowledgeGraph.Sequences, Series, Sigma Notation': 'Dãy số, Chuỗi, Ký hiệu Sigma',
  'knowledgeGraph.Analytic Geometry and Conics': 'Hình học giải tích và Đường conic',
  'knowledgeGraph.Trigonometric Functions and Graphs': 'Hàm lượng giác và Đồ thị',
  'knowledgeGraph.Trigonometric Identities and Equations': 'Đẳng thức và Phương trình lượng giác',
  'knowledgeGraph.Vectors, Parametric, and Polar Basics': 'Cơ bản về Vectơ, Tham số và Tọa độ cực',
  'knowledgeGraph.Precalculus Fluency': 'Thành thạo Tiền giải tích',
  'knowledgeGraph.Intuitive Limits': 'Giới hạn theo trực giác',
  'knowledgeGraph.Limit Laws and Algebraic Techniques': 'Các định luật giới hạn và Kỹ thuật đại số',
  'knowledgeGraph.Trigonometric Limits and Squeeze Theorem': 'Giới hạn lượng giác và Định lý kẹp',
  'knowledgeGraph.Continuity and Intermediate Value Theorem': 'Tính liên tục và Định lý giá trị trung gian',
  'knowledgeGraph.Derivative Definition': 'Định nghĩa đạo hàm',
  'knowledgeGraph.Derivative Rules': 'Quy tắc đạo hàm',
  'knowledgeGraph.Chain Rule and Implicit Differentiation': 'Quy tắc chuỗi và Vi phân ẩn',
  'knowledgeGraph.Related Rates, Optimization, Curve Sketching': 'Tốc độ liên hệ, Tối ưu hóa, Vẽ phác đường cong',
  'knowledgeGraph.Antiderivatives, Riemann Sums, Definite Integrals': 'Nguyên hàm, Tổng Riemann, Tích phân xác định',
  'knowledgeGraph.Fundamental Theorem of Calculus': 'Định lý cơ bản của giải tích',
  'knowledgeGraph.Integration Techniques': 'Các kỹ thuật tích phân',
  'knowledgeGraph.Area, Volume, Work, Fluid Force': 'Diện tích, Thể tích, Công, Lực chất lỏng',
  'knowledgeGraph.Convergence Tests and Power Series': 'Các tiêu chuẩn hội tụ và Chuỗi lũy thừa',
  'knowledgeGraph.Parametric and Polar Calculus': 'Giải tích tham số và tọa độ cực',
  'knowledgeGraph.3D Coordinates and Vector Operations': 'Tọa độ 3D và Các phép toán vectơ',
  'knowledgeGraph.Partial Derivatives and Gradients': 'Đạo hàm riêng và Gradient',
  'knowledgeGraph.Double and Triple Integrals': 'Tích phân bội hai và bội ba',
  'knowledgeGraph.Vector Fields, Line Integrals, Green, Stokes, Divergence': 'Trường vectơ, Tích phân đường, Green, Stokes, Divergence',
  'workspace.topicTitle': 'Chủ đề học tập',
  'workspace.startChatTitle': 'Bắt đầu học',
  'workspace.startChatBody': 'Gia sư sẽ hướng dẫn bạn dựa trên chẩn đoán và giai đoạn học được lưu ở backend.',
  'workspace.startChatButtonLabel': 'Bắt đầu trò chuyện học tập',
  'workspace.loadingDescription': 'Đang kết nối mô-đun này với ngữ cảnh học tập ở backend.',
  'workspace.syncedDescription': 'Cuộc trò chuyện, canvas, phương tiện và trạng thái giai đoạn được đồng bộ với backend.',
  'workspace.workspaceTitleLabel': 'Không gian làm việc',
  'workspace.newChatLabel': 'Trò chuyện mới',
  'workspace.chatHistoryTitle': 'Lịch sử trò chuyện',
  'workspace.advancePhaseLabel': 'Sang giai đoạn tiếp theo',
  'workspace.advancingPhaseLabel': 'Đang chuyển giai đoạn...',
  'workspace.phaseTransitionHint': 'Giai đoạn này đã hoàn tất. Tiếp tục học ở đây cho đến khi bạn sẵn sàng.',
  'workspace.phaseCheckpointPrompt': 'Bạn đã hoàn thành {0}. Bạn đã sẵn sàng tiếp tục sang {1} chưa?',
  'workspace.confirmPhaseLabel': 'Có, tiếp tục',
  'workspace.stayInPhaseLabel': 'Chưa',
  'workspace.startPosttestButtonLabel': 'Bắt đầu Posttest',
  'workspace.posttestReadyBody': 'Bắt đầu posttest ngay? Thao tác này sẽ hoàn tất mô-đun không gian làm việc và chuẩn bị phiên posttest.',
  'workspace.cancelLabel': 'Hủy',
  'workspace.startPosttestDialogLabel': 'Bắt đầu posttest',
  'workspace.posttestUnavailableMessage': 'Posttest chưa sẵn sàng. Hãy tiếp tục theo hướng dẫn của gia sư.',
  'workspace.workspaceNotReadyMessage': 'Không gian làm việc chưa sẵn sàng.',
  'workspace.openTrackModuleMessage': 'Hãy mở mô-đun lộ trình từ Trang chủ hoặc Hàng chờ trước khi dùng không gian làm việc.',
  'workspace.chatLoadingMessage': 'Phiên trò chuyện vẫn đang tải.',
  'workspace.connectingWorkspaceMessage': 'Đang kết nối tới không gian làm việc backend...',
  'workspace.savingEvidenceMessage': 'Đang lưu bằng chứng không gian làm việc...',
  'workspace.queueingVideoMessage': 'Đang xếp hàng tạo video...',
  'workspace.videoQueuedMessage': 'Video đã vào hàng chờ. Đang đợi worker...',
  'workspace.videoTimedOutMessage': 'Tạo video đã hết thời gian sau {0} phút.',
  'workspace.generationTimeoutMessage': 'Hết thời gian tạo.',
  'workspace.buildingScenesMessage': 'Đang dựng cảnh, lời dẫn và kết xuất...',
  'workspace.generatingVideoTitle': 'Đang tạo video',
  'workspace.generatedVideoFallbackTitle': 'Video đã tạo',
  'workspace.savedGeneratedVideoTitle': 'Video đã lưu',
  'workspace.generatedVideoSubtitle': 'Đã kết xuất xong video và sẵn sàng trong không gian làm việc của bạn.',
  'workspace.aiVideoChip': 'Video AI',
  'workspace.readyUrlChip': 'URL sẵn sàng',
  'workspace.playGeneratedVideoLabel': 'Phát video',
  'workspace.videoUrlUnavailableLabel': 'URL video không khả dụng',
  'workspace.videoGenerationFailedTitle': 'Tạo video thất bại',
  'workspace.videoGenerationFailedMessage': 'Tạo video thất bại.',
  'workspace.retryGenerateVideoLabel': 'Thử tạo video lại',
  'workspace.generatingVideoButtonLabel': 'Đang tạo video...',
  'workspace.generateVideoFromChatLabel': 'Tạo video từ cuộc trò chuyện này',
  'workspace.generatingVideoContextMessage': 'Đang tạo video từ ngữ cảnh cuộc trò chuyện gần nhất của bạn...',
  'workspace.videoReadyMessage': 'Video đã sẵn sàng. Bạn có thể phát từ thẻ trò chuyện mới nhất.',
  'workspace.failedToLoadVideoMessage': 'Không tải được video từ URL backend.',
  'workspace.openFullscreenTooltip': 'Mở toàn màn hình',
  'workspace.durationChipLabel': 'Thời lượng {0}',
  'workspace.canvasAttachedPrompt': 'Bài làm trên canvas đã được đính kèm. Thêm bản phác khác nếu cần.',
  'workspace.canvasPrompt': 'Cần bảng trắng? Hãy mở canvas và gửi bản phác của bạn tại đây.',
  'workspace.openCanvasLabel': 'Mở canvas',
  'workspace.useCanvasLabel': 'Dùng canvas',
  'workspace.canvasSentLabel': 'Đã gửi canvas',
  'workspace.explanationCardLabel': 'Thẻ giải thích',
  'workspace.evidenceRequestLabel': 'Bằng chứng được yêu cầu',
  'workspace.nextActionsLabel': 'Hành động tiếp theo',
  'workspace.canvasSnapshotSentLabel': 'Đã gửi ảnh chụp canvas',
  'workspace.canvasSnapshotSentCountLabel': 'Đã gửi ảnh chụp canvas ({0} nét)',
  'workspace.canvasMarksLabel': '{0} nét',
  'workspace.canvasMarksAttachedLabel': '{0} nét - có đính kèm giấy',
  'workspace.historyButtonLabel': 'Lịch sử ({0})',
  'workspace.historyMessageCountLabel': '{0} tin nhắn',
  'workspace.workspaceSyncFailedMessage': 'Đồng bộ không gian làm việc thất bại: {0}',
  'workspace.imageSentLabel': 'Đã gửi ảnh',
  'workspace.videoRequestedNote': 'Đã yêu cầu một video tại đây.',
  'workspace.canvasUploadFailedMessage': 'Tải ảnh canvas lên thất bại, gia sư chỉ nhận được văn bản: {0}',
  'workspace.resumingVideoMessage': 'Đang kết nối lại với tiến trình kết xuất...',
  'workspace.resumeVideoLabel': 'Kết nối lại',
  'workspace.tutorOfflineTitle': 'Gia sư AI không khả dụng',
  'workspace.tutorOfflineBody': 'Các câu trả lời bên dưới dùng văn bản dự phòng, nên giai đoạn của bạn sẽ không tiến lên cho đến khi gia sư trở lại. Hãy thử lại sau ít phút.',
  'workspace.feedbackCorrectLabel': 'Chính xác',
  'workspace.feedbackPartialLabel': 'Gần đúng',
  'workspace.feedbackIncorrectLabel': 'Chưa đúng',
  'workspace.misconceptionLabel': 'Phát hiện hiểu sai',
  'workspace.masteryDeltaUpLabel': 'Thành thạo +{0}%',
  'workspace.masteryDeltaDownLabel': 'Thành thạo -{0}%',
  'workspace.masteryDeltaFlatLabel': 'Mức thành thạo không đổi',
  'workspace.hintLevelLabel': 'Mức gợi ý {0}',
  'workspace.whyThisModuleLabel': 'Vì sao là mô-đun này?',
  'workspace.deleteSessionLabel': 'Xóa phiên',
  'workspace.deleteSessionConfirmBody': 'Phiên trò chuyện này sẽ bị xóa vĩnh viễn. Tiếp tục?',
  'loadingPosttestLabel': 'Đang tải Posttest',
  'preparingAdaptivePosttestFromBackendLabel': 'Đang chuẩn bị posttest thích ứng từ backend.',
  'posttestUnavailableLabel': 'Posttest không khả dụng',
  'backendReturnedNoPosttestQuestionsLabel': 'Backend không trả về câu hỏi posttest nào.',
  'tryAgainLabel2': 'Thử lại',
  'questionsMediumHardBasedWhatLabel': '10 câu hỏi: 3 trung bình và 7 khó dựa trên những gì bạn đã học.',
  'continueLabel2': 'Tiếp tục',
  'finishPosttestLabel': 'Hoàn thành posttest',
  'loadingDailyEvalsLabel': 'Đang tải Đánh giá hằng ngày',
  'fetchingSpacedReviewQuestionsFromLabel': 'Đang lấy câu hỏi ôn tập ngắt quãng từ backend.',
  'dailyEvalsUnavailableLabel': 'Đánh giá hằng ngày không khả dụng',
  'backendReturnedNoReviewQuestionsLabel': 'Backend không trả về câu hỏi ôn tập nào.',
  'dashboardUnavailableLabel': 'Bảng điều khiển không khả dụng',
  'retryLabel2': 'Thử lại',
  'loadingDashboardLabel': 'Đang tải bảng điều khiển',
  'fetchingProfileFromBackendLabel': 'Đang lấy hồ sơ của bạn từ backend.',
  'elementarySchoolLabel': 'Tiểu học',
  'juniorHighSchoolLabel': 'Trung học cơ sở',
  'seniorHighSchoolLabel': 'Trung học phổ thông',
  'universityLabel': 'Đại học',
  'pretestProgressLabel': 'Bài kiểm tra đầu vào đang diễn ra',
  'submittedAnswersSavedContinueFromLabel': 'Các câu trả lời đã nộp được lưu lại. Hãy tiếp tục từ câu hỏi gần nhất.',
  'continuePretestLabel': 'Tiếp tục bài kiểm tra đầu vào',
  'createLearningGoalLabel': 'Tạo mục tiêu học tập',
  'createLearningGoalSoWicaraLabel': 'Hãy tạo mục tiêu học tập để WICARA chuẩn bị lộ trình và không gian làm việc.',
  'pickGoalSubjectBeforeOpeningLabel': 'Hãy chọn mục tiêu trong môn học này trước khi mở không gian làm việc.',
  'nextModuleLabel': 'Mô-đun tiếp theo',
  'progressLabel2': 'Đang diễn ra',
  'readyLabel': 'Sẵn sàng',
  'completedLabel': 'Đã hoàn thành',
  'pausedLabel': 'Đã tạm dừng',
  'needsReviewLabel2': 'Cần ôn tập',
  'activeLabel': 'Đang hoạt động',
  'noModuleReadyYetLabel': 'Chưa có mô-đun nào sẵn sàng',
  'goalDoesNotHaveActiveLabel': 'Mục tiêu này chưa có mô-đun đang hoạt động.',
  'createChooseAnotherGoalStartLabel': 'Hãy tạo hoặc chọn mục tiêu khác để bắt đầu học.',
  'noGeneratedVideosReadyYetLabel': 'Chưa có video nào được tạo xong.',
  'videosFromBackendJobsSavedLabel': 'Video từ các tác vụ backend được lưu tại đây.',
  'noDailyEvaluationAssignedYetLabel': 'Chưa có bài đánh giá hằng ngày nào được giao.',
  'noEvaluationLabel': 'Không có đánh giá',
  'answerConfidenceLevelLabel': 'Mức độ tự tin về câu trả lời',
  'howConfidentAnswerLabel': 'Bạn tự tin đến mức nào với câu trả lời của mình?',
  'chooseNotConfidentVeryConfidentLabel': 'Chọn từ 0 (không tự tin) đến 10 (rất tự tin).',
  'masteryConfirmedLabel': 'Đã xác nhận thành thạo',
  'reviewNeededFromPosttestResultsLabel': 'Cần ôn tập dựa trên kết quả posttest',
  'posttestResultsLabel': 'Kết quả Posttest',
  'scoreSummaryLearningProgressionDecisionLabel': 'Bản tóm tắt điểm và quyết định tiến độ học tập đến từ backend.',
  'correctnessLabel': 'Độ chính xác',
  'correctLabel2': 'Đúng',
  'decisionLabel': 'Quyết định',
  'trackProgressLabel': 'Tiến độ lộ trình',
  'continueLearningLabel2': 'Tiếp tục học',
  'reviewWeakAreasLabel': 'Ôn lại các phần còn yếu',
  'moduleCompleteNextModuleNowLabel': 'Mô-đun này đã hoàn tất và mô-đun tiếp theo đã sẵn sàng.',
  'learningGoalCompleteLabel': 'Mục tiêu học tập này đã hoàn tất.',
  'backendConfirmedModuleAsPassedLabel': 'Backend đã xác nhận mô-đun này đạt. Hãy làm mới Trang chủ để xem bước lộ trình tiếp theo.',
  'backendRequiresReviewRemainingWeakLabel': 'Backend yêu cầu ôn lại các phần còn yếu trước khi thử lại.',
  'conceptResultsLabel': 'Kết quả theo khái niệm',
  'noPosttestNodesHaveBeenLabel': 'Chưa có nút posttest nào được đánh giá.',
  'scoreLabel2': 'Điểm',
  'profileUpdatedLabel': 'Đã cập nhật hồ sơ.',
  'localAiLitertLmLabel': 'AI cục bộ (LiteRT-LM)',
  'installInitializeModelLabel': 'Cài đặt & khởi tạo mô hình',
  'reportUnavailableLabel': 'Báo cáo không khả dụng',
  'openDetailsLabel': 'Mở chi tiết',
  'loadingWeekLabel': 'Đang tải tuần này',
  'syncingLabel': 'Đang đồng bộ',
  'fetchingReportDataFromBackendLabel': 'Đang lấy dữ liệu báo cáo từ backend.',
  'noDataYetLabel': 'Chưa có dữ liệu',
  'startLabel': 'Bắt đầu',
  'takeDailyEvaluationsFirstPopulateLabel': 'Hãy làm đánh giá hằng ngày trước để có dữ liệu cho biểu đồ này.',
  'weekTrendLabel': 'Xu hướng 4 tuần',
  'ptsLabel': 'điểm',
  'averageAccuracyLabel': 'Độ chính xác trung bình',
  'scoresLabel': 'Điểm số',
  'preTestPostTestChangeLabel': 'Kiểm tra trước, Kiểm tra sau và Thay đổi thể hiện biến động điểm trung bình.',
  'preTestLabel2': 'Kiểm tra trước',
  'postTestLabel2': 'Kiểm tra sau',
  'changeLabel': 'Thay đổi',
  'learningReportUnavailableLabel': 'Báo cáo học tập không khả dụng',
  'loadingLearningReportLabel': 'Đang tải Báo cáo học tập',
  'fetchingWeeklyProgressSummaryLabel': 'Đang lấy bản tóm tắt tiến độ hằng tuần.',
  'weekSummaryLabel': 'Tóm tắt tuần này',
  'answerAccuracyLabel': 'Độ chính xác câu trả lời',
  'fixedGapsLabel2': 'Lỗ hổng đã khắc phục',
  'remainingGapsLabel2': 'Lỗ hổng còn lại',
  'answerAccuracyPercentageCorrectAnswersLabel': 'Độ chính xác câu trả lời = tỷ lệ phần trăm câu đúng trong khoảng thời gian đã chọn.',
  'weekProgressLabel': 'Tiến độ 4 tuần',
  'trackAccuracyAttemptVolumeGapLabel': 'Theo dõi độ chính xác, số lượt làm và biến động lỗ hổng theo tuần.',
  'effortVsImpactLabel': 'Nỗ lực và tác động',
  'attemptsLabel': 'Lượt làm',
  'activeDaysLabel': 'Số ngày hoạt động',
  'impactLabel': 'Tác động',
  'strongConceptsVsNeedsImprovementLabel': 'Khái niệm vững và Khái niệm cần cải thiện',
  'focusConceptsBiggestLiftOnesLabel': 'Tập trung vào các khái niệm tiến bộ nhiều nhất và những khái niệm còn rủi ro.',
  'numberRightShowsConceptMasteryLabel': 'Số bên phải cho biết mức thay đổi thành thạo khái niệm (%) trong khoảng này.',
  'nowStrongLabel': 'Nay đã vững',
  'noConceptsShowedSignificantImprovementLabel': 'Không có khái niệm nào cải thiện đáng kể trong tuần này.',
  'needsImprovementLabel': 'Cần cải thiện',
  'noRiskConceptsRangeLabel': 'Không có khái niệm rủi ro trong khoảng này.',
  'weekLabel2': 'Tuần này',
  'lastWeekLabel': 'Tuần trước',
  'lastWeeksLabel': '4 tuần qua',
  'averageScoreLabel': 'Điểm trung bình',
  'notEnoughMatchedPreTestLabel': 'Chưa đủ dữ liệu kiểm tra trước và sau khớp nhau.',
  'reportRequestTimedOutPleaseLabel': 'Yêu cầu báo cáo đã hết thời gian. Vui lòng thử lại.',
  'reportCouldNotLoadedPleaseLabel': 'Không tải được báo cáo. Vui lòng thử lại.',
  'completeDataLabel': 'Dữ liệu đầy đủ',
  'partialDataLabel': 'Dữ liệu một phần',
  'earlyDataLabel': 'Dữ liệu ban đầu',
  'highLeverageLabel': 'Đòn bẩy cao',
  'steadyLabel': 'Ổn định',
  'needsFocusLabel': 'Cần tập trung',
  'noSignalLabel': 'Không có tín hiệu',
  'reportBuiltFromSufficientlyCompleteLabel': 'Báo cáo này được dựng từ lịch sử đủ đầy đủ.',
  'dataExistsButComparisonHistoryLabel': 'Đã có dữ liệu, nhưng lịch sử so sánh vẫn chưa đầy đủ.',
  'dataStillThinSoSomeLabel': 'Dữ liệu còn ít, nên một số nhận định chỉ là ước tính ban đầu.',
  'dataQualityStatusNotDefinedLabel': 'Chưa xác định trạng thái chất lượng dữ liệu.',
  'overallLabel2': 'Tổng thể',
  'applicationLabel2': 'Ứng dụng',
  'analysisLabel2': 'Phân tích',
  'weekLabel3': '0 tuần này',
  'learningPerformanceLabel': 'Hiệu suất học tập',
  'noAssessmentAttemptsRangeYetLabel': 'Chưa có lượt làm bài đánh giá nào trong khoảng này. Hãy làm đánh giá hằng ngày để dựng biểu đồ.',
  'useAsLearningGoalLabel': 'Dùng cái này làm mục tiêu học tập của bạn?',
  'chooseAnotherNodeLabel': 'Chọn nút khác',
  'startPretestLabel': 'Bắt đầu bài kiểm tra đầu vào',
  'activeGoalFoundLabel': 'Đã tìm thấy mục tiêu đang hoạt động',
  'backLabel2': 'Quay lại',
  'continueExistingGoalLabel': 'Tiếp tục mục tiêu hiện có',
  'useAsNewGoalLabel': 'Dùng làm mục tiêu mới',
  'visualizePrerequisitesGapsNextConceptsLabel': 'Trực quan hóa kiến thức tiên quyết, lỗ hổng và khái niệm tiếp theo.',
  'alreadyHaveActiveGoalNodeLabel': 'Bạn đã có mục tiêu đang hoạt động cho nút này:',
  'canContinueGoalGoBackLabel': 'Bạn có thể tiếp tục mục tiêu này, hoặc quay lại để chọn nút.',
  'findLearningGoalNodeLabel': 'Tìm nút mục tiêu học tập',
  'searchAgainLabel': 'Tìm lại',
  'searchAgainNewQueryLabel': 'Tìm lại với truy vấn mới',
  'sureWantTakeLabel': 'Bạn có chắc muốn chọn mục này?',
  'nodeDetailLabel': 'Chi tiết nút',
  'descriptionLabel': 'Mô tả',
  'subjectLabel2': 'Môn học',
  'matchLabel': 'Độ khớp',
  'seeGraphLabel': 'Xem đồ thị',
  'lockLabel': 'Khóa',
  'findLearningGoalFirstLabel': 'Hãy tìm mục tiêu học tập trước',
  'typeGoalThenWicaraWillLabel': 'Nhập mục tiêu của bạn, rồi WICARA sẽ khớp nó với một nút tài liệu. Bài kiểm tra đầu vào chỉ bắt đầu sau khi bạn xác nhận nút.',
  'nodeNotCertainLabel': 'Nút chưa chắc chắn',
  'tryAddingGradeSubjectMoreLabel': 'Hãy thử thêm khối lớp, môn học hoặc chủ đề cụ thể hơn.',
  'pickClosestCandidateLabel': 'Chọn ứng viên gần nhất',
  'recommendedNodeLabel': 'Nút được đề xuất',
  'otherPossibleNodesLabel': 'Các nút khả dĩ khác',
  'editPromptLabel': 'Sửa câu lệnh',
  'viewDetailLabel': 'Xem chi tiết',
  'descriptionNotFoundLabel': 'Không tìm thấy mô tả.',
  'nodeBelowGradeLevelCanLabel': 'Nút này thấp hơn khối lớp của bạn; nó có thể củng cố nền tảng.',
  'nodeAboveGradeLevelMayLabel': 'Nút này cao hơn khối lớp của bạn; có thể sẽ khó hơn.',
  'nodeFitsGradeLevelLabel': 'Nút này phù hợp với khối lớp của bạn.',
  'mathLabel': 'Toán',
  'physicsLabel': 'Vật lý',
  'chemistryLabel': 'Hóa học',
  'biologyLabel': 'Sinh học',
  'uploadingWorkImageLabel': 'Đang tải ảnh bài làm của bạn lên...',
  'answerSentEvaluatingWorkPreparingLabel': 'Đã gửi câu trả lời. Đang đánh giá bài làm và chuẩn bị câu hỏi tiếp theo...',
  'submitAnswerLabel': 'Nộp câu trả lời',
  'addReasoningSketchLabel': 'Thêm lập luận / bản phác',
  'hideWorkEvidenceLabel': 'Ẩn bằng chứng bài làm',
  'workEvidenceLabel': 'Bằng chứng bài làm',
  'typeStepsUploadPhotoWorkLabel': 'Nhập các bước của bạn, tải ảnh bài làm lên, hoặc dùng cả hai. AI sẽ đọc ảnh như các bước giải.',
  'writeSolutionStepsLabel': 'Viết các bước giải của bạn...',
  'uploadWorkImageLabel': 'Tải ảnh bài làm lên',
  'removeImageLabel': 'Xóa ảnh',
  'submitAnswerEvidenceLabel': 'Nộp câu trả lời kèm bằng chứng',
  'correctLabel3': 'đúng',
  'noAnswersLabel': 'Không có câu trả lời',
  'officialMcqScoreLabel': 'Điểm trắc nghiệm chính thức',
  'reportLabel': 'Báo cáo',
  'whatLooksStrongLabel': 'Điểm nào đang vững',
  'whatNeedsWorkLabel': 'Điểm nào cần cải thiện',
  'evidenceNotesLabel': 'Ghi chú bằng chứng',
  'checkedNodesLabel': 'Các nút đã kiểm tra',
  'levelLabel': 'Cấp độ',
  'nextPathFocusLabel': 'Trọng tâm lộ trình tiếp theo',
  'reasoningSuggestsMisconceptionNodeLabel': 'Lập luận cho thấy có hiểu sai ở nút này.',
  'therePossibleCarelessChoiceDespiteLabel': 'Có thể là chọn nhầm do bất cẩn dù lập luận hợp lý.',
  'evidenceWasStoredButNoLabel': 'Bằng chứng đã được lưu, nhưng không có bước viết nào để phân tích.',
  'noSubjectGoalsYetLabel': 'Chưa có mục tiêu {0}',
  'subjectGoalsLabel': 'Mục tiêu {0}',
  'percentCompleteLabel': 'hoàn thành {0}%',
  'moduleStatusLabel': 'Trạng thái mô-đun: {0}',
  'moduleStatusWithMinutesLabel': '{0} phút - trạng thái mô-đun: {1}',
  'sessionReturnsToPhaseLabel': 'Phiên quay lại giai đoạn {0} để khắc phục.{1}',
  'targetPassedLabel': 'Đúng {0}/{1}. Mục tiêu này đạt.',
  'conceptMarkedForReviewLabel': 'Đúng {0}/{1}. Backend đã đánh dấu khái niệm này cần ôn tập.',
  'accuracyPercentLabel': 'Độ chính xác {0}%',
  'fixedGapsDeltaLabel': '+{0} tuần này',
  'remainingGapsDeltaLabel': '{0} tuần này',
  'weeklyPointSummaryLabel': '{0} lượt làm • {1} lỗ hổng đã khắc phục • {2} lỗ hổng còn lại',
  'positiveDeltaThisWeekLabel': '+{0} tuần này',
  'deltaThisWeekLabel': '{0} tuần này',
  'activeGoalConflictBodyLabel': 'Bạn đã có mục tiêu đang hoạt động cho "{0}". Bạn có thể tiếp tục mục tiêu đó hoặc quay lại chọn nút.',
  'reasoningQualityLabel': 'Chất lượng lập luận: {0}{1}.',
  'learnConceptInGraphLabel': 'Học {0} trong đồ thị kiến thức tiên quyết.',
  'outputValidJsonOnlyLabel': 'Chỉ xuất JSON hợp lệ:',
  'workspace.collapseLabel': 'Thu gọn',
  'workspace.detailsLabel': 'Chi tiết',
  'workspace.finalTargetLabel': 'Mục tiêu cuối: {0}',
  'workspace.phaseTransitionReadyLabel': 'Sẵn sàng chuyển giai đoạn',
  'workspace.continueThisPhaseLabel': 'Tiếp tục giai đoạn này',
};
